/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import { AttioError } from "./attioerror.js";

export const NotFoundType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type NotFoundType = ClosedEnum<typeof NotFoundType>;

export const NotFoundCode = {
  NotFound: "not_found",
} as const;
export type NotFoundCode = ClosedEnum<typeof NotFoundCode>;

/**
 * Not Found
 */
export type GetV2ObjectsObjectNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2ObjectsObjectNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2ObjectsObjectNotFoundErrorData;

  constructor(
    err: GetV2ObjectsObjectNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2ObjectsObjectNotFoundError";
  }
}

export const ConflictType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type ConflictType = ClosedEnum<typeof ConflictType>;

export const ConflictCode = {
  SlugConflict: "slug_conflict",
} as const;
export type ConflictCode = ClosedEnum<typeof ConflictCode>;

/**
 * Conflict
 */
export type PostV2ObjectsSlugConflictErrorData = {
  statusCode: number;
  type: ConflictType;
  code: ConflictCode;
  message: string;
};

/**
 * Conflict
 */
export class PostV2ObjectsSlugConflictError extends AttioError {
  type: ConflictType;
  code: ConflictCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ObjectsSlugConflictErrorData;

  constructor(
    err: PostV2ObjectsSlugConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ObjectsSlugConflictError";
  }
}

/**
 * Conflict
 */
export type PatchV2ObjectsObjectSlugConflictErrorData = {
  statusCode: number;
  type: ConflictType;
  code: ConflictCode;
  message: string;
};

/**
 * Conflict
 */
export class PatchV2ObjectsObjectSlugConflictError extends AttioError {
  type: ConflictType;
  code: ConflictCode;

  /** The original data that was passed to this error instance. */
  data$: PatchV2ObjectsObjectSlugConflictErrorData;

  constructor(
    err: PatchV2ObjectsObjectSlugConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PatchV2ObjectsObjectSlugConflictError";
  }
}

export const BadRequestType = {
  InvalidRequestError: "invalid_request_error",
} as const;
export type BadRequestType = ClosedEnum<typeof BadRequestType>;

export const CodeValidationType = {
  ValidationType: "validation_type",
} as const;
export type CodeValidationType = ClosedEnum<typeof CodeValidationType>;

/**
 * Bad Request
 */
export type PatchV2ObjectsObjectValidationTypeErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: CodeValidationType;
  message: string;
};

/**
 * Bad Request
 */
export class PatchV2ObjectsObjectValidationTypeError extends AttioError {
  type: BadRequestType;
  code: CodeValidationType;

  /** The original data that was passed to this error instance. */
  data$: PatchV2ObjectsObjectValidationTypeErrorData;

  constructor(
    err: PatchV2ObjectsObjectValidationTypeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PatchV2ObjectsObjectValidationTypeError";
  }
}

/**
 * Conflict
 */
export type PostV2TargetIdentifierAttributesSlugConflictErrorData = {
  statusCode: number;
  type: ConflictType;
  code: ConflictCode;
  message: string;
};

/**
 * Conflict
 */
export class PostV2TargetIdentifierAttributesSlugConflictError
  extends AttioError
{
  type: ConflictType;
  code: ConflictCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2TargetIdentifierAttributesSlugConflictErrorData;

  constructor(
    err: PostV2TargetIdentifierAttributesSlugConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2TargetIdentifierAttributesSlugConflictError";
  }
}

/**
 * Not Found
 */
export type PostV2TargetIdentifierAttributesNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class PostV2TargetIdentifierAttributesNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2TargetIdentifierAttributesNotFoundErrorData;

  constructor(
    err: PostV2TargetIdentifierAttributesNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2TargetIdentifierAttributesNotFoundError";
  }
}

/**
 * Bad Request
 */
export type PostV2TargetIdentifierAttributesValidationTypeErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: CodeValidationType;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2TargetIdentifierAttributesValidationTypeError
  extends AttioError
{
  type: BadRequestType;
  code: CodeValidationType;

  /** The original data that was passed to this error instance. */
  data$: PostV2TargetIdentifierAttributesValidationTypeErrorData;

  constructor(
    err: PostV2TargetIdentifierAttributesValidationTypeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2TargetIdentifierAttributesValidationTypeError";
  }
}

/**
 * Not Found
 */
export type GetV2TargetIdentifierAttributesAttributeNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2TargetIdentifierAttributesAttributeNotFoundError
  extends AttioError
{
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2TargetIdentifierAttributesAttributeNotFoundErrorData;

  constructor(
    err: GetV2TargetIdentifierAttributesAttributeNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2TargetIdentifierAttributesAttributeNotFoundError";
  }
}

export const PatchV2TargetIdentifierAttributesAttributeCode = {
  SystemEditUnauthorized: "system_edit_unauthorized",
} as const;
export type PatchV2TargetIdentifierAttributesAttributeCode = ClosedEnum<
  typeof PatchV2TargetIdentifierAttributesAttributeCode
>;

/**
 * Bad Request
 */
export type SystemEditUnauthorizedErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: PatchV2TargetIdentifierAttributesAttributeCode;
  message: string;
};

/**
 * Bad Request
 */
export class SystemEditUnauthorizedError extends AttioError {
  type: BadRequestType;
  code: PatchV2TargetIdentifierAttributesAttributeCode;

  /** The original data that was passed to this error instance. */
  data$: SystemEditUnauthorizedErrorData;

  constructor(
    err: SystemEditUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "SystemEditUnauthorizedError";
  }
}

/**
 * Conflict
 */
export type PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData =
  {
    statusCode: number;
    type: ConflictType;
    code: ConflictCode;
    message: string;
  };

/**
 * Conflict
 */
export class PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictError
  extends AttioError
{
  type: ConflictType;
  code: ConflictCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData;

  constructor(
    err: PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name =
      "PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictError";
  }
}

/**
 * Bad Request
 */
export type PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData =
  {
    statusCode: number;
    type: BadRequestType;
    code: CodeValidationType;
    message: string;
  };

/**
 * Bad Request
 */
export class PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeError
  extends AttioError
{
  type: BadRequestType;
  code: CodeValidationType;

  /** The original data that was passed to this error instance. */
  data$:
    PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData;

  constructor(
    err:
      PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name =
      "PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeError";
  }
}

export const BadRequestCode = {
  ValueNotFound: "value_not_found",
  MissingValue: "missing_value",
} as const;
export type BadRequestCode = ClosedEnum<typeof BadRequestCode>;

/**
 * Bad Request
 */
export type PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestErrorData =
  {
    statusCode: number;
    type: BadRequestType;
    code: BadRequestCode;
    message: string;
  };

/**
 * Bad Request
 */
export class PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestError
  extends AttioError
{
  type: BadRequestType;
  code: BadRequestCode;

  /** The original data that was passed to this error instance. */
  data$:
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestErrorData;

  constructor(
    err:
      PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name =
      "PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestError";
  }
}

/**
 * Conflict
 */
export type PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictErrorData =
  {
    statusCode: number;
    type: ConflictType;
    code: ConflictCode;
    message: string;
  };

/**
 * Conflict
 */
export class PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictError
  extends AttioError
{
  type: ConflictType;
  code: ConflictCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictErrorData;

  constructor(
    err: PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name =
      "PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictError";
  }
}

/**
 * Bad Request
 */
export type PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeErrorData =
  {
    statusCode: number;
    type: BadRequestType;
    code: CodeValidationType;
    message: string;
  };

/**
 * Bad Request
 */
export class PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeError
  extends AttioError
{
  type: BadRequestType;
  code: CodeValidationType;

  /** The original data that was passed to this error instance. */
  data$:
    PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeErrorData;

  constructor(
    err:
      PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name =
      "PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeError";
  }
}

/**
 * Bad Request
 */
export type PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestErrorData =
  {
    statusCode: number;
    type: BadRequestType;
    code: BadRequestCode;
    message: string;
  };

/**
 * Bad Request
 */
export class PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestError
  extends AttioError
{
  type: BadRequestType;
  code: BadRequestCode;

  /** The original data that was passed to this error instance. */
  data$:
    PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestErrorData;

  constructor(
    err:
      PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name =
      "PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestError";
  }
}

/**
 * Not Found
 */
export type PostV2ObjectsObjectRecordsQueryNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class PostV2ObjectsObjectRecordsQueryNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ObjectsObjectRecordsQueryNotFoundErrorData;

  constructor(
    err: PostV2ObjectsObjectRecordsQueryNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ObjectsObjectRecordsQueryNotFoundError";
  }
}

export const PostV2ObjectsObjectRecordsQueryCode = {
  FilterError: "filter_error",
} as const;
export type PostV2ObjectsObjectRecordsQueryCode = ClosedEnum<
  typeof PostV2ObjectsObjectRecordsQueryCode
>;

/**
 * Bad Request
 */
export type FilterErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: PostV2ObjectsObjectRecordsQueryCode;
  message: string;
};

/**
 * Bad Request
 */
export class FilterError extends AttioError {
  type: BadRequestType;
  code: PostV2ObjectsObjectRecordsQueryCode;

  /** The original data that was passed to this error instance. */
  data$: FilterErrorData;

  constructor(
    err: FilterErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "FilterError";
  }
}

/**
 * Bad Request
 */
export type PostV2ObjectsObjectRecordsInvalidRequestErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: BadRequestCode;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2ObjectsObjectRecordsInvalidRequestError extends AttioError {
  type: BadRequestType;
  code: BadRequestCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ObjectsObjectRecordsInvalidRequestErrorData;

  constructor(
    err: PostV2ObjectsObjectRecordsInvalidRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ObjectsObjectRecordsInvalidRequestError";
  }
}

/**
 * Bad Request
 */
export type PutV2ObjectsObjectRecordsInvalidRequestErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: BadRequestCode;
  message: string;
};

/**
 * Bad Request
 */
export class PutV2ObjectsObjectRecordsInvalidRequestError extends AttioError {
  type: BadRequestType;
  code: BadRequestCode;

  /** The original data that was passed to this error instance. */
  data$: PutV2ObjectsObjectRecordsInvalidRequestErrorData;

  constructor(
    err: PutV2ObjectsObjectRecordsInvalidRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PutV2ObjectsObjectRecordsInvalidRequestError";
  }
}

/**
 * Not Found
 */
export type GetV2ObjectsObjectRecordsRecordIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2ObjectsObjectRecordsRecordIdNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2ObjectsObjectRecordsRecordIdNotFoundErrorData;

  constructor(
    err: GetV2ObjectsObjectRecordsRecordIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2ObjectsObjectRecordsRecordIdNotFoundError";
  }
}

export const CodeMissingValue = {
  MissingValue: "missing_value",
} as const;
export type CodeMissingValue = ClosedEnum<typeof CodeMissingValue>;

/**
 * Bad Request
 */
export type MissingValueErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: CodeMissingValue;
  message: string;
};

/**
 * Bad Request
 */
export class MissingValueError extends AttioError {
  type: BadRequestType;
  code: CodeMissingValue;

  /** The original data that was passed to this error instance. */
  data$: MissingValueErrorData;

  constructor(
    err: MissingValueErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "MissingValueError";
  }
}

/**
 * Bad Request
 */
export type GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesValidationTypeErrorData =
  {
    statusCode: number;
    type: BadRequestType;
    code: CodeValidationType;
    message: string;
  };

/**
 * Bad Request
 */
export class GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesValidationTypeError
  extends AttioError
{
  type: BadRequestType;
  code: CodeValidationType;

  /** The original data that was passed to this error instance. */
  data$:
    GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesValidationTypeErrorData;

  constructor(
    err:
      GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesValidationTypeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name =
      "GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesValidationTypeError";
  }
}

/**
 * Not Found
 */
export type PostV2ListsNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class PostV2ListsNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ListsNotFoundErrorData;

  constructor(
    err: PostV2ListsNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ListsNotFoundError";
  }
}

export const PostV2ListsType = {
  AuthError: "auth_error",
} as const;
export type PostV2ListsType = ClosedEnum<typeof PostV2ListsType>;

export const PostV2ListsCode = {
  BillingError: "billing_error",
} as const;
export type PostV2ListsCode = ClosedEnum<typeof PostV2ListsCode>;

/**
 * Forbidden
 */
export type BillingErrorData = {
  statusCode: number;
  type: PostV2ListsType;
  code: PostV2ListsCode;
  message: string;
};

/**
 * Forbidden
 */
export class BillingError extends AttioError {
  type: PostV2ListsType;
  code: PostV2ListsCode;

  /** The original data that was passed to this error instance. */
  data$: BillingErrorData;

  constructor(
    err: BillingErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "BillingError";
  }
}

/**
 * Bad Request
 */
export type PostV2ListsInvalidRequestErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: BadRequestCode;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2ListsInvalidRequestError extends AttioError {
  type: BadRequestType;
  code: BadRequestCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ListsInvalidRequestErrorData;

  constructor(
    err: PostV2ListsInvalidRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ListsInvalidRequestError";
  }
}

/**
 * Not Found
 */
export type GetV2ListsListNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2ListsListNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2ListsListNotFoundErrorData;

  constructor(
    err: GetV2ListsListNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2ListsListNotFoundError";
  }
}

/**
 * Not Found
 */
export type PostV2ListsListEntriesNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class PostV2ListsListEntriesNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ListsListEntriesNotFoundErrorData;

  constructor(
    err: PostV2ListsListEntriesNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ListsListEntriesNotFoundError";
  }
}

/**
 * Bad Request
 */
export type PostV2ListsListEntriesInvalidRequestErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: BadRequestCode;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2ListsListEntriesInvalidRequestError extends AttioError {
  type: BadRequestType;
  code: BadRequestCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2ListsListEntriesInvalidRequestErrorData;

  constructor(
    err: PostV2ListsListEntriesInvalidRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2ListsListEntriesInvalidRequestError";
  }
}

/**
 * Not Found
 */
export type PutV2ListsListEntriesNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class PutV2ListsListEntriesNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: PutV2ListsListEntriesNotFoundErrorData;

  constructor(
    err: PutV2ListsListEntriesNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PutV2ListsListEntriesNotFoundError";
  }
}

export const PutV2ListsListEntriesCode = {
  MultipleMatchResults: "multiple_match_results",
} as const;
export type PutV2ListsListEntriesCode = ClosedEnum<
  typeof PutV2ListsListEntriesCode
>;

/**
 * Bad Request
 */
export type MultipleMatchResultsErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: PutV2ListsListEntriesCode;
  message: string;
};

/**
 * Bad Request
 */
export class MultipleMatchResultsError extends AttioError {
  type: BadRequestType;
  code: PutV2ListsListEntriesCode;

  /** The original data that was passed to this error instance. */
  data$: MultipleMatchResultsErrorData;

  constructor(
    err: MultipleMatchResultsErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "MultipleMatchResultsError";
  }
}

export const CodeImmutableValue = {
  ImmutableValue: "immutable_value",
} as const;
export type CodeImmutableValue = ClosedEnum<typeof CodeImmutableValue>;

/**
 * Bad Request
 */
export type ImmutableValueErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: CodeImmutableValue;
  message: string;
};

/**
 * Bad Request
 */
export class ImmutableValueError extends AttioError {
  type: BadRequestType;
  code: CodeImmutableValue;

  /** The original data that was passed to this error instance. */
  data$: ImmutableValueErrorData;

  constructor(
    err: ImmutableValueErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "ImmutableValueError";
  }
}

/**
 * Not Found
 */
export type GetV2WorkspaceMembersWorkspaceMemberIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError
  extends AttioError
{
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2WorkspaceMembersWorkspaceMemberIdNotFoundErrorData;

  constructor(
    err: GetV2WorkspaceMembersWorkspaceMemberIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError";
  }
}

/**
 * Not Found
 */
export type GetV2NotesNoteIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2NotesNoteIdNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2NotesNoteIdNotFoundErrorData;

  constructor(
    err: GetV2NotesNoteIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2NotesNoteIdNotFoundError";
  }
}

/**
 * Bad Request
 */
export type PostV2TasksValidationTypeErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: CodeValidationType;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2TasksValidationTypeError extends AttioError {
  type: BadRequestType;
  code: CodeValidationType;

  /** The original data that was passed to this error instance. */
  data$: PostV2TasksValidationTypeErrorData;

  constructor(
    err: PostV2TasksValidationTypeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2TasksValidationTypeError";
  }
}

/**
 * Not Found
 */
export type GetV2TasksTaskIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2TasksTaskIdNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2TasksTaskIdNotFoundErrorData;

  constructor(
    err: GetV2TasksTaskIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2TasksTaskIdNotFoundError";
  }
}

/**
 * Not Found
 */
export type PatchV2TasksTaskIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class PatchV2TasksTaskIdNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: PatchV2TasksTaskIdNotFoundErrorData;

  constructor(
    err: PatchV2TasksTaskIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PatchV2TasksTaskIdNotFoundError";
  }
}

/**
 * Not Found
 */
export type GetV2ThreadsThreadIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2ThreadsThreadIdNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2ThreadsThreadIdNotFoundErrorData;

  constructor(
    err: GetV2ThreadsThreadIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2ThreadsThreadIdNotFoundError";
  }
}

/**
 * Bad Request
 */
export type PostV2CommentsInvalidRequestErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: BadRequestCode;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2CommentsInvalidRequestError extends AttioError {
  type: BadRequestType;
  code: BadRequestCode;

  /** The original data that was passed to this error instance. */
  data$: PostV2CommentsInvalidRequestErrorData;

  constructor(
    err: PostV2CommentsInvalidRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2CommentsInvalidRequestError";
  }
}

/**
 * Not Found
 */
export type GetV2CommentsCommentIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2CommentsCommentIdNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2CommentsCommentIdNotFoundErrorData;

  constructor(
    err: GetV2CommentsCommentIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2CommentsCommentIdNotFoundError";
  }
}

/**
 * Not Found
 */
export type DeleteV2CommentsCommentIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class DeleteV2CommentsCommentIdNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: DeleteV2CommentsCommentIdNotFoundErrorData;

  constructor(
    err: DeleteV2CommentsCommentIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "DeleteV2CommentsCommentIdNotFoundError";
  }
}

/**
 * Bad Request
 */
export type PostV2WebhooksValidationTypeErrorData = {
  statusCode: number;
  type: BadRequestType;
  code: CodeValidationType;
  message: string;
};

/**
 * Bad Request
 */
export class PostV2WebhooksValidationTypeError extends AttioError {
  type: BadRequestType;
  code: CodeValidationType;

  /** The original data that was passed to this error instance. */
  data$: PostV2WebhooksValidationTypeErrorData;

  constructor(
    err: PostV2WebhooksValidationTypeErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "PostV2WebhooksValidationTypeError";
  }
}

/**
 * Not Found
 */
export type GetV2WebhooksWebhookIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class GetV2WebhooksWebhookIdNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: GetV2WebhooksWebhookIdNotFoundErrorData;

  constructor(
    err: GetV2WebhooksWebhookIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "GetV2WebhooksWebhookIdNotFoundError";
  }
}

/**
 * Not Found
 */
export type DeleteV2WebhooksWebhookIdNotFoundErrorData = {
  statusCode: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

/**
 * Not Found
 */
export class DeleteV2WebhooksWebhookIdNotFoundError extends AttioError {
  type: NotFoundType;
  code: NotFoundCode;

  /** The original data that was passed to this error instance. */
  data$: DeleteV2WebhooksWebhookIdNotFoundErrorData;

  constructor(
    err: DeleteV2WebhooksWebhookIdNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.type = err.type;
    this.code = err.code;

    this.name = "DeleteV2WebhooksWebhookIdNotFoundError";
  }
}

/** @internal */
export const NotFoundType$inboundSchema: z.ZodEnum<typeof NotFoundType> =
  z.nativeEnum(NotFoundType);

/** @internal */
export const NotFoundCode$inboundSchema: z.ZodEnum<typeof NotFoundCode> =
  z.nativeEnum(NotFoundCode);

/** @internal */
export const GetV2ObjectsObjectNotFoundError$inboundSchema: z.ZodType<
  GetV2ObjectsObjectNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new GetV2ObjectsObjectNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const ConflictType$inboundSchema: z.ZodEnum<typeof ConflictType> =
  z.nativeEnum(ConflictType);

/** @internal */
export const ConflictCode$inboundSchema: z.ZodEnum<typeof ConflictCode> =
  z.nativeEnum(ConflictCode);

/** @internal */
export const PostV2ObjectsSlugConflictError$inboundSchema: z.ZodType<
  PostV2ObjectsSlugConflictError,
  unknown
> = z.object({
  status_code: z.number(),
  type: ConflictType$inboundSchema,
  code: ConflictCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PostV2ObjectsSlugConflictError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PatchV2ObjectsObjectSlugConflictError$inboundSchema: z.ZodType<
  PatchV2ObjectsObjectSlugConflictError,
  unknown
> = z.object({
  status_code: z.number(),
  type: ConflictType$inboundSchema,
  code: ConflictCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PatchV2ObjectsObjectSlugConflictError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const BadRequestType$inboundSchema: z.ZodEnum<
  typeof BadRequestType
> = z.nativeEnum(BadRequestType);

/** @internal */
export const CodeValidationType$inboundSchema: z.ZodEnum<
  typeof CodeValidationType
> = z.nativeEnum(CodeValidationType);

/** @internal */
export const PatchV2ObjectsObjectValidationTypeError$inboundSchema: z.ZodType<
  PatchV2ObjectsObjectValidationTypeError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: CodeValidationType$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PatchV2ObjectsObjectValidationTypeError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2TargetIdentifierAttributesSlugConflictError$inboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesSlugConflictError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: ConflictType$inboundSchema,
    code: ConflictCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2TargetIdentifierAttributesSlugConflictError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PostV2TargetIdentifierAttributesNotFoundError$inboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesNotFoundError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: NotFoundType$inboundSchema,
    code: NotFoundCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2TargetIdentifierAttributesNotFoundError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PostV2TargetIdentifierAttributesValidationTypeError$inboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesValidationTypeError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: BadRequestType$inboundSchema,
    code: CodeValidationType$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2TargetIdentifierAttributesValidationTypeError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeNotFoundError$inboundSchema:
  z.ZodType<
    GetV2TargetIdentifierAttributesAttributeNotFoundError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: NotFoundType$inboundSchema,
    code: NotFoundCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new GetV2TargetIdentifierAttributesAttributeNotFoundError(
        remapped,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeCode$inboundSchema:
  z.ZodEnum<typeof PatchV2TargetIdentifierAttributesAttributeCode> = z
    .nativeEnum(PatchV2TargetIdentifierAttributesAttributeCode);

/** @internal */
export const SystemEditUnauthorizedError$inboundSchema: z.ZodType<
  SystemEditUnauthorizedError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: PatchV2TargetIdentifierAttributesAttributeCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new SystemEditUnauthorizedError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictError$inboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: ConflictType$inboundSchema,
    code: ConflictCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2TargetIdentifierAttributesAttributeOptionsSlugConflictError(
        remapped,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeError$inboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: BadRequestType$inboundSchema,
    code: CodeValidationType$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2TargetIdentifierAttributesAttributeOptionsValidationTypeError(
        remapped,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const BadRequestCode$inboundSchema: z.ZodEnum<
  typeof BadRequestCode
> = z.nativeEnum(BadRequestCode);

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestError$inboundSchema:
  z.ZodType<
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: BadRequestType$inboundSchema,
    code: BadRequestCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PatchV2TargetIdentifierAttributesAttributeOptionsOptionInvalidRequestError(
        remapped,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictError$inboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: ConflictType$inboundSchema,
    code: ConflictCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2TargetIdentifierAttributesAttributeStatusesSlugConflictError(
        remapped,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeError$inboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: BadRequestType$inboundSchema,
    code: CodeValidationType$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2TargetIdentifierAttributesAttributeStatusesValidationTypeError(
        remapped,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestError$inboundSchema:
  z.ZodType<
    PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: BadRequestType$inboundSchema,
    code: BadRequestCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PatchV2TargetIdentifierAttributesAttributeStatusesStatusInvalidRequestError(
        remapped,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const PostV2ObjectsObjectRecordsQueryNotFoundError$inboundSchema:
  z.ZodType<
    PostV2ObjectsObjectRecordsQueryNotFoundError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: NotFoundType$inboundSchema,
    code: NotFoundCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2ObjectsObjectRecordsQueryNotFoundError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PostV2ObjectsObjectRecordsQueryCode$inboundSchema: z.ZodEnum<
  typeof PostV2ObjectsObjectRecordsQueryCode
> = z.nativeEnum(PostV2ObjectsObjectRecordsQueryCode);

/** @internal */
export const FilterError$inboundSchema: z.ZodType<
  FilterError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: PostV2ObjectsObjectRecordsQueryCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new FilterError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2ObjectsObjectRecordsInvalidRequestError$inboundSchema:
  z.ZodType<
    PostV2ObjectsObjectRecordsInvalidRequestError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: BadRequestType$inboundSchema,
    code: BadRequestCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PostV2ObjectsObjectRecordsInvalidRequestError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const PutV2ObjectsObjectRecordsInvalidRequestError$inboundSchema:
  z.ZodType<
    PutV2ObjectsObjectRecordsInvalidRequestError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: BadRequestType$inboundSchema,
    code: BadRequestCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new PutV2ObjectsObjectRecordsInvalidRequestError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetV2ObjectsObjectRecordsRecordIdNotFoundError$inboundSchema:
  z.ZodType<
    GetV2ObjectsObjectRecordsRecordIdNotFoundError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: NotFoundType$inboundSchema,
    code: NotFoundCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new GetV2ObjectsObjectRecordsRecordIdNotFoundError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const CodeMissingValue$inboundSchema: z.ZodEnum<
  typeof CodeMissingValue
> = z.nativeEnum(CodeMissingValue);

/** @internal */
export const MissingValueError$inboundSchema: z.ZodType<
  MissingValueError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: CodeMissingValue$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new MissingValueError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesValidationTypeError$inboundSchema:
  z.ZodType<
    GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesValidationTypeError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: BadRequestType$inboundSchema,
    code: CodeValidationType$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new GetV2ObjectsObjectRecordsRecordIdAttributesAttributeValuesValidationTypeError(
        remapped,
        { request: v.request$, response: v.response$, body: v.body$ },
      );
    });

/** @internal */
export const PostV2ListsNotFoundError$inboundSchema: z.ZodType<
  PostV2ListsNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PostV2ListsNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2ListsType$inboundSchema: z.ZodEnum<
  typeof PostV2ListsType
> = z.nativeEnum(PostV2ListsType);

/** @internal */
export const PostV2ListsCode$inboundSchema: z.ZodEnum<
  typeof PostV2ListsCode
> = z.nativeEnum(PostV2ListsCode);

/** @internal */
export const BillingError$inboundSchema: z.ZodType<
  BillingError,
  unknown
> = z.object({
  status_code: z.number(),
  type: PostV2ListsType$inboundSchema,
  code: PostV2ListsCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new BillingError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2ListsInvalidRequestError$inboundSchema: z.ZodType<
  PostV2ListsInvalidRequestError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: BadRequestCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PostV2ListsInvalidRequestError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetV2ListsListNotFoundError$inboundSchema: z.ZodType<
  GetV2ListsListNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new GetV2ListsListNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2ListsListEntriesNotFoundError$inboundSchema: z.ZodType<
  PostV2ListsListEntriesNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PostV2ListsListEntriesNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2ListsListEntriesInvalidRequestError$inboundSchema: z.ZodType<
  PostV2ListsListEntriesInvalidRequestError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: BadRequestCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PostV2ListsListEntriesInvalidRequestError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PutV2ListsListEntriesNotFoundError$inboundSchema: z.ZodType<
  PutV2ListsListEntriesNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PutV2ListsListEntriesNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PutV2ListsListEntriesCode$inboundSchema: z.ZodEnum<
  typeof PutV2ListsListEntriesCode
> = z.nativeEnum(PutV2ListsListEntriesCode);

/** @internal */
export const MultipleMatchResultsError$inboundSchema: z.ZodType<
  MultipleMatchResultsError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: PutV2ListsListEntriesCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new MultipleMatchResultsError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const CodeImmutableValue$inboundSchema: z.ZodEnum<
  typeof CodeImmutableValue
> = z.nativeEnum(CodeImmutableValue);

/** @internal */
export const ImmutableValueError$inboundSchema: z.ZodType<
  ImmutableValueError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: CodeImmutableValue$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new ImmutableValueError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError$inboundSchema:
  z.ZodType<
    GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError,
    unknown
  > = z.object({
    status_code: z.number(),
    type: NotFoundType$inboundSchema,
    code: NotFoundCode$inboundSchema,
    message: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
    .transform((v) => {
      const remapped = remap$(v, {
        "status_code": "statusCode",
      });

      return new GetV2WorkspaceMembersWorkspaceMemberIdNotFoundError(remapped, {
        request: v.request$,
        response: v.response$,
        body: v.body$,
      });
    });

/** @internal */
export const GetV2NotesNoteIdNotFoundError$inboundSchema: z.ZodType<
  GetV2NotesNoteIdNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new GetV2NotesNoteIdNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2TasksValidationTypeError$inboundSchema: z.ZodType<
  PostV2TasksValidationTypeError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: CodeValidationType$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PostV2TasksValidationTypeError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetV2TasksTaskIdNotFoundError$inboundSchema: z.ZodType<
  GetV2TasksTaskIdNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new GetV2TasksTaskIdNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PatchV2TasksTaskIdNotFoundError$inboundSchema: z.ZodType<
  PatchV2TasksTaskIdNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PatchV2TasksTaskIdNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetV2ThreadsThreadIdNotFoundError$inboundSchema: z.ZodType<
  GetV2ThreadsThreadIdNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new GetV2ThreadsThreadIdNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2CommentsInvalidRequestError$inboundSchema: z.ZodType<
  PostV2CommentsInvalidRequestError,
  unknown
> = z.object({
  statusCode: z.number(),
  type: BadRequestType$inboundSchema,
  code: BadRequestCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PostV2CommentsInvalidRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetV2CommentsCommentIdNotFoundError$inboundSchema: z.ZodType<
  GetV2CommentsCommentIdNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new GetV2CommentsCommentIdNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const DeleteV2CommentsCommentIdNotFoundError$inboundSchema: z.ZodType<
  DeleteV2CommentsCommentIdNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new DeleteV2CommentsCommentIdNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PostV2WebhooksValidationTypeError$inboundSchema: z.ZodType<
  PostV2WebhooksValidationTypeError,
  unknown
> = z.object({
  status_code: z.number(),
  type: BadRequestType$inboundSchema,
  code: CodeValidationType$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new PostV2WebhooksValidationTypeError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const GetV2WebhooksWebhookIdNotFoundError$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new GetV2WebhooksWebhookIdNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const DeleteV2WebhooksWebhookIdNotFoundError$inboundSchema: z.ZodType<
  DeleteV2WebhooksWebhookIdNotFoundError,
  unknown
> = z.object({
  status_code: z.number(),
  type: NotFoundType$inboundSchema,
  code: NotFoundCode$inboundSchema,
  message: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "status_code": "statusCode",
    });

    return new DeleteV2WebhooksWebhookIdNotFoundError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
