/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV2TasksTaskIdRequest = {
  taskId: string;
};

/**
 * Success
 */
export type DeleteV2TasksTaskIdResponse = {};

/** @internal */
export type DeleteV2TasksTaskIdRequest$Outbound = {
  task_id: string;
};

/** @internal */
export const DeleteV2TasksTaskIdRequest$outboundSchema: z.ZodType<
  DeleteV2TasksTaskIdRequest$Outbound,
  DeleteV2TasksTaskIdRequest
> = z.object({
  taskId: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
  });
});

export function deleteV2TasksTaskIdRequestToJSON(
  deleteV2TasksTaskIdRequest: DeleteV2TasksTaskIdRequest,
): string {
  return JSON.stringify(
    DeleteV2TasksTaskIdRequest$outboundSchema.parse(deleteV2TasksTaskIdRequest),
  );
}

/** @internal */
export const DeleteV2TasksTaskIdResponse$inboundSchema: z.ZodType<
  DeleteV2TasksTaskIdResponse,
  unknown
> = z.object({});

export function deleteV2TasksTaskIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV2TasksTaskIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV2TasksTaskIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV2TasksTaskIdResponse' from JSON`,
  );
}
