/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV2WebhooksWebhookIdRequest = {
  webhookId: string;
};

/**
 * Success
 */
export type DeleteV2WebhooksWebhookIdResponse = {};

/** @internal */
export type DeleteV2WebhooksWebhookIdRequest$Outbound = {
  webhook_id: string;
};

/** @internal */
export const DeleteV2WebhooksWebhookIdRequest$outboundSchema: z.ZodType<
  DeleteV2WebhooksWebhookIdRequest$Outbound,
  DeleteV2WebhooksWebhookIdRequest
> = z.object({
  webhookId: z.string(),
}).transform((v) => {
  return remap$(v, {
    webhookId: "webhook_id",
  });
});

export function deleteV2WebhooksWebhookIdRequestToJSON(
  deleteV2WebhooksWebhookIdRequest: DeleteV2WebhooksWebhookIdRequest,
): string {
  return JSON.stringify(
    DeleteV2WebhooksWebhookIdRequest$outboundSchema.parse(
      deleteV2WebhooksWebhookIdRequest,
    ),
  );
}

/** @internal */
export const DeleteV2WebhooksWebhookIdResponse$inboundSchema: z.ZodType<
  DeleteV2WebhooksWebhookIdResponse,
  unknown
> = z.object({});

export function deleteV2WebhooksWebhookIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV2WebhooksWebhookIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV2WebhooksWebhookIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV2WebhooksWebhookIdResponse' from JSON`,
  );
}
