/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV2CommentsCommentIdRequest = {
  commentId: string;
};

/**
 * Success
 */
export type DeleteV2CommentsCommentIdResponse = {};

/** @internal */
export type DeleteV2CommentsCommentIdRequest$Outbound = {
  comment_id: string;
};

/** @internal */
export const DeleteV2CommentsCommentIdRequest$outboundSchema: z.ZodType<
  DeleteV2CommentsCommentIdRequest$Outbound,
  DeleteV2CommentsCommentIdRequest
> = z.object({
  commentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    commentId: "comment_id",
  });
});

export function deleteV2CommentsCommentIdRequestToJSON(
  deleteV2CommentsCommentIdRequest: DeleteV2CommentsCommentIdRequest,
): string {
  return JSON.stringify(
    DeleteV2CommentsCommentIdRequest$outboundSchema.parse(
      deleteV2CommentsCommentIdRequest,
    ),
  );
}

/** @internal */
export const DeleteV2CommentsCommentIdResponse$inboundSchema: z.ZodType<
  DeleteV2CommentsCommentIdResponse,
  unknown
> = z.object({});

export function deleteV2CommentsCommentIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV2CommentsCommentIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV2CommentsCommentIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV2CommentsCommentIdResponse' from JSON`,
  );
}
