/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV2NotesNoteIdRequest = {
  noteId: string;
};

/**
 * Success
 */
export type DeleteV2NotesNoteIdResponse = {};

/** @internal */
export type DeleteV2NotesNoteIdRequest$Outbound = {
  note_id: string;
};

/** @internal */
export const DeleteV2NotesNoteIdRequest$outboundSchema: z.ZodType<
  DeleteV2NotesNoteIdRequest$Outbound,
  DeleteV2NotesNoteIdRequest
> = z.object({
  noteId: z.string(),
}).transform((v) => {
  return remap$(v, {
    noteId: "note_id",
  });
});

export function deleteV2NotesNoteIdRequestToJSON(
  deleteV2NotesNoteIdRequest: DeleteV2NotesNoteIdRequest,
): string {
  return JSON.stringify(
    DeleteV2NotesNoteIdRequest$outboundSchema.parse(deleteV2NotesNoteIdRequest),
  );
}

/** @internal */
export const DeleteV2NotesNoteIdResponse$inboundSchema: z.ZodType<
  DeleteV2NotesNoteIdResponse,
  unknown
> = z.object({});

export function deleteV2NotesNoteIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteV2NotesNoteIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteV2NotesNoteIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteV2NotesNoteIdResponse' from JSON`,
  );
}
