/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV2ObjectsObjectRecordsRecordIdRequest = {
  object: string;
  recordId: string;
};

/**
 * Success
 */
export type DeleteV2ObjectsObjectRecordsRecordIdResponse = {};

/** @internal */
export type DeleteV2ObjectsObjectRecordsRecordIdRequest$Outbound = {
  object: string;
  record_id: string;
};

/** @internal */
export const DeleteV2ObjectsObjectRecordsRecordIdRequest$outboundSchema:
  z.ZodType<
    DeleteV2ObjectsObjectRecordsRecordIdRequest$Outbound,
    DeleteV2ObjectsObjectRecordsRecordIdRequest
  > = z.object({
    object: z.string(),
    recordId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      recordId: "record_id",
    });
  });

export function deleteV2ObjectsObjectRecordsRecordIdRequestToJSON(
  deleteV2ObjectsObjectRecordsRecordIdRequest:
    DeleteV2ObjectsObjectRecordsRecordIdRequest,
): string {
  return JSON.stringify(
    DeleteV2ObjectsObjectRecordsRecordIdRequest$outboundSchema.parse(
      deleteV2ObjectsObjectRecordsRecordIdRequest,
    ),
  );
}

/** @internal */
export const DeleteV2ObjectsObjectRecordsRecordIdResponse$inboundSchema:
  z.ZodType<
    DeleteV2ObjectsObjectRecordsRecordIdResponse,
    unknown
  > = z.object({});

export function deleteV2ObjectsObjectRecordsRecordIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteV2ObjectsObjectRecordsRecordIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteV2ObjectsObjectRecordsRecordIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteV2ObjectsObjectRecordsRecordIdResponse' from JSON`,
  );
}
