/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteV2ListsListEntriesEntryIdRequest = {
  list: string;
  entryId: string;
};

/**
 * Success
 */
export type DeleteV2ListsListEntriesEntryIdResponse = {};

/** @internal */
export type DeleteV2ListsListEntriesEntryIdRequest$Outbound = {
  list: string;
  entry_id: string;
};

/** @internal */
export const DeleteV2ListsListEntriesEntryIdRequest$outboundSchema: z.ZodType<
  DeleteV2ListsListEntriesEntryIdRequest$Outbound,
  DeleteV2ListsListEntriesEntryIdRequest
> = z.object({
  list: z.string(),
  entryId: z.string(),
}).transform((v) => {
  return remap$(v, {
    entryId: "entry_id",
  });
});

export function deleteV2ListsListEntriesEntryIdRequestToJSON(
  deleteV2ListsListEntriesEntryIdRequest:
    DeleteV2ListsListEntriesEntryIdRequest,
): string {
  return JSON.stringify(
    DeleteV2ListsListEntriesEntryIdRequest$outboundSchema.parse(
      deleteV2ListsListEntriesEntryIdRequest,
    ),
  );
}

/** @internal */
export const DeleteV2ListsListEntriesEntryIdResponse$inboundSchema: z.ZodType<
  DeleteV2ListsListEntriesEntryIdResponse,
  unknown
> = z.object({});

export function deleteV2ListsListEntriesEntryIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  DeleteV2ListsListEntriesEntryIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      DeleteV2ListsListEntriesEntryIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'DeleteV2ListsListEntriesEntryIdResponse' from JSON`,
  );
}
