/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Attribute, Attribute$inboundSchema } from "../components/attribute.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Whether the attribute is on an object or a list.
 */
export const GetV2TargetIdentifierAttributesAttributeTarget = {
  Objects: "objects",
  Lists: "lists",
} as const;
/**
 * Whether the attribute is on an object or a list.
 */
export type GetV2TargetIdentifierAttributesAttributeTarget = ClosedEnum<
  typeof GetV2TargetIdentifierAttributesAttributeTarget
>;

export type GetV2TargetIdentifierAttributesAttributeRequest = {
  /**
   * Whether the attribute is on an object or a list.
   */
  target: GetV2TargetIdentifierAttributesAttributeTarget;
  identifier: string;
  attribute: string;
};

/**
 * Success
 */
export type GetV2TargetIdentifierAttributesAttributeResponse = {
  data: Attribute;
};

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeTarget$outboundSchema:
  z.ZodEnum<typeof GetV2TargetIdentifierAttributesAttributeTarget> = z
    .nativeEnum(GetV2TargetIdentifierAttributesAttributeTarget);

/** @internal */
export type GetV2TargetIdentifierAttributesAttributeRequest$Outbound = {
  target: string;
  identifier: string;
  attribute: string;
};

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeRequest$outboundSchema:
  z.ZodType<
    GetV2TargetIdentifierAttributesAttributeRequest$Outbound,
    GetV2TargetIdentifierAttributesAttributeRequest
  > = z.object({
    target: GetV2TargetIdentifierAttributesAttributeTarget$outboundSchema,
    identifier: z.string(),
    attribute: z.string(),
  });

export function getV2TargetIdentifierAttributesAttributeRequestToJSON(
  getV2TargetIdentifierAttributesAttributeRequest:
    GetV2TargetIdentifierAttributesAttributeRequest,
): string {
  return JSON.stringify(
    GetV2TargetIdentifierAttributesAttributeRequest$outboundSchema.parse(
      getV2TargetIdentifierAttributesAttributeRequest,
    ),
  );
}

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeResponse$inboundSchema:
  z.ZodType<
    GetV2TargetIdentifierAttributesAttributeResponse,
    unknown
  > = z.object({
    data: Attribute$inboundSchema,
  });

export function getV2TargetIdentifierAttributesAttributeResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2TargetIdentifierAttributesAttributeResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2TargetIdentifierAttributesAttributeResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV2TargetIdentifierAttributesAttributeResponse' from JSON`,
  );
}
