/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2ObjectsObjectRecordsRecordIdEntriesRequest = {
  object: string;
  recordId: string;
  limit?: number | undefined;
  offset?: number | undefined;
};

export type GetV2ObjectsObjectRecordsRecordIdEntriesData = {
  /**
   * A UUID identifying the list that this record is in.
   */
  listId: string;
  /**
   * A human-readable slug for the list for use in URLs and responses.
   */
  listApiSlug: string;
  /**
   * A UUID identifying this entry on the list.
   */
  entryId: string;
  /**
   * When this entry was created.
   */
  createdAt: string;
};

/**
 * Success
 */
export type GetV2ObjectsObjectRecordsRecordIdEntriesResponse = {
  data: Array<GetV2ObjectsObjectRecordsRecordIdEntriesData>;
};

/** @internal */
export type GetV2ObjectsObjectRecordsRecordIdEntriesRequest$Outbound = {
  object: string;
  record_id: string;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const GetV2ObjectsObjectRecordsRecordIdEntriesRequest$outboundSchema:
  z.ZodType<
    GetV2ObjectsObjectRecordsRecordIdEntriesRequest$Outbound,
    GetV2ObjectsObjectRecordsRecordIdEntriesRequest
  > = z.object({
    object: z.string(),
    recordId: z.string(),
    limit: z.number().int().optional(),
    offset: z.number().int().optional(),
  }).transform((v) => {
    return remap$(v, {
      recordId: "record_id",
    });
  });

export function getV2ObjectsObjectRecordsRecordIdEntriesRequestToJSON(
  getV2ObjectsObjectRecordsRecordIdEntriesRequest:
    GetV2ObjectsObjectRecordsRecordIdEntriesRequest,
): string {
  return JSON.stringify(
    GetV2ObjectsObjectRecordsRecordIdEntriesRequest$outboundSchema.parse(
      getV2ObjectsObjectRecordsRecordIdEntriesRequest,
    ),
  );
}

/** @internal */
export const GetV2ObjectsObjectRecordsRecordIdEntriesData$inboundSchema:
  z.ZodType<
    GetV2ObjectsObjectRecordsRecordIdEntriesData,
    unknown
  > = z.object({
    list_id: z.string(),
    list_api_slug: z.string(),
    entry_id: z.string(),
    created_at: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "list_id": "listId",
      "list_api_slug": "listApiSlug",
      "entry_id": "entryId",
      "created_at": "createdAt",
    });
  });

export function getV2ObjectsObjectRecordsRecordIdEntriesDataFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2ObjectsObjectRecordsRecordIdEntriesData,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2ObjectsObjectRecordsRecordIdEntriesData$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV2ObjectsObjectRecordsRecordIdEntriesData' from JSON`,
  );
}

/** @internal */
export const GetV2ObjectsObjectRecordsRecordIdEntriesResponse$inboundSchema:
  z.ZodType<
    GetV2ObjectsObjectRecordsRecordIdEntriesResponse,
    unknown
  > = z.object({
    data: z.array(
      z.lazy(() => GetV2ObjectsObjectRecordsRecordIdEntriesData$inboundSchema),
    ),
  });

export function getV2ObjectsObjectRecordsRecordIdEntriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2ObjectsObjectRecordsRecordIdEntriesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2ObjectsObjectRecordsRecordIdEntriesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV2ObjectsObjectRecordsRecordIdEntriesResponse' from JSON`,
  );
}
