/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Attribute, Attribute$inboundSchema } from "../components/attribute.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Whether the attributes are on an object or a list.
 */
export const GetV2TargetIdentifierAttributesTarget = {
  Objects: "objects",
  Lists: "lists",
} as const;
/**
 * Whether the attributes are on an object or a list.
 */
export type GetV2TargetIdentifierAttributesTarget = ClosedEnum<
  typeof GetV2TargetIdentifierAttributesTarget
>;

export type GetV2TargetIdentifierAttributesRequest = {
  /**
   * Whether the attributes are on an object or a list.
   */
  target: GetV2TargetIdentifierAttributesTarget;
  identifier: string;
  limit?: number | undefined;
  offset?: number | undefined;
  showArchived?: boolean | undefined;
};

/**
 * Success
 */
export type GetV2TargetIdentifierAttributesResponse = {
  data: Array<Attribute>;
};

/** @internal */
export const GetV2TargetIdentifierAttributesTarget$outboundSchema:
  z.ZodEnum<typeof GetV2TargetIdentifierAttributesTarget> = z.nativeEnum(
    GetV2TargetIdentifierAttributesTarget,
  );

/** @internal */
export type GetV2TargetIdentifierAttributesRequest$Outbound = {
  target: string;
  identifier: string;
  limit?: number | undefined;
  offset?: number | undefined;
  show_archived?: boolean | undefined;
};

/** @internal */
export const GetV2TargetIdentifierAttributesRequest$outboundSchema: z.ZodType<
  GetV2TargetIdentifierAttributesRequest$Outbound,
  GetV2TargetIdentifierAttributesRequest
> = z.object({
  target: GetV2TargetIdentifierAttributesTarget$outboundSchema,
  identifier: z.string(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  showArchived: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    showArchived: "show_archived",
  });
});

export function getV2TargetIdentifierAttributesRequestToJSON(
  getV2TargetIdentifierAttributesRequest:
    GetV2TargetIdentifierAttributesRequest,
): string {
  return JSON.stringify(
    GetV2TargetIdentifierAttributesRequest$outboundSchema.parse(
      getV2TargetIdentifierAttributesRequest,
    ),
  );
}

/** @internal */
export const GetV2TargetIdentifierAttributesResponse$inboundSchema: z.ZodType<
  GetV2TargetIdentifierAttributesResponse,
  unknown
> = z.object({
  data: z.array(Attribute$inboundSchema),
});

export function getV2TargetIdentifierAttributesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2TargetIdentifierAttributesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2TargetIdentifierAttributesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV2TargetIdentifierAttributesResponse' from JSON`,
  );
}
