/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2WebhooksRequest = {
  limit?: number | undefined;
  offset?: number | undefined;
};

/**
 * Type of event the webhook is subscribed to.
 */
export const GetV2WebhooksEventType = {
  CommentCreated: "comment.created",
  CommentResolved: "comment.resolved",
  CommentUnresolved: "comment.unresolved",
  CommentDeleted: "comment.deleted",
  ListCreated: "list.created",
  ListUpdated: "list.updated",
  ListDeleted: "list.deleted",
  ListAttributeCreated: "list-attribute.created",
  ListAttributeUpdated: "list-attribute.updated",
  ListEntryCreated: "list-entry.created",
  ListEntryUpdated: "list-entry.updated",
  ListEntryDeleted: "list-entry.deleted",
  ObjectAttributeCreated: "object-attribute.created",
  ObjectAttributeUpdated: "object-attribute.updated",
  NoteCreated: "note.created",
  NoteUpdated: "note.updated",
  NoteDeleted: "note.deleted",
  RecordCreated: "record.created",
  RecordMerged: "record.merged",
  RecordUpdated: "record.updated",
  RecordDeleted: "record.deleted",
  TaskCreated: "task.created",
  TaskUpdated: "task.updated",
  TaskDeleted: "task.deleted",
  WorkspaceMemberCreated: "workspace-member.created",
} as const;
/**
 * Type of event the webhook is subscribed to.
 */
export type GetV2WebhooksEventType = ClosedEnum<typeof GetV2WebhooksEventType>;

export type GetV2WebhooksDollarAndNotEquals = {
  field: string;
  operator: "not_equals";
  value: string;
};

export type GetV2WebhooksDollarAndEquals = {
  field: string;
  operator: "equals";
  value: string;
};

export type GetV2WebhooksDollarAndUnion =
  | GetV2WebhooksDollarAndEquals
  | GetV2WebhooksDollarAndNotEquals;

export type GetV2WebhooksFilter2 = {
  dollarAnd: Array<
    GetV2WebhooksDollarAndEquals | GetV2WebhooksDollarAndNotEquals
  >;
};

export type GetV2WebhooksDollarOrNotEquals = {
  field: string;
  operator: "not_equals";
  value: string;
};

export type GetV2WebhooksDollarOrEquals = {
  field: string;
  operator: "equals";
  value: string;
};

export type GetV2WebhooksDollarOrUnion =
  | GetV2WebhooksDollarOrEquals
  | GetV2WebhooksDollarOrNotEquals;

export type GetV2WebhooksFilter1 = {
  dollarOr: Array<GetV2WebhooksDollarOrEquals | GetV2WebhooksDollarOrNotEquals>;
};

/**
 * Filters to determine whether the webhook event should be sent. If null, the filter always passes.
 */
export type GetV2WebhooksFilterUnion =
  | GetV2WebhooksFilter1
  | GetV2WebhooksFilter2;

export type GetV2WebhooksSubscription = {
  /**
   * Type of event the webhook is subscribed to.
   */
  eventType: GetV2WebhooksEventType;
  /**
   * Filters to determine whether the webhook event should be sent. If null, the filter always passes.
   */
  filter: GetV2WebhooksFilter1 | GetV2WebhooksFilter2 | null;
};

export type GetV2WebhooksId = {
  /**
   * The ID of the workspace the webhook belongs to.
   */
  workspaceId: string;
  /**
   * The ID of the webhook.
   */
  webhookId: string;
};

/**
 * The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
 */
export const GetV2WebhooksStatus = {
  Active: "active",
  Degraded: "degraded",
  Inactive: "inactive",
} as const;
/**
 * The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
 */
export type GetV2WebhooksStatus = ClosedEnum<typeof GetV2WebhooksStatus>;

export type GetV2WebhooksData = {
  /**
   * URL where the webhook events will be delivered to.
   */
  targetUrl: string;
  /**
   * One or more events the webhook is subscribed to.
   */
  subscriptions: Array<GetV2WebhooksSubscription>;
  id: GetV2WebhooksId;
  /**
   * The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
   */
  status: GetV2WebhooksStatus;
  /**
   * When the webhook was created.
   */
  createdAt: string;
};

/**
 * Success
 */
export type GetV2WebhooksResponse = {
  data: Array<GetV2WebhooksData>;
};

/** @internal */
export type GetV2WebhooksRequest$Outbound = {
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const GetV2WebhooksRequest$outboundSchema: z.ZodType<
  GetV2WebhooksRequest$Outbound,
  GetV2WebhooksRequest
> = z.object({
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
});

export function getV2WebhooksRequestToJSON(
  getV2WebhooksRequest: GetV2WebhooksRequest,
): string {
  return JSON.stringify(
    GetV2WebhooksRequest$outboundSchema.parse(getV2WebhooksRequest),
  );
}

/** @internal */
export const GetV2WebhooksEventType$inboundSchema: z.ZodEnum<
  typeof GetV2WebhooksEventType
> = z.nativeEnum(GetV2WebhooksEventType);

/** @internal */
export const GetV2WebhooksDollarAndNotEquals$inboundSchema: z.ZodType<
  GetV2WebhooksDollarAndNotEquals,
  unknown
> = z.object({
  field: z.string(),
  operator: z.literal("not_equals"),
  value: z.string(),
});

export function getV2WebhooksDollarAndNotEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksDollarAndNotEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksDollarAndNotEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksDollarAndNotEquals' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksDollarAndEquals$inboundSchema: z.ZodType<
  GetV2WebhooksDollarAndEquals,
  unknown
> = z.object({
  field: z.string(),
  operator: z.literal("equals"),
  value: z.string(),
});

export function getV2WebhooksDollarAndEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksDollarAndEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksDollarAndEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksDollarAndEquals' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksDollarAndUnion$inboundSchema: z.ZodType<
  GetV2WebhooksDollarAndUnion,
  unknown
> = z.union([
  z.lazy(() => GetV2WebhooksDollarAndEquals$inboundSchema),
  z.lazy(() => GetV2WebhooksDollarAndNotEquals$inboundSchema),
]);

export function getV2WebhooksDollarAndUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksDollarAndUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksDollarAndUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksDollarAndUnion' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksFilter2$inboundSchema: z.ZodType<
  GetV2WebhooksFilter2,
  unknown
> = z.object({
  $and: z.array(
    z.union([
      z.lazy(() => GetV2WebhooksDollarAndEquals$inboundSchema),
      z.lazy(() => GetV2WebhooksDollarAndNotEquals$inboundSchema),
    ]),
  ),
}).transform((v) => {
  return remap$(v, {
    "$and": "dollarAnd",
  });
});

export function getV2WebhooksFilter2FromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksFilter2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksFilter2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksFilter2' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksDollarOrNotEquals$inboundSchema: z.ZodType<
  GetV2WebhooksDollarOrNotEquals,
  unknown
> = z.object({
  field: z.string(),
  operator: z.literal("not_equals"),
  value: z.string(),
});

export function getV2WebhooksDollarOrNotEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksDollarOrNotEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksDollarOrNotEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksDollarOrNotEquals' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksDollarOrEquals$inboundSchema: z.ZodType<
  GetV2WebhooksDollarOrEquals,
  unknown
> = z.object({
  field: z.string(),
  operator: z.literal("equals"),
  value: z.string(),
});

export function getV2WebhooksDollarOrEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksDollarOrEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksDollarOrEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksDollarOrEquals' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksDollarOrUnion$inboundSchema: z.ZodType<
  GetV2WebhooksDollarOrUnion,
  unknown
> = z.union([
  z.lazy(() => GetV2WebhooksDollarOrEquals$inboundSchema),
  z.lazy(() => GetV2WebhooksDollarOrNotEquals$inboundSchema),
]);

export function getV2WebhooksDollarOrUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksDollarOrUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksDollarOrUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksDollarOrUnion' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksFilter1$inboundSchema: z.ZodType<
  GetV2WebhooksFilter1,
  unknown
> = z.object({
  $or: z.array(
    z.union([
      z.lazy(() => GetV2WebhooksDollarOrEquals$inboundSchema),
      z.lazy(() => GetV2WebhooksDollarOrNotEquals$inboundSchema),
    ]),
  ),
}).transform((v) => {
  return remap$(v, {
    "$or": "dollarOr",
  });
});

export function getV2WebhooksFilter1FromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksFilter1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksFilter1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksFilter1' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksFilterUnion$inboundSchema: z.ZodType<
  GetV2WebhooksFilterUnion,
  unknown
> = z.union([
  z.lazy(() => GetV2WebhooksFilter1$inboundSchema),
  z.lazy(() => GetV2WebhooksFilter2$inboundSchema),
]);

export function getV2WebhooksFilterUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksFilterUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksFilterUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksFilterUnion' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksSubscription$inboundSchema: z.ZodType<
  GetV2WebhooksSubscription,
  unknown
> = z.object({
  event_type: GetV2WebhooksEventType$inboundSchema,
  filter: z.nullable(
    z.union([
      z.lazy(() => GetV2WebhooksFilter1$inboundSchema),
      z.lazy(() => GetV2WebhooksFilter2$inboundSchema),
    ]),
  ),
}).transform((v) => {
  return remap$(v, {
    "event_type": "eventType",
  });
});

export function getV2WebhooksSubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksSubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksSubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksSubscription' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksId$inboundSchema: z.ZodType<
  GetV2WebhooksId,
  unknown
> = z.object({
  workspace_id: z.string(),
  webhook_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "webhook_id": "webhookId",
  });
});

export function getV2WebhooksIdFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksId' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksStatus$inboundSchema: z.ZodEnum<
  typeof GetV2WebhooksStatus
> = z.nativeEnum(GetV2WebhooksStatus);

/** @internal */
export const GetV2WebhooksData$inboundSchema: z.ZodType<
  GetV2WebhooksData,
  unknown
> = z.object({
  target_url: z.string(),
  subscriptions: z.array(z.lazy(() => GetV2WebhooksSubscription$inboundSchema)),
  id: z.lazy(() => GetV2WebhooksId$inboundSchema),
  status: GetV2WebhooksStatus$inboundSchema,
  created_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "target_url": "targetUrl",
    "created_at": "createdAt",
  });
});

export function getV2WebhooksDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksData' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksResponse$inboundSchema: z.ZodType<
  GetV2WebhooksResponse,
  unknown
> = z.object({
  data: z.array(z.lazy(() => GetV2WebhooksData$inboundSchema)),
});

export function getV2WebhooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksResponse' from JSON`,
  );
}
