/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Thread, Thread$inboundSchema } from "../components/thread.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2ThreadsRequest = {
  recordId?: string | undefined;
  object?: string | undefined;
  entryId?: string | undefined;
  list?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/**
 * Success
 */
export type GetV2ThreadsResponse = {
  data: Array<Thread>;
};

/** @internal */
export type GetV2ThreadsRequest$Outbound = {
  record_id?: string | undefined;
  object?: string | undefined;
  entry_id?: string | undefined;
  list?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const GetV2ThreadsRequest$outboundSchema: z.ZodType<
  GetV2ThreadsRequest$Outbound,
  GetV2ThreadsRequest
> = z.object({
  recordId: z.string().optional(),
  object: z.string().optional(),
  entryId: z.string().optional(),
  list: z.string().optional(),
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
}).transform((v) => {
  return remap$(v, {
    recordId: "record_id",
    entryId: "entry_id",
  });
});

export function getV2ThreadsRequestToJSON(
  getV2ThreadsRequest: GetV2ThreadsRequest,
): string {
  return JSON.stringify(
    GetV2ThreadsRequest$outboundSchema.parse(getV2ThreadsRequest),
  );
}

/** @internal */
export const GetV2ThreadsResponse$inboundSchema: z.ZodType<
  GetV2ThreadsResponse,
  unknown
> = z.object({
  data: z.array(Thread$inboundSchema),
});

export function getV2ThreadsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ThreadsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ThreadsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ThreadsResponse' from JSON`,
  );
}
