/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Status, Status$inboundSchema } from "../components/status.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Whether the attribute is on an object or a list. Please note that the company and people objects do not support status attributes at this time.
 */
export const GetV2TargetIdentifierAttributesAttributeStatusesTarget = {
  Lists: "lists",
  Objects: "objects",
} as const;
/**
 * Whether the attribute is on an object or a list. Please note that the company and people objects do not support status attributes at this time.
 */
export type GetV2TargetIdentifierAttributesAttributeStatusesTarget = ClosedEnum<
  typeof GetV2TargetIdentifierAttributesAttributeStatusesTarget
>;

export type GetV2TargetIdentifierAttributesAttributeStatusesRequest = {
  /**
   * Whether the attribute is on an object or a list. Please note that the company and people objects do not support status attributes at this time.
   */
  target: GetV2TargetIdentifierAttributesAttributeStatusesTarget;
  identifier: string;
  attribute: string;
  showArchived?: boolean | undefined;
};

/**
 * Success
 */
export type GetV2TargetIdentifierAttributesAttributeStatusesResponse = {
  data: Array<Status>;
};

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeStatusesTarget$outboundSchema:
  z.ZodEnum<
    typeof GetV2TargetIdentifierAttributesAttributeStatusesTarget
  > = z.nativeEnum(GetV2TargetIdentifierAttributesAttributeStatusesTarget);

/** @internal */
export type GetV2TargetIdentifierAttributesAttributeStatusesRequest$Outbound = {
  target: string;
  identifier: string;
  attribute: string;
  show_archived: boolean;
};

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeStatusesRequest$outboundSchema:
  z.ZodType<
    GetV2TargetIdentifierAttributesAttributeStatusesRequest$Outbound,
    GetV2TargetIdentifierAttributesAttributeStatusesRequest
  > = z.object({
    target:
      GetV2TargetIdentifierAttributesAttributeStatusesTarget$outboundSchema,
    identifier: z.string(),
    attribute: z.string(),
    showArchived: z.boolean().default(false),
  }).transform((v) => {
    return remap$(v, {
      showArchived: "show_archived",
    });
  });

export function getV2TargetIdentifierAttributesAttributeStatusesRequestToJSON(
  getV2TargetIdentifierAttributesAttributeStatusesRequest:
    GetV2TargetIdentifierAttributesAttributeStatusesRequest,
): string {
  return JSON.stringify(
    GetV2TargetIdentifierAttributesAttributeStatusesRequest$outboundSchema
      .parse(getV2TargetIdentifierAttributesAttributeStatusesRequest),
  );
}

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeStatusesResponse$inboundSchema:
  z.ZodType<
    GetV2TargetIdentifierAttributesAttributeStatusesResponse,
    unknown
  > = z.object({
    data: z.array(Status$inboundSchema),
  });

export function getV2TargetIdentifierAttributesAttributeStatusesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2TargetIdentifierAttributesAttributeStatusesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2TargetIdentifierAttributesAttributeStatusesResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetV2TargetIdentifierAttributesAttributeStatusesResponse' from JSON`,
  );
}
