/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Comment, Comment$inboundSchema } from "../components/comment.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2CommentsCommentIdRequest = {
  commentId: string;
};

/**
 * Success
 */
export type GetV2CommentsCommentIdResponse = {
  data: Comment;
};

/** @internal */
export type GetV2CommentsCommentIdRequest$Outbound = {
  comment_id: string;
};

/** @internal */
export const GetV2CommentsCommentIdRequest$outboundSchema: z.ZodType<
  GetV2CommentsCommentIdRequest$Outbound,
  GetV2CommentsCommentIdRequest
> = z.object({
  commentId: z.string(),
}).transform((v) => {
  return remap$(v, {
    commentId: "comment_id",
  });
});

export function getV2CommentsCommentIdRequestToJSON(
  getV2CommentsCommentIdRequest: GetV2CommentsCommentIdRequest,
): string {
  return JSON.stringify(
    GetV2CommentsCommentIdRequest$outboundSchema.parse(
      getV2CommentsCommentIdRequest,
    ),
  );
}

/** @internal */
export const GetV2CommentsCommentIdResponse$inboundSchema: z.ZodType<
  GetV2CommentsCommentIdResponse,
  unknown
> = z.object({
  data: Comment$inboundSchema,
});

export function getV2CommentsCommentIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2CommentsCommentIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2CommentsCommentIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2CommentsCommentIdResponse' from JSON`,
  );
}
