/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Note, Note$inboundSchema } from "../components/note.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2NotesRequest = {
  limit?: number | undefined;
  offset?: number | undefined;
  parentObject?: string | undefined;
  parentRecordId?: string | undefined;
};

/**
 * Success
 */
export type GetV2NotesResponse = {
  data: Array<Note>;
};

/** @internal */
export type GetV2NotesRequest$Outbound = {
  limit?: number | undefined;
  offset?: number | undefined;
  parent_object?: string | undefined;
  parent_record_id?: string | undefined;
};

/** @internal */
export const GetV2NotesRequest$outboundSchema: z.ZodType<
  GetV2NotesRequest$Outbound,
  GetV2NotesRequest
> = z.object({
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  parentObject: z.string().optional(),
  parentRecordId: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    parentObject: "parent_object",
    parentRecordId: "parent_record_id",
  });
});

export function getV2NotesRequestToJSON(
  getV2NotesRequest: GetV2NotesRequest,
): string {
  return JSON.stringify(
    GetV2NotesRequest$outboundSchema.parse(getV2NotesRequest),
  );
}

/** @internal */
export const GetV2NotesResponse$inboundSchema: z.ZodType<
  GetV2NotesResponse,
  unknown
> = z.object({
  data: z.array(Note$inboundSchema),
});

export function getV2NotesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2NotesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2NotesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2NotesResponse' from JSON`,
  );
}
