/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Thread, Thread$inboundSchema } from "../components/thread.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2ThreadsThreadIdRequest = {
  threadId: string;
};

/**
 * Success
 */
export type GetV2ThreadsThreadIdResponse = {
  data: Thread;
};

/** @internal */
export type GetV2ThreadsThreadIdRequest$Outbound = {
  thread_id: string;
};

/** @internal */
export const GetV2ThreadsThreadIdRequest$outboundSchema: z.ZodType<
  GetV2ThreadsThreadIdRequest$Outbound,
  GetV2ThreadsThreadIdRequest
> = z.object({
  threadId: z.string(),
}).transform((v) => {
  return remap$(v, {
    threadId: "thread_id",
  });
});

export function getV2ThreadsThreadIdRequestToJSON(
  getV2ThreadsThreadIdRequest: GetV2ThreadsThreadIdRequest,
): string {
  return JSON.stringify(
    GetV2ThreadsThreadIdRequest$outboundSchema.parse(
      getV2ThreadsThreadIdRequest,
    ),
  );
}

/** @internal */
export const GetV2ThreadsThreadIdResponse$inboundSchema: z.ZodType<
  GetV2ThreadsThreadIdResponse,
  unknown
> = z.object({
  data: Thread$inboundSchema,
});

export function getV2ThreadsThreadIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ThreadsThreadIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ThreadsThreadIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ThreadsThreadIdResponse' from JSON`,
  );
}
