/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { ObjectT, ObjectT$inboundSchema } from "../components/object.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2ObjectsObjectRequest = {
  object: string;
};

/**
 * Success
 */
export type GetV2ObjectsObjectResponse = {
  data: ObjectT;
};

/** @internal */
export type GetV2ObjectsObjectRequest$Outbound = {
  object: string;
};

/** @internal */
export const GetV2ObjectsObjectRequest$outboundSchema: z.ZodType<
  GetV2ObjectsObjectRequest$Outbound,
  GetV2ObjectsObjectRequest
> = z.object({
  object: z.string(),
});

export function getV2ObjectsObjectRequestToJSON(
  getV2ObjectsObjectRequest: GetV2ObjectsObjectRequest,
): string {
  return JSON.stringify(
    GetV2ObjectsObjectRequest$outboundSchema.parse(getV2ObjectsObjectRequest),
  );
}

/** @internal */
export const GetV2ObjectsObjectResponse$inboundSchema: z.ZodType<
  GetV2ObjectsObjectResponse,
  unknown
> = z.object({
  data: ObjectT$inboundSchema,
});

export function getV2ObjectsObjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ObjectsObjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ObjectsObjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ObjectsObjectResponse' from JSON`,
  );
}
