/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Task, Task$inboundSchema } from "../components/task.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Optionally sort the results. "created_at:asc" returns oldest results first, "created_at:desc" returns the newest results first. If unspecified, defaults to "created_at:asc" (oldest results first).
 */
export const GetV2TasksSort = {
  CreatedAtAsc: "created_at:asc",
  CreatedAtDesc: "created_at:desc",
} as const;
/**
 * Optionally sort the results. "created_at:asc" returns oldest results first, "created_at:desc" returns the newest results first. If unspecified, defaults to "created_at:asc" (oldest results first).
 */
export type GetV2TasksSort = ClosedEnum<typeof GetV2TasksSort>;

export type GetV2TasksRequest = {
  limit?: number | undefined;
  offset?: number | undefined;
  /**
   * Optionally sort the results. "created_at:asc" returns oldest results first, "created_at:desc" returns the newest results first. If unspecified, defaults to "created_at:asc" (oldest results first).
   */
  sort?: GetV2TasksSort | undefined;
  linkedObject?: string | undefined;
  linkedRecordId?: string | undefined;
  assignee?: string | null | undefined;
  isCompleted?: boolean | undefined;
};

/**
 * Success
 */
export type GetV2TasksResponse = {
  data: Array<Task>;
};

/** @internal */
export const GetV2TasksSort$outboundSchema: z.ZodEnum<
  typeof GetV2TasksSort
> = z.nativeEnum(GetV2TasksSort);

/** @internal */
export type GetV2TasksRequest$Outbound = {
  limit?: number | undefined;
  offset?: number | undefined;
  sort?: string | undefined;
  linked_object?: string | undefined;
  linked_record_id?: string | undefined;
  assignee?: string | null | undefined;
  is_completed?: boolean | undefined;
};

/** @internal */
export const GetV2TasksRequest$outboundSchema: z.ZodType<
  GetV2TasksRequest$Outbound,
  GetV2TasksRequest
> = z.object({
  limit: z.number().int().optional(),
  offset: z.number().int().optional(),
  sort: GetV2TasksSort$outboundSchema.optional(),
  linkedObject: z.string().optional(),
  linkedRecordId: z.string().optional(),
  assignee: z.nullable(z.string()).optional(),
  isCompleted: z.boolean().optional(),
}).transform((v) => {
  return remap$(v, {
    linkedObject: "linked_object",
    linkedRecordId: "linked_record_id",
    isCompleted: "is_completed",
  });
});

export function getV2TasksRequestToJSON(
  getV2TasksRequest: GetV2TasksRequest,
): string {
  return JSON.stringify(
    GetV2TasksRequest$outboundSchema.parse(getV2TasksRequest),
  );
}

/** @internal */
export const GetV2TasksResponse$inboundSchema: z.ZodType<
  GetV2TasksResponse,
  unknown
> = z.object({
  data: z.array(Task$inboundSchema),
});

export function getV2TasksResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2TasksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2TasksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2TasksResponse' from JSON`,
  );
}
