/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  WorkspaceMember,
  WorkspaceMember$inboundSchema,
} from "../components/workspacemember.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Success
 */
export type GetV2WorkspaceMembersResponse = {
  data: Array<WorkspaceMember>;
};

/** @internal */
export const GetV2WorkspaceMembersResponse$inboundSchema: z.ZodType<
  GetV2WorkspaceMembersResponse,
  unknown
> = z.object({
  data: z.array(WorkspaceMember$inboundSchema),
});

export function getV2WorkspaceMembersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WorkspaceMembersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WorkspaceMembersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WorkspaceMembersResponse' from JSON`,
  );
}
