/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2ObjectsObjectRecordsRecordIdRequest = {
  object: string;
  recordId: string;
};

export type GetV2ObjectsObjectRecordsRecordIdId = {
  /**
   * A UUID identifying the workspace this record belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the object this record belongs to.
   */
  objectId: string;
  /**
   * A UUID identifying this record.
   */
  recordId: string;
};

export type GetV2ObjectsObjectRecordsRecordIdData = {
  id: GetV2ObjectsObjectRecordsRecordIdId;
  /**
   * When this record was created.
   */
  createdAt: string;
  /**
   * A record type with an attribute `api_slug` as the key, and an array of value objects as the values.
   */
  values: { [k: string]: any };
};

/**
 * Success
 */
export type GetV2ObjectsObjectRecordsRecordIdResponse = {
  data: GetV2ObjectsObjectRecordsRecordIdData;
};

/** @internal */
export type GetV2ObjectsObjectRecordsRecordIdRequest$Outbound = {
  object: string;
  record_id: string;
};

/** @internal */
export const GetV2ObjectsObjectRecordsRecordIdRequest$outboundSchema: z.ZodType<
  GetV2ObjectsObjectRecordsRecordIdRequest$Outbound,
  GetV2ObjectsObjectRecordsRecordIdRequest
> = z.object({
  object: z.string(),
  recordId: z.string(),
}).transform((v) => {
  return remap$(v, {
    recordId: "record_id",
  });
});

export function getV2ObjectsObjectRecordsRecordIdRequestToJSON(
  getV2ObjectsObjectRecordsRecordIdRequest:
    GetV2ObjectsObjectRecordsRecordIdRequest,
): string {
  return JSON.stringify(
    GetV2ObjectsObjectRecordsRecordIdRequest$outboundSchema.parse(
      getV2ObjectsObjectRecordsRecordIdRequest,
    ),
  );
}

/** @internal */
export const GetV2ObjectsObjectRecordsRecordIdId$inboundSchema: z.ZodType<
  GetV2ObjectsObjectRecordsRecordIdId,
  unknown
> = z.object({
  workspace_id: z.string(),
  object_id: z.string(),
  record_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "object_id": "objectId",
    "record_id": "recordId",
  });
});

export function getV2ObjectsObjectRecordsRecordIdIdFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ObjectsObjectRecordsRecordIdId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2ObjectsObjectRecordsRecordIdId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ObjectsObjectRecordsRecordIdId' from JSON`,
  );
}

/** @internal */
export const GetV2ObjectsObjectRecordsRecordIdData$inboundSchema: z.ZodType<
  GetV2ObjectsObjectRecordsRecordIdData,
  unknown
> = z.object({
  id: z.lazy(() => GetV2ObjectsObjectRecordsRecordIdId$inboundSchema),
  created_at: z.string(),
  values: z.record(z.string(), z.any()),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});

export function getV2ObjectsObjectRecordsRecordIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ObjectsObjectRecordsRecordIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2ObjectsObjectRecordsRecordIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ObjectsObjectRecordsRecordIdData' from JSON`,
  );
}

/** @internal */
export const GetV2ObjectsObjectRecordsRecordIdResponse$inboundSchema: z.ZodType<
  GetV2ObjectsObjectRecordsRecordIdResponse,
  unknown
> = z.object({
  data: z.lazy(() => GetV2ObjectsObjectRecordsRecordIdData$inboundSchema),
});

export function getV2ObjectsObjectRecordsRecordIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2ObjectsObjectRecordsRecordIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2ObjectsObjectRecordsRecordIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV2ObjectsObjectRecordsRecordIdResponse' from JSON`,
  );
}
