/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2WebhooksWebhookIdRequest = {
  webhookId: string;
};

/**
 * Type of event the webhook is subscribed to.
 */
export const GetV2WebhooksWebhookIdEventType = {
  CommentCreated: "comment.created",
  CommentResolved: "comment.resolved",
  CommentUnresolved: "comment.unresolved",
  CommentDeleted: "comment.deleted",
  ListCreated: "list.created",
  ListUpdated: "list.updated",
  ListDeleted: "list.deleted",
  ListAttributeCreated: "list-attribute.created",
  ListAttributeUpdated: "list-attribute.updated",
  ListEntryCreated: "list-entry.created",
  ListEntryUpdated: "list-entry.updated",
  ListEntryDeleted: "list-entry.deleted",
  ObjectAttributeCreated: "object-attribute.created",
  ObjectAttributeUpdated: "object-attribute.updated",
  NoteCreated: "note.created",
  NoteUpdated: "note.updated",
  NoteDeleted: "note.deleted",
  RecordCreated: "record.created",
  RecordMerged: "record.merged",
  RecordUpdated: "record.updated",
  RecordDeleted: "record.deleted",
  TaskCreated: "task.created",
  TaskUpdated: "task.updated",
  TaskDeleted: "task.deleted",
  WorkspaceMemberCreated: "workspace-member.created",
} as const;
/**
 * Type of event the webhook is subscribed to.
 */
export type GetV2WebhooksWebhookIdEventType = ClosedEnum<
  typeof GetV2WebhooksWebhookIdEventType
>;

export type GetV2WebhooksWebhookIdDollarAndNotEquals = {
  field: string;
  operator: "not_equals";
  value: string;
};

export type GetV2WebhooksWebhookIdDollarAndEquals = {
  field: string;
  operator: "equals";
  value: string;
};

export type GetV2WebhooksWebhookIdDollarAndUnion =
  | GetV2WebhooksWebhookIdDollarAndEquals
  | GetV2WebhooksWebhookIdDollarAndNotEquals;

export type GetV2WebhooksWebhookIdFilter2 = {
  dollarAnd: Array<
    | GetV2WebhooksWebhookIdDollarAndEquals
    | GetV2WebhooksWebhookIdDollarAndNotEquals
  >;
};

export type GetV2WebhooksWebhookIdDollarOrNotEquals = {
  field: string;
  operator: "not_equals";
  value: string;
};

export type GetV2WebhooksWebhookIdDollarOrEquals = {
  field: string;
  operator: "equals";
  value: string;
};

export type GetV2WebhooksWebhookIdDollarOrUnion =
  | GetV2WebhooksWebhookIdDollarOrEquals
  | GetV2WebhooksWebhookIdDollarOrNotEquals;

export type GetV2WebhooksWebhookIdFilter1 = {
  dollarOr: Array<
    | GetV2WebhooksWebhookIdDollarOrEquals
    | GetV2WebhooksWebhookIdDollarOrNotEquals
  >;
};

/**
 * Filters to determine whether the webhook event should be sent. If null, the filter always passes.
 */
export type GetV2WebhooksWebhookIdFilterUnion =
  | GetV2WebhooksWebhookIdFilter1
  | GetV2WebhooksWebhookIdFilter2;

export type GetV2WebhooksWebhookIdSubscription = {
  /**
   * Type of event the webhook is subscribed to.
   */
  eventType: GetV2WebhooksWebhookIdEventType;
  /**
   * Filters to determine whether the webhook event should be sent. If null, the filter always passes.
   */
  filter: GetV2WebhooksWebhookIdFilter1 | GetV2WebhooksWebhookIdFilter2 | null;
};

export type GetV2WebhooksWebhookIdId = {
  /**
   * The ID of the workspace the webhook belongs to.
   */
  workspaceId: string;
  /**
   * The ID of the webhook.
   */
  webhookId: string;
};

/**
 * The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
 */
export const GetV2WebhooksWebhookIdStatus = {
  Active: "active",
  Degraded: "degraded",
  Inactive: "inactive",
} as const;
/**
 * The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
 */
export type GetV2WebhooksWebhookIdStatus = ClosedEnum<
  typeof GetV2WebhooksWebhookIdStatus
>;

export type GetV2WebhooksWebhookIdData = {
  /**
   * URL where the webhook events will be delivered to.
   */
  targetUrl: string;
  /**
   * One or more events the webhook is subscribed to.
   */
  subscriptions: Array<GetV2WebhooksWebhookIdSubscription>;
  id: GetV2WebhooksWebhookIdId;
  /**
   * The state of the webhook. Webhooks marked as active and degraded will receive events, inactive ones will not. If a webhook remains in the degraded state for 7 days, it will be marked inactive.
   */
  status: GetV2WebhooksWebhookIdStatus;
  /**
   * When the webhook was created.
   */
  createdAt: string;
};

/**
 * Success
 */
export type GetV2WebhooksWebhookIdResponse = {
  data: GetV2WebhooksWebhookIdData;
};

/** @internal */
export type GetV2WebhooksWebhookIdRequest$Outbound = {
  webhook_id: string;
};

/** @internal */
export const GetV2WebhooksWebhookIdRequest$outboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdRequest$Outbound,
  GetV2WebhooksWebhookIdRequest
> = z.object({
  webhookId: z.string(),
}).transform((v) => {
  return remap$(v, {
    webhookId: "webhook_id",
  });
});

export function getV2WebhooksWebhookIdRequestToJSON(
  getV2WebhooksWebhookIdRequest: GetV2WebhooksWebhookIdRequest,
): string {
  return JSON.stringify(
    GetV2WebhooksWebhookIdRequest$outboundSchema.parse(
      getV2WebhooksWebhookIdRequest,
    ),
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdEventType$inboundSchema: z.ZodEnum<
  typeof GetV2WebhooksWebhookIdEventType
> = z.nativeEnum(GetV2WebhooksWebhookIdEventType);

/** @internal */
export const GetV2WebhooksWebhookIdDollarAndNotEquals$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdDollarAndNotEquals,
  unknown
> = z.object({
  field: z.string(),
  operator: z.literal("not_equals"),
  value: z.string(),
});

export function getV2WebhooksWebhookIdDollarAndNotEqualsFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2WebhooksWebhookIdDollarAndNotEquals,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2WebhooksWebhookIdDollarAndNotEquals$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV2WebhooksWebhookIdDollarAndNotEquals' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdDollarAndEquals$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdDollarAndEquals,
  unknown
> = z.object({
  field: z.string(),
  operator: z.literal("equals"),
  value: z.string(),
});

export function getV2WebhooksWebhookIdDollarAndEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdDollarAndEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2WebhooksWebhookIdDollarAndEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdDollarAndEquals' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdDollarAndUnion$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdDollarAndUnion,
  unknown
> = z.union([
  z.lazy(() => GetV2WebhooksWebhookIdDollarAndEquals$inboundSchema),
  z.lazy(() => GetV2WebhooksWebhookIdDollarAndNotEquals$inboundSchema),
]);

export function getV2WebhooksWebhookIdDollarAndUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdDollarAndUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2WebhooksWebhookIdDollarAndUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdDollarAndUnion' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdFilter2$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdFilter2,
  unknown
> = z.object({
  $and: z.array(
    z.union([
      z.lazy(() => GetV2WebhooksWebhookIdDollarAndEquals$inboundSchema),
      z.lazy(() => GetV2WebhooksWebhookIdDollarAndNotEquals$inboundSchema),
    ]),
  ),
}).transform((v) => {
  return remap$(v, {
    "$and": "dollarAnd",
  });
});

export function getV2WebhooksWebhookIdFilter2FromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdFilter2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksWebhookIdFilter2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdFilter2' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdDollarOrNotEquals$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdDollarOrNotEquals,
  unknown
> = z.object({
  field: z.string(),
  operator: z.literal("not_equals"),
  value: z.string(),
});

export function getV2WebhooksWebhookIdDollarOrNotEqualsFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2WebhooksWebhookIdDollarOrNotEquals,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2WebhooksWebhookIdDollarOrNotEquals$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV2WebhooksWebhookIdDollarOrNotEquals' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdDollarOrEquals$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdDollarOrEquals,
  unknown
> = z.object({
  field: z.string(),
  operator: z.literal("equals"),
  value: z.string(),
});

export function getV2WebhooksWebhookIdDollarOrEqualsFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdDollarOrEquals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2WebhooksWebhookIdDollarOrEquals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdDollarOrEquals' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdDollarOrUnion$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdDollarOrUnion,
  unknown
> = z.union([
  z.lazy(() => GetV2WebhooksWebhookIdDollarOrEquals$inboundSchema),
  z.lazy(() => GetV2WebhooksWebhookIdDollarOrNotEquals$inboundSchema),
]);

export function getV2WebhooksWebhookIdDollarOrUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdDollarOrUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2WebhooksWebhookIdDollarOrUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdDollarOrUnion' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdFilter1$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdFilter1,
  unknown
> = z.object({
  $or: z.array(
    z.union([
      z.lazy(() => GetV2WebhooksWebhookIdDollarOrEquals$inboundSchema),
      z.lazy(() => GetV2WebhooksWebhookIdDollarOrNotEquals$inboundSchema),
    ]),
  ),
}).transform((v) => {
  return remap$(v, {
    "$or": "dollarOr",
  });
});

export function getV2WebhooksWebhookIdFilter1FromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdFilter1, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksWebhookIdFilter1$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdFilter1' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdFilterUnion$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdFilterUnion,
  unknown
> = z.union([
  z.lazy(() => GetV2WebhooksWebhookIdFilter1$inboundSchema),
  z.lazy(() => GetV2WebhooksWebhookIdFilter2$inboundSchema),
]);

export function getV2WebhooksWebhookIdFilterUnionFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdFilterUnion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksWebhookIdFilterUnion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdFilterUnion' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdSubscription$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdSubscription,
  unknown
> = z.object({
  event_type: GetV2WebhooksWebhookIdEventType$inboundSchema,
  filter: z.nullable(
    z.union([
      z.lazy(() => GetV2WebhooksWebhookIdFilter1$inboundSchema),
      z.lazy(() => GetV2WebhooksWebhookIdFilter2$inboundSchema),
    ]),
  ),
}).transform((v) => {
  return remap$(v, {
    "event_type": "eventType",
  });
});

export function getV2WebhooksWebhookIdSubscriptionFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdSubscription, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2WebhooksWebhookIdSubscription$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdSubscription' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdId$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdId,
  unknown
> = z.object({
  workspace_id: z.string(),
  webhook_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "webhook_id": "webhookId",
  });
});

export function getV2WebhooksWebhookIdIdFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksWebhookIdId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdId' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdStatus$inboundSchema: z.ZodEnum<
  typeof GetV2WebhooksWebhookIdStatus
> = z.nativeEnum(GetV2WebhooksWebhookIdStatus);

/** @internal */
export const GetV2WebhooksWebhookIdData$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdData,
  unknown
> = z.object({
  target_url: z.string(),
  subscriptions: z.array(
    z.lazy(() => GetV2WebhooksWebhookIdSubscription$inboundSchema),
  ),
  id: z.lazy(() => GetV2WebhooksWebhookIdId$inboundSchema),
  status: GetV2WebhooksWebhookIdStatus$inboundSchema,
  created_at: z.string(),
}).transform((v) => {
  return remap$(v, {
    "target_url": "targetUrl",
    "created_at": "createdAt",
  });
});

export function getV2WebhooksWebhookIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksWebhookIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdData' from JSON`,
  );
}

/** @internal */
export const GetV2WebhooksWebhookIdResponse$inboundSchema: z.ZodType<
  GetV2WebhooksWebhookIdResponse,
  unknown
> = z.object({
  data: z.lazy(() => GetV2WebhooksWebhookIdData$inboundSchema),
});

export function getV2WebhooksWebhookIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2WebhooksWebhookIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2WebhooksWebhookIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2WebhooksWebhookIdResponse' from JSON`,
  );
}
