/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  SelectOption,
  SelectOption$inboundSchema,
} from "../components/selectoption.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Whether the attribute is on an object or a list.
 */
export const GetV2TargetIdentifierAttributesAttributeOptionsTarget = {
  Objects: "objects",
  Lists: "lists",
} as const;
/**
 * Whether the attribute is on an object or a list.
 */
export type GetV2TargetIdentifierAttributesAttributeOptionsTarget = ClosedEnum<
  typeof GetV2TargetIdentifierAttributesAttributeOptionsTarget
>;

export type GetV2TargetIdentifierAttributesAttributeOptionsRequest = {
  /**
   * Whether the attribute is on an object or a list.
   */
  target: GetV2TargetIdentifierAttributesAttributeOptionsTarget;
  identifier: string;
  attribute: string;
  showArchived?: boolean | undefined;
};

/**
 * Success
 */
export type GetV2TargetIdentifierAttributesAttributeOptionsResponse = {
  data: Array<SelectOption>;
};

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeOptionsTarget$outboundSchema:
  z.ZodEnum<
    typeof GetV2TargetIdentifierAttributesAttributeOptionsTarget
  > = z.nativeEnum(GetV2TargetIdentifierAttributesAttributeOptionsTarget);

/** @internal */
export type GetV2TargetIdentifierAttributesAttributeOptionsRequest$Outbound = {
  target: string;
  identifier: string;
  attribute: string;
  show_archived?: boolean | undefined;
};

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeOptionsRequest$outboundSchema:
  z.ZodType<
    GetV2TargetIdentifierAttributesAttributeOptionsRequest$Outbound,
    GetV2TargetIdentifierAttributesAttributeOptionsRequest
  > = z.object({
    target:
      GetV2TargetIdentifierAttributesAttributeOptionsTarget$outboundSchema,
    identifier: z.string(),
    attribute: z.string(),
    showArchived: z.boolean().optional(),
  }).transform((v) => {
    return remap$(v, {
      showArchived: "show_archived",
    });
  });

export function getV2TargetIdentifierAttributesAttributeOptionsRequestToJSON(
  getV2TargetIdentifierAttributesAttributeOptionsRequest:
    GetV2TargetIdentifierAttributesAttributeOptionsRequest,
): string {
  return JSON.stringify(
    GetV2TargetIdentifierAttributesAttributeOptionsRequest$outboundSchema.parse(
      getV2TargetIdentifierAttributesAttributeOptionsRequest,
    ),
  );
}

/** @internal */
export const GetV2TargetIdentifierAttributesAttributeOptionsResponse$inboundSchema:
  z.ZodType<
    GetV2TargetIdentifierAttributesAttributeOptionsResponse,
    unknown
  > = z.object({
    data: z.array(SelectOption$inboundSchema),
  });

export function getV2TargetIdentifierAttributesAttributeOptionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2TargetIdentifierAttributesAttributeOptionsResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2TargetIdentifierAttributesAttributeOptionsResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'GetV2TargetIdentifierAttributesAttributeOptionsResponse' from JSON`,
  );
}
