/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Task, Task$inboundSchema } from "../components/task.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2TasksTaskIdRequest = {
  taskId: string;
};

/**
 * Success
 */
export type GetV2TasksTaskIdResponse = {
  data: Task;
};

/** @internal */
export type GetV2TasksTaskIdRequest$Outbound = {
  task_id: string;
};

/** @internal */
export const GetV2TasksTaskIdRequest$outboundSchema: z.ZodType<
  GetV2TasksTaskIdRequest$Outbound,
  GetV2TasksTaskIdRequest
> = z.object({
  taskId: z.string(),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
  });
});

export function getV2TasksTaskIdRequestToJSON(
  getV2TasksTaskIdRequest: GetV2TasksTaskIdRequest,
): string {
  return JSON.stringify(
    GetV2TasksTaskIdRequest$outboundSchema.parse(getV2TasksTaskIdRequest),
  );
}

/** @internal */
export const GetV2TasksTaskIdResponse$inboundSchema: z.ZodType<
  GetV2TasksTaskIdResponse,
  unknown
> = z.object({
  data: Task$inboundSchema,
});

export function getV2TasksTaskIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2TasksTaskIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2TasksTaskIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2TasksTaskIdResponse' from JSON`,
  );
}
