/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { List, List$inboundSchema } from "../components/list.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2ListsListRequest = {
  list: string;
};

/**
 * Success
 */
export type GetV2ListsListResponse = {
  data: List;
};

/** @internal */
export type GetV2ListsListRequest$Outbound = {
  list: string;
};

/** @internal */
export const GetV2ListsListRequest$outboundSchema: z.ZodType<
  GetV2ListsListRequest$Outbound,
  GetV2ListsListRequest
> = z.object({
  list: z.string(),
});

export function getV2ListsListRequestToJSON(
  getV2ListsListRequest: GetV2ListsListRequest,
): string {
  return JSON.stringify(
    GetV2ListsListRequest$outboundSchema.parse(getV2ListsListRequest),
  );
}

/** @internal */
export const GetV2ListsListResponse$inboundSchema: z.ZodType<
  GetV2ListsListResponse,
  unknown
> = z.object({
  data: List$inboundSchema,
});

export function getV2ListsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ListsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ListsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ListsListResponse' from JSON`,
  );
}
