/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Note, Note$inboundSchema } from "../components/note.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2NotesNoteIdRequest = {
  noteId: string;
};

/**
 * Success
 */
export type GetV2NotesNoteIdResponse = {
  data: Note;
};

/** @internal */
export type GetV2NotesNoteIdRequest$Outbound = {
  note_id: string;
};

/** @internal */
export const GetV2NotesNoteIdRequest$outboundSchema: z.ZodType<
  GetV2NotesNoteIdRequest$Outbound,
  GetV2NotesNoteIdRequest
> = z.object({
  noteId: z.string(),
}).transform((v) => {
  return remap$(v, {
    noteId: "note_id",
  });
});

export function getV2NotesNoteIdRequestToJSON(
  getV2NotesNoteIdRequest: GetV2NotesNoteIdRequest,
): string {
  return JSON.stringify(
    GetV2NotesNoteIdRequest$outboundSchema.parse(getV2NotesNoteIdRequest),
  );
}

/** @internal */
export const GetV2NotesNoteIdResponse$inboundSchema: z.ZodType<
  GetV2NotesNoteIdResponse,
  unknown
> = z.object({
  data: Note$inboundSchema,
});

export function getV2NotesNoteIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2NotesNoteIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2NotesNoteIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2NotesNoteIdResponse' from JSON`,
  );
}
