/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  WorkspaceMember,
  WorkspaceMember$inboundSchema,
} from "../components/workspacemember.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2WorkspaceMembersWorkspaceMemberIdRequest = {
  workspaceMemberId: string;
};

/**
 * Success
 */
export type GetV2WorkspaceMembersWorkspaceMemberIdResponse = {
  data: WorkspaceMember;
};

/** @internal */
export type GetV2WorkspaceMembersWorkspaceMemberIdRequest$Outbound = {
  workspace_member_id: string;
};

/** @internal */
export const GetV2WorkspaceMembersWorkspaceMemberIdRequest$outboundSchema:
  z.ZodType<
    GetV2WorkspaceMembersWorkspaceMemberIdRequest$Outbound,
    GetV2WorkspaceMembersWorkspaceMemberIdRequest
  > = z.object({
    workspaceMemberId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      workspaceMemberId: "workspace_member_id",
    });
  });

export function getV2WorkspaceMembersWorkspaceMemberIdRequestToJSON(
  getV2WorkspaceMembersWorkspaceMemberIdRequest:
    GetV2WorkspaceMembersWorkspaceMemberIdRequest,
): string {
  return JSON.stringify(
    GetV2WorkspaceMembersWorkspaceMemberIdRequest$outboundSchema.parse(
      getV2WorkspaceMembersWorkspaceMemberIdRequest,
    ),
  );
}

/** @internal */
export const GetV2WorkspaceMembersWorkspaceMemberIdResponse$inboundSchema:
  z.ZodType<
    GetV2WorkspaceMembersWorkspaceMemberIdResponse,
    unknown
  > = z.object({
    data: WorkspaceMember$inboundSchema,
  });

export function getV2WorkspaceMembersWorkspaceMemberIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2WorkspaceMembersWorkspaceMemberIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2WorkspaceMembersWorkspaceMemberIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV2WorkspaceMembersWorkspaceMemberIdResponse' from JSON`,
  );
}
