/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV2ListsListEntriesEntryIdRequest = {
  list: string;
  entryId: string;
};

export type GetV2ListsListEntriesEntryIdId = {
  /**
   * A UUID identifying the workspace this entry belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the list this entry is in.
   */
  listId: string;
  /**
   * A UUID identifying this entry.
   */
  entryId: string;
};

/**
 * A list of attribute values for the list entry (not attribute values for its parent record).
 */
export type GetV2ListsListEntriesEntryIdEntryValues = {};

export type GetV2ListsListEntriesEntryIdData = {
  id: GetV2ListsListEntriesEntryIdId;
  /**
   * A UUID identifying the record that is parent of the list entry.
   */
  parentRecordId: string;
  /**
   * A UUID or slug identifying the object that the parent record belongs to.
   */
  parentObject: string;
  /**
   * When this entry was created.
   */
  createdAt: string;
  /**
   * A list of attribute values for the list entry (not attribute values for its parent record).
   */
  entryValues: GetV2ListsListEntriesEntryIdEntryValues;
};

/**
 * Success
 */
export type GetV2ListsListEntriesEntryIdResponse = {
  data: GetV2ListsListEntriesEntryIdData;
};

/** @internal */
export type GetV2ListsListEntriesEntryIdRequest$Outbound = {
  list: string;
  entry_id: string;
};

/** @internal */
export const GetV2ListsListEntriesEntryIdRequest$outboundSchema: z.ZodType<
  GetV2ListsListEntriesEntryIdRequest$Outbound,
  GetV2ListsListEntriesEntryIdRequest
> = z.object({
  list: z.string(),
  entryId: z.string(),
}).transform((v) => {
  return remap$(v, {
    entryId: "entry_id",
  });
});

export function getV2ListsListEntriesEntryIdRequestToJSON(
  getV2ListsListEntriesEntryIdRequest: GetV2ListsListEntriesEntryIdRequest,
): string {
  return JSON.stringify(
    GetV2ListsListEntriesEntryIdRequest$outboundSchema.parse(
      getV2ListsListEntriesEntryIdRequest,
    ),
  );
}

/** @internal */
export const GetV2ListsListEntriesEntryIdId$inboundSchema: z.ZodType<
  GetV2ListsListEntriesEntryIdId,
  unknown
> = z.object({
  workspace_id: z.string(),
  list_id: z.string(),
  entry_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "list_id": "listId",
    "entry_id": "entryId",
  });
});

export function getV2ListsListEntriesEntryIdIdFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ListsListEntriesEntryIdId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ListsListEntriesEntryIdId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ListsListEntriesEntryIdId' from JSON`,
  );
}

/** @internal */
export const GetV2ListsListEntriesEntryIdEntryValues$inboundSchema: z.ZodType<
  GetV2ListsListEntriesEntryIdEntryValues,
  unknown
> = z.object({});

export function getV2ListsListEntriesEntryIdEntryValuesFromJSON(
  jsonString: string,
): SafeParseResult<
  GetV2ListsListEntriesEntryIdEntryValues,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2ListsListEntriesEntryIdEntryValues$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetV2ListsListEntriesEntryIdEntryValues' from JSON`,
  );
}

/** @internal */
export const GetV2ListsListEntriesEntryIdData$inboundSchema: z.ZodType<
  GetV2ListsListEntriesEntryIdData,
  unknown
> = z.object({
  id: z.lazy(() => GetV2ListsListEntriesEntryIdId$inboundSchema),
  parent_record_id: z.string(),
  parent_object: z.string(),
  created_at: z.string(),
  entry_values: z.lazy(() =>
    GetV2ListsListEntriesEntryIdEntryValues$inboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    "parent_record_id": "parentRecordId",
    "parent_object": "parentObject",
    "created_at": "createdAt",
    "entry_values": "entryValues",
  });
});

export function getV2ListsListEntriesEntryIdDataFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ListsListEntriesEntryIdData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV2ListsListEntriesEntryIdData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ListsListEntriesEntryIdData' from JSON`,
  );
}

/** @internal */
export const GetV2ListsListEntriesEntryIdResponse$inboundSchema: z.ZodType<
  GetV2ListsListEntriesEntryIdResponse,
  unknown
> = z.object({
  data: z.lazy(() => GetV2ListsListEntriesEntryIdData$inboundSchema),
});

export function getV2ListsListEntriesEntryIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV2ListsListEntriesEntryIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetV2ListsListEntriesEntryIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV2ListsListEntriesEntryIdResponse' from JSON`,
  );
}
