/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PatchV2ListsListEntriesEntryIdDataRequest = {
  /**
   * An object with an attribute `api_slug` or `attribute_id` as the key, and a single value (for single-select attributes), or an array of values (for single or multi-select attributes) as the values. For complete documentation on values for all attribute types, please see our [attribute type docs](/docs/attribute-types).
   */
  entryValues: { [k: string]: any };
};

export type PatchV2ListsListEntriesEntryIdRequestBody = {
  data: PatchV2ListsListEntriesEntryIdDataRequest;
};

export type PatchV2ListsListEntriesEntryIdRequest = {
  list: string;
  entryId: string;
  requestBody: PatchV2ListsListEntriesEntryIdRequestBody;
};

export type PatchV2ListsListEntriesEntryIdId = {
  /**
   * A UUID identifying the workspace this entry belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the list this entry is in.
   */
  listId: string;
  /**
   * A UUID identifying this entry.
   */
  entryId: string;
};

/**
 * A list of attribute values for the list entry (not attribute values for its parent record).
 */
export type PatchV2ListsListEntriesEntryIdEntryValues = {};

export type PatchV2ListsListEntriesEntryIdDataResponse = {
  id: PatchV2ListsListEntriesEntryIdId;
  /**
   * A UUID identifying the record that is parent of the list entry.
   */
  parentRecordId: string;
  /**
   * A UUID or slug identifying the object that the parent record belongs to.
   */
  parentObject: string;
  /**
   * When this entry was created.
   */
  createdAt: string;
  /**
   * A list of attribute values for the list entry (not attribute values for its parent record).
   */
  entryValues: PatchV2ListsListEntriesEntryIdEntryValues;
};

/**
 * Success
 */
export type PatchV2ListsListEntriesEntryIdResponse = {
  data: PatchV2ListsListEntriesEntryIdDataResponse;
};

/** @internal */
export type PatchV2ListsListEntriesEntryIdDataRequest$Outbound = {
  entry_values: { [k: string]: any };
};

/** @internal */
export const PatchV2ListsListEntriesEntryIdDataRequest$outboundSchema:
  z.ZodType<
    PatchV2ListsListEntriesEntryIdDataRequest$Outbound,
    PatchV2ListsListEntriesEntryIdDataRequest
  > = z.object({
    entryValues: z.record(z.string(), z.any()),
  }).transform((v) => {
    return remap$(v, {
      entryValues: "entry_values",
    });
  });

export function patchV2ListsListEntriesEntryIdDataRequestToJSON(
  patchV2ListsListEntriesEntryIdDataRequest:
    PatchV2ListsListEntriesEntryIdDataRequest,
): string {
  return JSON.stringify(
    PatchV2ListsListEntriesEntryIdDataRequest$outboundSchema.parse(
      patchV2ListsListEntriesEntryIdDataRequest,
    ),
  );
}

/** @internal */
export type PatchV2ListsListEntriesEntryIdRequestBody$Outbound = {
  data: PatchV2ListsListEntriesEntryIdDataRequest$Outbound;
};

/** @internal */
export const PatchV2ListsListEntriesEntryIdRequestBody$outboundSchema:
  z.ZodType<
    PatchV2ListsListEntriesEntryIdRequestBody$Outbound,
    PatchV2ListsListEntriesEntryIdRequestBody
  > = z.object({
    data: z.lazy(() =>
      PatchV2ListsListEntriesEntryIdDataRequest$outboundSchema
    ),
  });

export function patchV2ListsListEntriesEntryIdRequestBodyToJSON(
  patchV2ListsListEntriesEntryIdRequestBody:
    PatchV2ListsListEntriesEntryIdRequestBody,
): string {
  return JSON.stringify(
    PatchV2ListsListEntriesEntryIdRequestBody$outboundSchema.parse(
      patchV2ListsListEntriesEntryIdRequestBody,
    ),
  );
}

/** @internal */
export type PatchV2ListsListEntriesEntryIdRequest$Outbound = {
  list: string;
  entry_id: string;
  RequestBody: PatchV2ListsListEntriesEntryIdRequestBody$Outbound;
};

/** @internal */
export const PatchV2ListsListEntriesEntryIdRequest$outboundSchema: z.ZodType<
  PatchV2ListsListEntriesEntryIdRequest$Outbound,
  PatchV2ListsListEntriesEntryIdRequest
> = z.object({
  list: z.string(),
  entryId: z.string(),
  requestBody: z.lazy(() =>
    PatchV2ListsListEntriesEntryIdRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    entryId: "entry_id",
    requestBody: "RequestBody",
  });
});

export function patchV2ListsListEntriesEntryIdRequestToJSON(
  patchV2ListsListEntriesEntryIdRequest: PatchV2ListsListEntriesEntryIdRequest,
): string {
  return JSON.stringify(
    PatchV2ListsListEntriesEntryIdRequest$outboundSchema.parse(
      patchV2ListsListEntriesEntryIdRequest,
    ),
  );
}

/** @internal */
export const PatchV2ListsListEntriesEntryIdId$inboundSchema: z.ZodType<
  PatchV2ListsListEntriesEntryIdId,
  unknown
> = z.object({
  workspace_id: z.string(),
  list_id: z.string(),
  entry_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "list_id": "listId",
    "entry_id": "entryId",
  });
});

export function patchV2ListsListEntriesEntryIdIdFromJSON(
  jsonString: string,
): SafeParseResult<PatchV2ListsListEntriesEntryIdId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchV2ListsListEntriesEntryIdId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchV2ListsListEntriesEntryIdId' from JSON`,
  );
}

/** @internal */
export const PatchV2ListsListEntriesEntryIdEntryValues$inboundSchema: z.ZodType<
  PatchV2ListsListEntriesEntryIdEntryValues,
  unknown
> = z.object({});

export function patchV2ListsListEntriesEntryIdEntryValuesFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchV2ListsListEntriesEntryIdEntryValues,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV2ListsListEntriesEntryIdEntryValues$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchV2ListsListEntriesEntryIdEntryValues' from JSON`,
  );
}

/** @internal */
export const PatchV2ListsListEntriesEntryIdDataResponse$inboundSchema:
  z.ZodType<PatchV2ListsListEntriesEntryIdDataResponse, unknown> =
    z.object({
      id: z.lazy(() => PatchV2ListsListEntriesEntryIdId$inboundSchema),
      parent_record_id: z.string(),
      parent_object: z.string(),
      created_at: z.string(),
      entry_values: z.lazy(() =>
        PatchV2ListsListEntriesEntryIdEntryValues$inboundSchema
      ),
    }).transform((v) => {
      return remap$(v, {
        "parent_record_id": "parentRecordId",
        "parent_object": "parentObject",
        "created_at": "createdAt",
        "entry_values": "entryValues",
      });
    });

export function patchV2ListsListEntriesEntryIdDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchV2ListsListEntriesEntryIdDataResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV2ListsListEntriesEntryIdDataResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchV2ListsListEntriesEntryIdDataResponse' from JSON`,
  );
}

/** @internal */
export const PatchV2ListsListEntriesEntryIdResponse$inboundSchema: z.ZodType<
  PatchV2ListsListEntriesEntryIdResponse,
  unknown
> = z.object({
  data: z.lazy(() => PatchV2ListsListEntriesEntryIdDataResponse$inboundSchema),
});

export function patchV2ListsListEntriesEntryIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchV2ListsListEntriesEntryIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV2ListsListEntriesEntryIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchV2ListsListEntriesEntryIdResponse' from JSON`,
  );
}
