/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Task, Task$inboundSchema } from "../components/task.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5 = {
  /**
   * A raw text field. Values are limited to 10MB.
   */
  value?: string | undefined;
};

/**
 * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
 */
export const PatchV2TasksTaskIdCountryCode = {
  Af: "AF",
  Ax: "AX",
  Al: "AL",
  Dz: "DZ",
  As: "AS",
  Ad: "AD",
  Ao: "AO",
  Ai: "AI",
  Aq: "AQ",
  Ag: "AG",
  Ar: "AR",
  Am: "AM",
  Aw: "AW",
  Au: "AU",
  At: "AT",
  Az: "AZ",
  Bs: "BS",
  Bh: "BH",
  Bd: "BD",
  Bb: "BB",
  By: "BY",
  Be: "BE",
  Bz: "BZ",
  Bj: "BJ",
  Bm: "BM",
  Bt: "BT",
  Bo: "BO",
  Ba: "BA",
  Bw: "BW",
  Bv: "BV",
  Br: "BR",
  Io: "IO",
  Bn: "BN",
  Bg: "BG",
  Bf: "BF",
  Bi: "BI",
  Kh: "KH",
  Cm: "CM",
  Ca: "CA",
  Cv: "CV",
  Ky: "KY",
  Cf: "CF",
  Td: "TD",
  Cl: "CL",
  Cn: "CN",
  Cx: "CX",
  Cc: "CC",
  Co: "CO",
  Km: "KM",
  Cg: "CG",
  Cd: "CD",
  Ck: "CK",
  Cr: "CR",
  Ci: "CI",
  Hr: "HR",
  Cu: "CU",
  Cw: "CW",
  Cy: "CY",
  Cz: "CZ",
  Dk: "DK",
  Dj: "DJ",
  Dm: "DM",
  Do: "DO",
  Ec: "EC",
  Eg: "EG",
  Sv: "SV",
  Gq: "GQ",
  Er: "ER",
  Ee: "EE",
  Et: "ET",
  Fk: "FK",
  Fo: "FO",
  Fj: "FJ",
  Fi: "FI",
  Fr: "FR",
  Gf: "GF",
  Pf: "PF",
  Tf: "TF",
  Ga: "GA",
  Gm: "GM",
  Ge: "GE",
  De: "DE",
  Gh: "GH",
  Gi: "GI",
  Gr: "GR",
  Gl: "GL",
  Gd: "GD",
  Gp: "GP",
  Gu: "GU",
  Gt: "GT",
  Gg: "GG",
  Gn: "GN",
  Gw: "GW",
  Gy: "GY",
  Ht: "HT",
  Hm: "HM",
  Va: "VA",
  Hn: "HN",
  Hk: "HK",
  Hu: "HU",
  Is: "IS",
  In: "IN",
  Id: "ID",
  Ir: "IR",
  Iq: "IQ",
  Ie: "IE",
  Im: "IM",
  Il: "IL",
  It: "IT",
  Jm: "JM",
  Jp: "JP",
  Je: "JE",
  Jo: "JO",
  Kz: "KZ",
  Ke: "KE",
  Ki: "KI",
  Kr: "KR",
  Kw: "KW",
  Kg: "KG",
  La: "LA",
  Lv: "LV",
  Lb: "LB",
  Ls: "LS",
  Lr: "LR",
  Ly: "LY",
  Li: "LI",
  Lt: "LT",
  Lu: "LU",
  Mo: "MO",
  Mk: "MK",
  Mg: "MG",
  Mw: "MW",
  My: "MY",
  Mv: "MV",
  Ml: "ML",
  Mt: "MT",
  Mh: "MH",
  Mq: "MQ",
  Mr: "MR",
  Mu: "MU",
  Yt: "YT",
  Mx: "MX",
  Fm: "FM",
  Md: "MD",
  Mc: "MC",
  Mn: "MN",
  Me: "ME",
  Ms: "MS",
  Ma: "MA",
  Mz: "MZ",
  Mm: "MM",
  Na: "NA",
  Nr: "NR",
  Np: "NP",
  Nl: "NL",
  An: "AN",
  Nc: "NC",
  Nz: "NZ",
  Ni: "NI",
  Ne: "NE",
  Ng: "NG",
  Nu: "NU",
  Nf: "NF",
  Mp: "MP",
  No: "NO",
  Om: "OM",
  Pk: "PK",
  Pw: "PW",
  Ps: "PS",
  Pa: "PA",
  Pg: "PG",
  Py: "PY",
  Pe: "PE",
  Ph: "PH",
  Pn: "PN",
  Pl: "PL",
  Pt: "PT",
  Pr: "PR",
  Qa: "QA",
  Re: "RE",
  Ro: "RO",
  Ru: "RU",
  Rw: "RW",
  Bl: "BL",
  Sh: "SH",
  Kn: "KN",
  Lc: "LC",
  Mf: "MF",
  Pm: "PM",
  Vc: "VC",
  Ws: "WS",
  Sm: "SM",
  St: "ST",
  Sa: "SA",
  Sn: "SN",
  Ss: "SS",
  Rs: "RS",
  Sc: "SC",
  Sl: "SL",
  Sg: "SG",
  Sk: "SK",
  Si: "SI",
  Sb: "SB",
  So: "SO",
  Za: "ZA",
  Gs: "GS",
  Es: "ES",
  Lk: "LK",
  Sd: "SD",
  Sr: "SR",
  Sj: "SJ",
  Sz: "SZ",
  Se: "SE",
  Ch: "CH",
  Sy: "SY",
  Tw: "TW",
  Tj: "TJ",
  Tz: "TZ",
  Th: "TH",
  Tl: "TL",
  Tg: "TG",
  Tk: "TK",
  To: "TO",
  Tt: "TT",
  Tn: "TN",
  Tr: "TR",
  Tm: "TM",
  Tc: "TC",
  Tv: "TV",
  Ug: "UG",
  Ua: "UA",
  Ae: "AE",
  Gb: "GB",
  Us: "US",
  Um: "UM",
  Uy: "UY",
  Uz: "UZ",
  Vu: "VU",
  Ve: "VE",
  Vn: "VN",
  Vg: "VG",
  Vi: "VI",
  Wf: "WF",
  Eh: "EH",
  Ye: "YE",
  Zm: "ZM",
  Zw: "ZW",
} as const;
/**
 * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
 */
export type PatchV2TasksTaskIdCountryCode = ClosedEnum<
  typeof PatchV2TasksTaskIdCountryCode
>;

export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4 = {
  /**
   * The raw, original phone number, as inputted.
   */
  originalPhoneNumber?: string | undefined;
  /**
   * The ISO 3166-1 alpha-2 country code representing the country that this phone number belongs to.
   */
  countryCode?: PatchV2TasksTaskIdCountryCode | null | undefined;
};

export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3 = {
  /**
   * Numbers are persisted as 64 bit floats.
   */
  value?: number | undefined;
};

export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2 = {
  /**
   * An email address string
   */
  emailAddress?: string | undefined;
};

export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1 = {
  /**
   * The full domain of the website.
   */
  domain?: string | undefined;
};

export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnion =
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5;

export type PatchV2TasksTaskIdLinkedRecord2 = {
  /**
   * A UUID or slug to identify the object that the referenced record belongs to.
   */
  targetObject: string;
  /**
   * In addition to referencing records directly by record ID, you may also reference by a matching attribute of your choice. For example, if you want to add a reference to the person record with email "alice@website.com", you should pass a value with `target_object` set to `"people"` and `email_addresses` set to `[{email_address:"alice@website.com"}]`. The key should be the slug or ID of the matching attribute you would like to use and the value should be an array containing a single value of the appropriate attribute type (as specified below). Matching on multiple values is not currently supported. Matching attributes must be unique. This process is similar to how you use the `matching_attribute` query param in Attio's [assert endpoints](/reference/put_v2-objects-object-records).
   */
  slugOrIdOfMatchingAttribute: Array<
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5
  >;
};

export type PatchV2TasksTaskIdLinkedRecord1 = {
  /**
   * The ID or slug of the parent object the tasks refers to. This can reference both standard and custom objects.`
   */
  targetObject: string;
  /**
   * The ID of the parent record the task refers to.
   */
  targetRecordId: string;
};

export type PatchV2TasksTaskIdLinkedRecordUnion =
  | PatchV2TasksTaskIdLinkedRecord1
  | PatchV2TasksTaskIdLinkedRecord2;

export type PatchV2TasksTaskIdAssignee = {
  /**
   * Workspace member actors can be referenced by email address as well as actor ID.
   */
  workspaceMemberEmailAddress: string;
};

/**
 * The actor type of the task assignee. Only `workspace-member` actors can be assigned to tasks. [Read more information on actor types here](/docs/actors).
 */
export const PatchV2TasksTaskIdReferencedActorType = {
  WorkspaceMember: "workspace-member",
} as const;
/**
 * The actor type of the task assignee. Only `workspace-member` actors can be assigned to tasks. [Read more information on actor types here](/docs/actors).
 */
export type PatchV2TasksTaskIdReferencedActorType = ClosedEnum<
  typeof PatchV2TasksTaskIdReferencedActorType
>;

export type PatchV2TasksTaskIdAssigneeWorkspaceMember = {
  /**
   * The actor type of the task assignee. Only `workspace-member` actors can be assigned to tasks. [Read more information on actor types here](/docs/actors).
   */
  referencedActorType: PatchV2TasksTaskIdReferencedActorType;
  /**
   * The ID of the actor assigned to this task.
   */
  referencedActorId: string;
};

export type PatchV2TasksTaskIdAssigneeUnion =
  | PatchV2TasksTaskIdAssigneeWorkspaceMember
  | PatchV2TasksTaskIdAssignee;

export type PatchV2TasksTaskIdData = {
  /**
   * The deadline of the task, in ISO 8601 format.
   */
  deadlineAt?: string | null | undefined;
  /**
   * Whether the task has been completed.
   */
  isCompleted?: boolean | undefined;
  /**
   * Records linked to the task. Creating record links within task content text is not possible via the API at present.
   */
  linkedRecords?:
    | Array<PatchV2TasksTaskIdLinkedRecord1 | PatchV2TasksTaskIdLinkedRecord2>
    | undefined;
  /**
   * Workspace members assigned to this task.
   */
  assignees?:
    | Array<
      PatchV2TasksTaskIdAssigneeWorkspaceMember | PatchV2TasksTaskIdAssignee
    >
    | undefined;
};

export type PatchV2TasksTaskIdRequestBody = {
  data: PatchV2TasksTaskIdData;
};

export type PatchV2TasksTaskIdRequest = {
  taskId: string;
  requestBody: PatchV2TasksTaskIdRequestBody;
};

/**
 * Success
 */
export type PatchV2TasksTaskIdResponse = {
  data: Task;
};

/** @internal */
export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5$Outbound = {
  value?: string | undefined;
};

/** @internal */
export const PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5$outboundSchema:
  z.ZodType<
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5$Outbound,
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5
  > = z.object({
    value: z.string().optional(),
  });

export function patchV2TasksTaskIdSlugOrIdOfMatchingAttribute5ToJSON(
  patchV2TasksTaskIdSlugOrIdOfMatchingAttribute5:
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5$outboundSchema.parse(
      patchV2TasksTaskIdSlugOrIdOfMatchingAttribute5,
    ),
  );
}

/** @internal */
export const PatchV2TasksTaskIdCountryCode$outboundSchema: z.ZodEnum<
  typeof PatchV2TasksTaskIdCountryCode
> = z.nativeEnum(PatchV2TasksTaskIdCountryCode);

/** @internal */
export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4$Outbound = {
  original_phone_number?: string | undefined;
  country_code?: string | null | undefined;
};

/** @internal */
export const PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4$outboundSchema:
  z.ZodType<
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4$Outbound,
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4
  > = z.object({
    originalPhoneNumber: z.string().optional(),
    countryCode: z.nullable(PatchV2TasksTaskIdCountryCode$outboundSchema)
      .optional(),
  }).transform((v) => {
    return remap$(v, {
      originalPhoneNumber: "original_phone_number",
      countryCode: "country_code",
    });
  });

export function patchV2TasksTaskIdSlugOrIdOfMatchingAttribute4ToJSON(
  patchV2TasksTaskIdSlugOrIdOfMatchingAttribute4:
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4$outboundSchema.parse(
      patchV2TasksTaskIdSlugOrIdOfMatchingAttribute4,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3$Outbound = {
  value?: number | undefined;
};

/** @internal */
export const PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3$outboundSchema:
  z.ZodType<
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3$Outbound,
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3
  > = z.object({
    value: z.number().optional(),
  });

export function patchV2TasksTaskIdSlugOrIdOfMatchingAttribute3ToJSON(
  patchV2TasksTaskIdSlugOrIdOfMatchingAttribute3:
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3$outboundSchema.parse(
      patchV2TasksTaskIdSlugOrIdOfMatchingAttribute3,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2$Outbound = {
  email_address?: string | undefined;
};

/** @internal */
export const PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2$outboundSchema:
  z.ZodType<
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2$Outbound,
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2
  > = z.object({
    emailAddress: z.string().optional(),
  }).transform((v) => {
    return remap$(v, {
      emailAddress: "email_address",
    });
  });

export function patchV2TasksTaskIdSlugOrIdOfMatchingAttribute2ToJSON(
  patchV2TasksTaskIdSlugOrIdOfMatchingAttribute2:
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2$outboundSchema.parse(
      patchV2TasksTaskIdSlugOrIdOfMatchingAttribute2,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1$Outbound = {
  domain?: string | undefined;
};

/** @internal */
export const PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1$outboundSchema:
  z.ZodType<
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1$Outbound,
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1
  > = z.object({
    domain: z.string().optional(),
  });

export function patchV2TasksTaskIdSlugOrIdOfMatchingAttribute1ToJSON(
  patchV2TasksTaskIdSlugOrIdOfMatchingAttribute1:
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1$outboundSchema.parse(
      patchV2TasksTaskIdSlugOrIdOfMatchingAttribute1,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnion$Outbound =
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1$Outbound
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2$Outbound
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3$Outbound
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4$Outbound
  | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5$Outbound;

/** @internal */
export const PatchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnion$outboundSchema:
  z.ZodType<
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnion$Outbound,
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnion
  > = z.union([
    z.lazy(() => PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1$outboundSchema),
    z.lazy(() => PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2$outboundSchema),
    z.lazy(() => PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3$outboundSchema),
    z.lazy(() => PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4$outboundSchema),
    z.lazy(() => PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5$outboundSchema),
  ]);

export function patchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnionToJSON(
  patchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnion:
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnion,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnion$outboundSchema.parse(
      patchV2TasksTaskIdSlugOrIdOfMatchingAttributeUnion,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdLinkedRecord2$Outbound = {
  target_object: string;
  "[slug_or_id_of_matching_attribute]": Array<
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1$Outbound
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2$Outbound
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3$Outbound
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4$Outbound
    | PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5$Outbound
  >;
};

/** @internal */
export const PatchV2TasksTaskIdLinkedRecord2$outboundSchema: z.ZodType<
  PatchV2TasksTaskIdLinkedRecord2$Outbound,
  PatchV2TasksTaskIdLinkedRecord2
> = z.object({
  targetObject: z.string(),
  slugOrIdOfMatchingAttribute: z.array(
    z.union([
      z.lazy(() =>
        PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute1$outboundSchema
      ),
      z.lazy(() =>
        PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute2$outboundSchema
      ),
      z.lazy(() =>
        PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute3$outboundSchema
      ),
      z.lazy(() =>
        PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute4$outboundSchema
      ),
      z.lazy(() =>
        PatchV2TasksTaskIdSlugOrIdOfMatchingAttribute5$outboundSchema
      ),
    ]),
  ),
}).transform((v) => {
  return remap$(v, {
    targetObject: "target_object",
    slugOrIdOfMatchingAttribute: "[slug_or_id_of_matching_attribute]",
  });
});

export function patchV2TasksTaskIdLinkedRecord2ToJSON(
  patchV2TasksTaskIdLinkedRecord2: PatchV2TasksTaskIdLinkedRecord2,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdLinkedRecord2$outboundSchema.parse(
      patchV2TasksTaskIdLinkedRecord2,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdLinkedRecord1$Outbound = {
  target_object: string;
  target_record_id: string;
};

/** @internal */
export const PatchV2TasksTaskIdLinkedRecord1$outboundSchema: z.ZodType<
  PatchV2TasksTaskIdLinkedRecord1$Outbound,
  PatchV2TasksTaskIdLinkedRecord1
> = z.object({
  targetObject: z.string(),
  targetRecordId: z.string(),
}).transform((v) => {
  return remap$(v, {
    targetObject: "target_object",
    targetRecordId: "target_record_id",
  });
});

export function patchV2TasksTaskIdLinkedRecord1ToJSON(
  patchV2TasksTaskIdLinkedRecord1: PatchV2TasksTaskIdLinkedRecord1,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdLinkedRecord1$outboundSchema.parse(
      patchV2TasksTaskIdLinkedRecord1,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdLinkedRecordUnion$Outbound =
  | PatchV2TasksTaskIdLinkedRecord1$Outbound
  | PatchV2TasksTaskIdLinkedRecord2$Outbound;

/** @internal */
export const PatchV2TasksTaskIdLinkedRecordUnion$outboundSchema: z.ZodType<
  PatchV2TasksTaskIdLinkedRecordUnion$Outbound,
  PatchV2TasksTaskIdLinkedRecordUnion
> = z.union([
  z.lazy(() => PatchV2TasksTaskIdLinkedRecord1$outboundSchema),
  z.lazy(() => PatchV2TasksTaskIdLinkedRecord2$outboundSchema),
]);

export function patchV2TasksTaskIdLinkedRecordUnionToJSON(
  patchV2TasksTaskIdLinkedRecordUnion: PatchV2TasksTaskIdLinkedRecordUnion,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdLinkedRecordUnion$outboundSchema.parse(
      patchV2TasksTaskIdLinkedRecordUnion,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdAssignee$Outbound = {
  workspace_member_email_address: string;
};

/** @internal */
export const PatchV2TasksTaskIdAssignee$outboundSchema: z.ZodType<
  PatchV2TasksTaskIdAssignee$Outbound,
  PatchV2TasksTaskIdAssignee
> = z.object({
  workspaceMemberEmailAddress: z.string(),
}).transform((v) => {
  return remap$(v, {
    workspaceMemberEmailAddress: "workspace_member_email_address",
  });
});

export function patchV2TasksTaskIdAssigneeToJSON(
  patchV2TasksTaskIdAssignee: PatchV2TasksTaskIdAssignee,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdAssignee$outboundSchema.parse(patchV2TasksTaskIdAssignee),
  );
}

/** @internal */
export const PatchV2TasksTaskIdReferencedActorType$outboundSchema:
  z.ZodEnum<typeof PatchV2TasksTaskIdReferencedActorType> = z.nativeEnum(
    PatchV2TasksTaskIdReferencedActorType,
  );

/** @internal */
export type PatchV2TasksTaskIdAssigneeWorkspaceMember$Outbound = {
  referenced_actor_type: string;
  referenced_actor_id: string;
};

/** @internal */
export const PatchV2TasksTaskIdAssigneeWorkspaceMember$outboundSchema:
  z.ZodType<
    PatchV2TasksTaskIdAssigneeWorkspaceMember$Outbound,
    PatchV2TasksTaskIdAssigneeWorkspaceMember
  > = z.object({
    referencedActorType: PatchV2TasksTaskIdReferencedActorType$outboundSchema,
    referencedActorId: z.string(),
  }).transform((v) => {
    return remap$(v, {
      referencedActorType: "referenced_actor_type",
      referencedActorId: "referenced_actor_id",
    });
  });

export function patchV2TasksTaskIdAssigneeWorkspaceMemberToJSON(
  patchV2TasksTaskIdAssigneeWorkspaceMember:
    PatchV2TasksTaskIdAssigneeWorkspaceMember,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdAssigneeWorkspaceMember$outboundSchema.parse(
      patchV2TasksTaskIdAssigneeWorkspaceMember,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdAssigneeUnion$Outbound =
  | PatchV2TasksTaskIdAssigneeWorkspaceMember$Outbound
  | PatchV2TasksTaskIdAssignee$Outbound;

/** @internal */
export const PatchV2TasksTaskIdAssigneeUnion$outboundSchema: z.ZodType<
  PatchV2TasksTaskIdAssigneeUnion$Outbound,
  PatchV2TasksTaskIdAssigneeUnion
> = z.union([
  z.lazy(() => PatchV2TasksTaskIdAssigneeWorkspaceMember$outboundSchema),
  z.lazy(() => PatchV2TasksTaskIdAssignee$outboundSchema),
]);

export function patchV2TasksTaskIdAssigneeUnionToJSON(
  patchV2TasksTaskIdAssigneeUnion: PatchV2TasksTaskIdAssigneeUnion,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdAssigneeUnion$outboundSchema.parse(
      patchV2TasksTaskIdAssigneeUnion,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdData$Outbound = {
  deadline_at?: string | null | undefined;
  is_completed?: boolean | undefined;
  linked_records?:
    | Array<
      | PatchV2TasksTaskIdLinkedRecord1$Outbound
      | PatchV2TasksTaskIdLinkedRecord2$Outbound
    >
    | undefined;
  assignees?:
    | Array<
      | PatchV2TasksTaskIdAssigneeWorkspaceMember$Outbound
      | PatchV2TasksTaskIdAssignee$Outbound
    >
    | undefined;
};

/** @internal */
export const PatchV2TasksTaskIdData$outboundSchema: z.ZodType<
  PatchV2TasksTaskIdData$Outbound,
  PatchV2TasksTaskIdData
> = z.object({
  deadlineAt: z.nullable(z.string()).optional(),
  isCompleted: z.boolean().optional(),
  linkedRecords: z.array(
    z.union([
      z.lazy(() => PatchV2TasksTaskIdLinkedRecord1$outboundSchema),
      z.lazy(() => PatchV2TasksTaskIdLinkedRecord2$outboundSchema),
    ]),
  ).optional(),
  assignees: z.array(
    z.union([
      z.lazy(() => PatchV2TasksTaskIdAssigneeWorkspaceMember$outboundSchema),
      z.lazy(() => PatchV2TasksTaskIdAssignee$outboundSchema),
    ]),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    deadlineAt: "deadline_at",
    isCompleted: "is_completed",
    linkedRecords: "linked_records",
  });
});

export function patchV2TasksTaskIdDataToJSON(
  patchV2TasksTaskIdData: PatchV2TasksTaskIdData,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdData$outboundSchema.parse(patchV2TasksTaskIdData),
  );
}

/** @internal */
export type PatchV2TasksTaskIdRequestBody$Outbound = {
  data: PatchV2TasksTaskIdData$Outbound;
};

/** @internal */
export const PatchV2TasksTaskIdRequestBody$outboundSchema: z.ZodType<
  PatchV2TasksTaskIdRequestBody$Outbound,
  PatchV2TasksTaskIdRequestBody
> = z.object({
  data: z.lazy(() => PatchV2TasksTaskIdData$outboundSchema),
});

export function patchV2TasksTaskIdRequestBodyToJSON(
  patchV2TasksTaskIdRequestBody: PatchV2TasksTaskIdRequestBody,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdRequestBody$outboundSchema.parse(
      patchV2TasksTaskIdRequestBody,
    ),
  );
}

/** @internal */
export type PatchV2TasksTaskIdRequest$Outbound = {
  task_id: string;
  RequestBody: PatchV2TasksTaskIdRequestBody$Outbound;
};

/** @internal */
export const PatchV2TasksTaskIdRequest$outboundSchema: z.ZodType<
  PatchV2TasksTaskIdRequest$Outbound,
  PatchV2TasksTaskIdRequest
> = z.object({
  taskId: z.string(),
  requestBody: z.lazy(() => PatchV2TasksTaskIdRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    taskId: "task_id",
    requestBody: "RequestBody",
  });
});

export function patchV2TasksTaskIdRequestToJSON(
  patchV2TasksTaskIdRequest: PatchV2TasksTaskIdRequest,
): string {
  return JSON.stringify(
    PatchV2TasksTaskIdRequest$outboundSchema.parse(patchV2TasksTaskIdRequest),
  );
}

/** @internal */
export const PatchV2TasksTaskIdResponse$inboundSchema: z.ZodType<
  PatchV2TasksTaskIdResponse,
  unknown
> = z.object({
  data: Task$inboundSchema,
});

export function patchV2TasksTaskIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchV2TasksTaskIdResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchV2TasksTaskIdResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchV2TasksTaskIdResponse' from JSON`,
  );
}
