/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { List, List$inboundSchema } from "../components/list.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
 */
export const PatchV2ListsListWorkspaceAccess = {
  FullAccess: "full-access",
  ReadAndWrite: "read-and-write",
  ReadOnly: "read-only",
} as const;
/**
 * The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
 */
export type PatchV2ListsListWorkspaceAccess = ClosedEnum<
  typeof PatchV2ListsListWorkspaceAccess
>;

/**
 * The level of access to the list.
 */
export const PatchV2ListsListLevel = {
  FullAccess: "full-access",
  ReadAndWrite: "read-and-write",
  ReadOnly: "read-only",
} as const;
/**
 * The level of access to the list.
 */
export type PatchV2ListsListLevel = ClosedEnum<typeof PatchV2ListsListLevel>;

export type PatchV2ListsListWorkspaceMemberAccess = {
  /**
   * A UUID to identify the workspace member to grant access to.
   */
  workspaceMemberId: string;
  /**
   * The level of access to the list.
   */
  level: PatchV2ListsListLevel;
};

export type PatchV2ListsListData = {
  /**
   * The human-readable name of the list.
   */
  name?: string | undefined;
  /**
   * A unique, human-readable slug to access the list through API calls. Should be formatted in snake case.
   */
  apiSlug?: string | undefined;
  /**
   * The level of access granted to all members of the workspace for this list. Pass `null` to keep the list private and only grant access to specific workspace members.
   */
  workspaceAccess?: PatchV2ListsListWorkspaceAccess | null | undefined;
  /**
   * The level of access granted to specific workspace members for this list. Pass an empty array to grant access to no workspace members.
   */
  workspaceMemberAccess?:
    | Array<PatchV2ListsListWorkspaceMemberAccess>
    | undefined;
};

export type PatchV2ListsListRequestBody = {
  data: PatchV2ListsListData;
};

export type PatchV2ListsListRequest = {
  list: string;
  requestBody: PatchV2ListsListRequestBody;
};

/**
 * Success
 */
export type PatchV2ListsListResponse = {
  data: List;
};

/** @internal */
export const PatchV2ListsListWorkspaceAccess$outboundSchema: z.ZodEnum<
  typeof PatchV2ListsListWorkspaceAccess
> = z.nativeEnum(PatchV2ListsListWorkspaceAccess);

/** @internal */
export const PatchV2ListsListLevel$outboundSchema: z.ZodEnum<
  typeof PatchV2ListsListLevel
> = z.nativeEnum(PatchV2ListsListLevel);

/** @internal */
export type PatchV2ListsListWorkspaceMemberAccess$Outbound = {
  workspace_member_id: string;
  level: string;
};

/** @internal */
export const PatchV2ListsListWorkspaceMemberAccess$outboundSchema: z.ZodType<
  PatchV2ListsListWorkspaceMemberAccess$Outbound,
  PatchV2ListsListWorkspaceMemberAccess
> = z.object({
  workspaceMemberId: z.string(),
  level: PatchV2ListsListLevel$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    workspaceMemberId: "workspace_member_id",
  });
});

export function patchV2ListsListWorkspaceMemberAccessToJSON(
  patchV2ListsListWorkspaceMemberAccess: PatchV2ListsListWorkspaceMemberAccess,
): string {
  return JSON.stringify(
    PatchV2ListsListWorkspaceMemberAccess$outboundSchema.parse(
      patchV2ListsListWorkspaceMemberAccess,
    ),
  );
}

/** @internal */
export type PatchV2ListsListData$Outbound = {
  name?: string | undefined;
  api_slug?: string | undefined;
  workspace_access?: string | null | undefined;
  workspace_member_access?:
    | Array<PatchV2ListsListWorkspaceMemberAccess$Outbound>
    | undefined;
};

/** @internal */
export const PatchV2ListsListData$outboundSchema: z.ZodType<
  PatchV2ListsListData$Outbound,
  PatchV2ListsListData
> = z.object({
  name: z.string().optional(),
  apiSlug: z.string().optional(),
  workspaceAccess: z.nullable(PatchV2ListsListWorkspaceAccess$outboundSchema)
    .optional(),
  workspaceMemberAccess: z.array(
    z.lazy(() => PatchV2ListsListWorkspaceMemberAccess$outboundSchema),
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    apiSlug: "api_slug",
    workspaceAccess: "workspace_access",
    workspaceMemberAccess: "workspace_member_access",
  });
});

export function patchV2ListsListDataToJSON(
  patchV2ListsListData: PatchV2ListsListData,
): string {
  return JSON.stringify(
    PatchV2ListsListData$outboundSchema.parse(patchV2ListsListData),
  );
}

/** @internal */
export type PatchV2ListsListRequestBody$Outbound = {
  data: PatchV2ListsListData$Outbound;
};

/** @internal */
export const PatchV2ListsListRequestBody$outboundSchema: z.ZodType<
  PatchV2ListsListRequestBody$Outbound,
  PatchV2ListsListRequestBody
> = z.object({
  data: z.lazy(() => PatchV2ListsListData$outboundSchema),
});

export function patchV2ListsListRequestBodyToJSON(
  patchV2ListsListRequestBody: PatchV2ListsListRequestBody,
): string {
  return JSON.stringify(
    PatchV2ListsListRequestBody$outboundSchema.parse(
      patchV2ListsListRequestBody,
    ),
  );
}

/** @internal */
export type PatchV2ListsListRequest$Outbound = {
  list: string;
  RequestBody: PatchV2ListsListRequestBody$Outbound;
};

/** @internal */
export const PatchV2ListsListRequest$outboundSchema: z.ZodType<
  PatchV2ListsListRequest$Outbound,
  PatchV2ListsListRequest
> = z.object({
  list: z.string(),
  requestBody: z.lazy(() => PatchV2ListsListRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function patchV2ListsListRequestToJSON(
  patchV2ListsListRequest: PatchV2ListsListRequest,
): string {
  return JSON.stringify(
    PatchV2ListsListRequest$outboundSchema.parse(patchV2ListsListRequest),
  );
}

/** @internal */
export const PatchV2ListsListResponse$inboundSchema: z.ZodType<
  PatchV2ListsListResponse,
  unknown
> = z.object({
  data: List$inboundSchema,
});

export function patchV2ListsListResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchV2ListsListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchV2ListsListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchV2ListsListResponse' from JSON`,
  );
}
