/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import {
  SelectOption,
  SelectOption$inboundSchema,
} from "../components/selectoption.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Whether the attribute is on an object or a list.
 */
export const PatchV2TargetIdentifierAttributesAttributeOptionsOptionTarget = {
  Objects: "objects",
  Lists: "lists",
} as const;
/**
 * Whether the attribute is on an object or a list.
 */
export type PatchV2TargetIdentifierAttributesAttributeOptionsOptionTarget =
  ClosedEnum<
    typeof PatchV2TargetIdentifierAttributesAttributeOptionsOptionTarget
  >;

export type PatchV2TargetIdentifierAttributesAttributeOptionsOptionData = {
  /**
   * The Title of the select option
   */
  title?: string | undefined;
  /**
   * Whether or not to archive the select option. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving.
   */
  isArchived?: boolean | undefined;
};

export type PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody =
  {
    data: PatchV2TargetIdentifierAttributesAttributeOptionsOptionData;
  };

export type PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequest = {
  /**
   * Whether the attribute is on an object or a list.
   */
  target: PatchV2TargetIdentifierAttributesAttributeOptionsOptionTarget;
  identifier: string;
  attribute: string;
  option: string;
  requestBody:
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody;
};

/**
 * Success
 */
export type PatchV2TargetIdentifierAttributesAttributeOptionsOptionResponse = {
  data: SelectOption;
};

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeOptionsOptionTarget$outboundSchema:
  z.ZodEnum<
    typeof PatchV2TargetIdentifierAttributesAttributeOptionsOptionTarget
  > = z.nativeEnum(
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionTarget,
  );

/** @internal */
export type PatchV2TargetIdentifierAttributesAttributeOptionsOptionData$Outbound =
  {
    title?: string | undefined;
    is_archived?: boolean | undefined;
  };

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeOptionsOptionData$outboundSchema:
  z.ZodType<
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionData$Outbound,
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionData
  > = z.object({
    title: z.string().optional(),
    isArchived: z.boolean().optional(),
  }).transform((v) => {
    return remap$(v, {
      isArchived: "is_archived",
    });
  });

export function patchV2TargetIdentifierAttributesAttributeOptionsOptionDataToJSON(
  patchV2TargetIdentifierAttributesAttributeOptionsOptionData:
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionData,
): string {
  return JSON.stringify(
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionData$outboundSchema
      .parse(patchV2TargetIdentifierAttributesAttributeOptionsOptionData),
  );
}

/** @internal */
export type PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody$Outbound =
  {
    data: PatchV2TargetIdentifierAttributesAttributeOptionsOptionData$Outbound;
  };

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody$outboundSchema:
  z.ZodType<
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody$Outbound,
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody
  > = z.object({
    data: z.lazy(() =>
      PatchV2TargetIdentifierAttributesAttributeOptionsOptionData$outboundSchema
    ),
  });

export function patchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBodyToJSON(
  patchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody:
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody,
): string {
  return JSON.stringify(
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody$outboundSchema
      .parse(
        patchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody,
      ),
  );
}

/** @internal */
export type PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequest$Outbound =
  {
    target: string;
    identifier: string;
    attribute: string;
    option: string;
    RequestBody:
      PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody$Outbound;
  };

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequest$outboundSchema:
  z.ZodType<
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequest$Outbound,
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequest
  > = z.object({
    target:
      PatchV2TargetIdentifierAttributesAttributeOptionsOptionTarget$outboundSchema,
    identifier: z.string(),
    attribute: z.string(),
    option: z.string(),
    requestBody: z.lazy(() =>
      PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequestBody$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      requestBody: "RequestBody",
    });
  });

export function patchV2TargetIdentifierAttributesAttributeOptionsOptionRequestToJSON(
  patchV2TargetIdentifierAttributesAttributeOptionsOptionRequest:
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequest,
): string {
  return JSON.stringify(
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionRequest$outboundSchema
      .parse(patchV2TargetIdentifierAttributesAttributeOptionsOptionRequest),
  );
}

/** @internal */
export const PatchV2TargetIdentifierAttributesAttributeOptionsOptionResponse$inboundSchema:
  z.ZodType<
    PatchV2TargetIdentifierAttributesAttributeOptionsOptionResponse,
    unknown
  > = z.object({
    data: SelectOption$inboundSchema,
  });

export function patchV2TargetIdentifierAttributesAttributeOptionsOptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchV2TargetIdentifierAttributesAttributeOptionsOptionResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV2TargetIdentifierAttributesAttributeOptionsOptionResponse$inboundSchema
        .parse(JSON.parse(x)),
    `Failed to parse 'PatchV2TargetIdentifierAttributesAttributeOptionsOptionResponse' from JSON`,
  );
}
