/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PatchV2ObjectsObjectRecordsRecordIdDataRequest = {
  /**
   * An object with an attribute `api_slug` or `attribute_id` as the key, and a single value (for single-select attributes), or an array of values (for single or multi-select attributes) as the values. For complete documentation on values for all attribute types, please see our [attribute type docs](/docs/attribute-types).
   */
  values: { [k: string]: any };
};

export type PatchV2ObjectsObjectRecordsRecordIdRequestBody = {
  data: PatchV2ObjectsObjectRecordsRecordIdDataRequest;
};

export type PatchV2ObjectsObjectRecordsRecordIdRequest = {
  object: string;
  recordId: string;
  requestBody: PatchV2ObjectsObjectRecordsRecordIdRequestBody;
};

export type PatchV2ObjectsObjectRecordsRecordIdId = {
  /**
   * A UUID identifying the workspace this record belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the object this record belongs to.
   */
  objectId: string;
  /**
   * A UUID identifying this record.
   */
  recordId: string;
};

export type PatchV2ObjectsObjectRecordsRecordIdDataResponse = {
  id: PatchV2ObjectsObjectRecordsRecordIdId;
  /**
   * When this record was created.
   */
  createdAt: string;
  /**
   * A record type with an attribute `api_slug` as the key, and an array of value objects as the values.
   */
  values: { [k: string]: any };
};

/**
 * Success
 */
export type PatchV2ObjectsObjectRecordsRecordIdResponse = {
  data: PatchV2ObjectsObjectRecordsRecordIdDataResponse;
};

/** @internal */
export type PatchV2ObjectsObjectRecordsRecordIdDataRequest$Outbound = {
  values: { [k: string]: any };
};

/** @internal */
export const PatchV2ObjectsObjectRecordsRecordIdDataRequest$outboundSchema:
  z.ZodType<
    PatchV2ObjectsObjectRecordsRecordIdDataRequest$Outbound,
    PatchV2ObjectsObjectRecordsRecordIdDataRequest
  > = z.object({
    values: z.record(z.string(), z.any()),
  });

export function patchV2ObjectsObjectRecordsRecordIdDataRequestToJSON(
  patchV2ObjectsObjectRecordsRecordIdDataRequest:
    PatchV2ObjectsObjectRecordsRecordIdDataRequest,
): string {
  return JSON.stringify(
    PatchV2ObjectsObjectRecordsRecordIdDataRequest$outboundSchema.parse(
      patchV2ObjectsObjectRecordsRecordIdDataRequest,
    ),
  );
}

/** @internal */
export type PatchV2ObjectsObjectRecordsRecordIdRequestBody$Outbound = {
  data: PatchV2ObjectsObjectRecordsRecordIdDataRequest$Outbound;
};

/** @internal */
export const PatchV2ObjectsObjectRecordsRecordIdRequestBody$outboundSchema:
  z.ZodType<
    PatchV2ObjectsObjectRecordsRecordIdRequestBody$Outbound,
    PatchV2ObjectsObjectRecordsRecordIdRequestBody
  > = z.object({
    data: z.lazy(() =>
      PatchV2ObjectsObjectRecordsRecordIdDataRequest$outboundSchema
    ),
  });

export function patchV2ObjectsObjectRecordsRecordIdRequestBodyToJSON(
  patchV2ObjectsObjectRecordsRecordIdRequestBody:
    PatchV2ObjectsObjectRecordsRecordIdRequestBody,
): string {
  return JSON.stringify(
    PatchV2ObjectsObjectRecordsRecordIdRequestBody$outboundSchema.parse(
      patchV2ObjectsObjectRecordsRecordIdRequestBody,
    ),
  );
}

/** @internal */
export type PatchV2ObjectsObjectRecordsRecordIdRequest$Outbound = {
  object: string;
  record_id: string;
  RequestBody: PatchV2ObjectsObjectRecordsRecordIdRequestBody$Outbound;
};

/** @internal */
export const PatchV2ObjectsObjectRecordsRecordIdRequest$outboundSchema:
  z.ZodType<
    PatchV2ObjectsObjectRecordsRecordIdRequest$Outbound,
    PatchV2ObjectsObjectRecordsRecordIdRequest
  > = z.object({
    object: z.string(),
    recordId: z.string(),
    requestBody: z.lazy(() =>
      PatchV2ObjectsObjectRecordsRecordIdRequestBody$outboundSchema
    ),
  }).transform((v) => {
    return remap$(v, {
      recordId: "record_id",
      requestBody: "RequestBody",
    });
  });

export function patchV2ObjectsObjectRecordsRecordIdRequestToJSON(
  patchV2ObjectsObjectRecordsRecordIdRequest:
    PatchV2ObjectsObjectRecordsRecordIdRequest,
): string {
  return JSON.stringify(
    PatchV2ObjectsObjectRecordsRecordIdRequest$outboundSchema.parse(
      patchV2ObjectsObjectRecordsRecordIdRequest,
    ),
  );
}

/** @internal */
export const PatchV2ObjectsObjectRecordsRecordIdId$inboundSchema: z.ZodType<
  PatchV2ObjectsObjectRecordsRecordIdId,
  unknown
> = z.object({
  workspace_id: z.string(),
  object_id: z.string(),
  record_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "object_id": "objectId",
    "record_id": "recordId",
  });
});

export function patchV2ObjectsObjectRecordsRecordIdIdFromJSON(
  jsonString: string,
): SafeParseResult<PatchV2ObjectsObjectRecordsRecordIdId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV2ObjectsObjectRecordsRecordIdId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchV2ObjectsObjectRecordsRecordIdId' from JSON`,
  );
}

/** @internal */
export const PatchV2ObjectsObjectRecordsRecordIdDataResponse$inboundSchema:
  z.ZodType<
    PatchV2ObjectsObjectRecordsRecordIdDataResponse,
    unknown
  > = z.object({
    id: z.lazy(() => PatchV2ObjectsObjectRecordsRecordIdId$inboundSchema),
    created_at: z.string(),
    values: z.record(z.string(), z.any()),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  });

export function patchV2ObjectsObjectRecordsRecordIdDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchV2ObjectsObjectRecordsRecordIdDataResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV2ObjectsObjectRecordsRecordIdDataResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchV2ObjectsObjectRecordsRecordIdDataResponse' from JSON`,
  );
}

/** @internal */
export const PatchV2ObjectsObjectRecordsRecordIdResponse$inboundSchema:
  z.ZodType<
    PatchV2ObjectsObjectRecordsRecordIdResponse,
    unknown
  > = z.object({
    data: z.lazy(() =>
      PatchV2ObjectsObjectRecordsRecordIdDataResponse$inboundSchema
    ),
  });

export function patchV2ObjectsObjectRecordsRecordIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PatchV2ObjectsObjectRecordsRecordIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PatchV2ObjectsObjectRecordsRecordIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PatchV2ObjectsObjectRecordsRecordIdResponse' from JSON`,
  );
}
