/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Comment, Comment$inboundSchema } from "../components/comment.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The format that the comment content is provided in. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. Rich text formatting and links are not supported.
 */
export const PostV2CommentsFormat3 = {
  Plaintext: "plaintext",
} as const;
/**
 * The format that the comment content is provided in. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. Rich text formatting and links are not supported.
 */
export type PostV2CommentsFormat3 = ClosedEnum<typeof PostV2CommentsFormat3>;

export const PostV2CommentsType3 = {
  WorkspaceMember: "workspace-member",
} as const;
export type PostV2CommentsType3 = ClosedEnum<typeof PostV2CommentsType3>;

/**
 * The workspace member who wrote this comment. Note that other types of actors are not currently supported.
 */
export type Author3 = {
  type: PostV2CommentsType3;
  id: string;
};

export type Entry = {
  /**
   * If creating a top-level comment on a list entry, this is the slug or ID of that list.
   */
  list: string;
  /**
   * If creating a top-level comment on a list entry, this is the ID of that entry.
   */
  entryId: string;
};

export type PostV2CommentsDataPlaintext3 = {
  /**
   * The format that the comment content is provided in. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. Rich text formatting and links are not supported.
   */
  format: PostV2CommentsFormat3;
  /**
   * The content of the comment itself. Workspace members can be mentioned using their email address, otherwise email addresses will be presented to users as clickable mailto links.
   */
  content: string;
  /**
   * The workspace member who wrote this comment. Note that other types of actors are not currently supported.
   */
  author: Author3;
  /**
   * `created_at` will default to the current time. However, if you wish to backdate a comment for migration or other purposes, you can override with a custom `created_at` value. Note that dates before 1970 or in the future are not allowed.
   */
  createdAt?: string | undefined;
  entry: Entry;
};

/**
 * The format that the comment content is provided in. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. Rich text formatting and links are not supported.
 */
export const PostV2CommentsFormat2 = {
  Plaintext: "plaintext",
} as const;
/**
 * The format that the comment content is provided in. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. Rich text formatting and links are not supported.
 */
export type PostV2CommentsFormat2 = ClosedEnum<typeof PostV2CommentsFormat2>;

export const PostV2CommentsType2 = {
  WorkspaceMember: "workspace-member",
} as const;
export type PostV2CommentsType2 = ClosedEnum<typeof PostV2CommentsType2>;

/**
 * The workspace member who wrote this comment. Note that other types of actors are not currently supported.
 */
export type Author2 = {
  type: PostV2CommentsType2;
  id: string;
};

export type RecordT = {
  /**
   * If creating a top-level comment on a record, this is the slug or ID of that object.
   */
  object: string;
  /**
   * If creating a top-level comment on a record, this is the ID of that record.
   */
  recordId: string;
};

export type PostV2CommentsDataPlaintext2 = {
  /**
   * The format that the comment content is provided in. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. Rich text formatting and links are not supported.
   */
  format: PostV2CommentsFormat2;
  /**
   * The content of the comment itself. Workspace members can be mentioned using their email address, otherwise email addresses will be presented to users as clickable mailto links.
   */
  content: string;
  /**
   * The workspace member who wrote this comment. Note that other types of actors are not currently supported.
   */
  author: Author2;
  /**
   * `created_at` will default to the current time. However, if you wish to backdate a comment for migration or other purposes, you can override with a custom `created_at` value. Note that dates before 1970 or in the future are not allowed.
   */
  createdAt?: string | undefined;
  record: RecordT;
};

/**
 * The format that the comment content is provided in. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. Rich text formatting and links are not supported.
 */
export const PostV2CommentsFormat1 = {
  Plaintext: "plaintext",
} as const;
/**
 * The format that the comment content is provided in. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. Rich text formatting and links are not supported.
 */
export type PostV2CommentsFormat1 = ClosedEnum<typeof PostV2CommentsFormat1>;

export const PostV2CommentsType1 = {
  WorkspaceMember: "workspace-member",
} as const;
export type PostV2CommentsType1 = ClosedEnum<typeof PostV2CommentsType1>;

/**
 * The workspace member who wrote this comment. Note that other types of actors are not currently supported.
 */
export type Author1 = {
  type: PostV2CommentsType1;
  id: string;
};

export type PostV2CommentsDataPlaintext1 = {
  /**
   * The format that the comment content is provided in. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. Rich text formatting and links are not supported.
   */
  format: PostV2CommentsFormat1;
  /**
   * The content of the comment itself. Workspace members can be mentioned using their email address, otherwise email addresses will be presented to users as clickable mailto links.
   */
  content: string;
  /**
   * The workspace member who wrote this comment. Note that other types of actors are not currently supported.
   */
  author: Author1;
  /**
   * `created_at` will default to the current time. However, if you wish to backdate a comment for migration or other purposes, you can override with a custom `created_at` value. Note that dates before 1970 or in the future are not allowed.
   */
  createdAt?: string | undefined;
  /**
   * If responding to an existing thread, this would be the ID of that thread.
   */
  threadId: string;
};

export type PostV2CommentsDataUnion =
  | PostV2CommentsDataPlaintext1
  | PostV2CommentsDataPlaintext2
  | PostV2CommentsDataPlaintext3;

export type PostV2CommentsRequest = {
  data:
    | PostV2CommentsDataPlaintext1
    | PostV2CommentsDataPlaintext2
    | PostV2CommentsDataPlaintext3;
};

/**
 * Success
 */
export type PostV2CommentsResponse = {
  data: Comment;
};

/** @internal */
export const PostV2CommentsFormat3$outboundSchema: z.ZodEnum<
  typeof PostV2CommentsFormat3
> = z.nativeEnum(PostV2CommentsFormat3);

/** @internal */
export const PostV2CommentsType3$outboundSchema: z.ZodEnum<
  typeof PostV2CommentsType3
> = z.nativeEnum(PostV2CommentsType3);

/** @internal */
export type Author3$Outbound = {
  type: string;
  id: string;
};

/** @internal */
export const Author3$outboundSchema: z.ZodType<
  Author3$Outbound,
  Author3
> = z.object({
  type: PostV2CommentsType3$outboundSchema,
  id: z.string(),
});

export function author3ToJSON(author3: Author3): string {
  return JSON.stringify(Author3$outboundSchema.parse(author3));
}

/** @internal */
export type Entry$Outbound = {
  list: string;
  entry_id: string;
};

/** @internal */
export const Entry$outboundSchema: z.ZodType<
  Entry$Outbound,
  Entry
> = z.object({
  list: z.string(),
  entryId: z.string(),
}).transform((v) => {
  return remap$(v, {
    entryId: "entry_id",
  });
});

export function entryToJSON(entry: Entry): string {
  return JSON.stringify(Entry$outboundSchema.parse(entry));
}

/** @internal */
export type PostV2CommentsDataPlaintext3$Outbound = {
  format: string;
  content: string;
  author: Author3$Outbound;
  created_at?: string | undefined;
  entry: Entry$Outbound;
};

/** @internal */
export const PostV2CommentsDataPlaintext3$outboundSchema: z.ZodType<
  PostV2CommentsDataPlaintext3$Outbound,
  PostV2CommentsDataPlaintext3
> = z.object({
  format: PostV2CommentsFormat3$outboundSchema,
  content: z.string(),
  author: z.lazy(() => Author3$outboundSchema),
  createdAt: z.string().optional(),
  entry: z.lazy(() => Entry$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function postV2CommentsDataPlaintext3ToJSON(
  postV2CommentsDataPlaintext3: PostV2CommentsDataPlaintext3,
): string {
  return JSON.stringify(
    PostV2CommentsDataPlaintext3$outboundSchema.parse(
      postV2CommentsDataPlaintext3,
    ),
  );
}

/** @internal */
export const PostV2CommentsFormat2$outboundSchema: z.ZodEnum<
  typeof PostV2CommentsFormat2
> = z.nativeEnum(PostV2CommentsFormat2);

/** @internal */
export const PostV2CommentsType2$outboundSchema: z.ZodEnum<
  typeof PostV2CommentsType2
> = z.nativeEnum(PostV2CommentsType2);

/** @internal */
export type Author2$Outbound = {
  type: string;
  id: string;
};

/** @internal */
export const Author2$outboundSchema: z.ZodType<
  Author2$Outbound,
  Author2
> = z.object({
  type: PostV2CommentsType2$outboundSchema,
  id: z.string(),
});

export function author2ToJSON(author2: Author2): string {
  return JSON.stringify(Author2$outboundSchema.parse(author2));
}

/** @internal */
export type RecordT$Outbound = {
  object: string;
  record_id: string;
};

/** @internal */
export const RecordT$outboundSchema: z.ZodType<
  RecordT$Outbound,
  RecordT
> = z.object({
  object: z.string(),
  recordId: z.string(),
}).transform((v) => {
  return remap$(v, {
    recordId: "record_id",
  });
});

export function recordToJSON(recordT: RecordT): string {
  return JSON.stringify(RecordT$outboundSchema.parse(recordT));
}

/** @internal */
export type PostV2CommentsDataPlaintext2$Outbound = {
  format: string;
  content: string;
  author: Author2$Outbound;
  created_at?: string | undefined;
  record: RecordT$Outbound;
};

/** @internal */
export const PostV2CommentsDataPlaintext2$outboundSchema: z.ZodType<
  PostV2CommentsDataPlaintext2$Outbound,
  PostV2CommentsDataPlaintext2
> = z.object({
  format: PostV2CommentsFormat2$outboundSchema,
  content: z.string(),
  author: z.lazy(() => Author2$outboundSchema),
  createdAt: z.string().optional(),
  record: z.lazy(() => RecordT$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

export function postV2CommentsDataPlaintext2ToJSON(
  postV2CommentsDataPlaintext2: PostV2CommentsDataPlaintext2,
): string {
  return JSON.stringify(
    PostV2CommentsDataPlaintext2$outboundSchema.parse(
      postV2CommentsDataPlaintext2,
    ),
  );
}

/** @internal */
export const PostV2CommentsFormat1$outboundSchema: z.ZodEnum<
  typeof PostV2CommentsFormat1
> = z.nativeEnum(PostV2CommentsFormat1);

/** @internal */
export const PostV2CommentsType1$outboundSchema: z.ZodEnum<
  typeof PostV2CommentsType1
> = z.nativeEnum(PostV2CommentsType1);

/** @internal */
export type Author1$Outbound = {
  type: string;
  id: string;
};

/** @internal */
export const Author1$outboundSchema: z.ZodType<
  Author1$Outbound,
  Author1
> = z.object({
  type: PostV2CommentsType1$outboundSchema,
  id: z.string(),
});

export function author1ToJSON(author1: Author1): string {
  return JSON.stringify(Author1$outboundSchema.parse(author1));
}

/** @internal */
export type PostV2CommentsDataPlaintext1$Outbound = {
  format: string;
  content: string;
  author: Author1$Outbound;
  created_at?: string | undefined;
  thread_id: string;
};

/** @internal */
export const PostV2CommentsDataPlaintext1$outboundSchema: z.ZodType<
  PostV2CommentsDataPlaintext1$Outbound,
  PostV2CommentsDataPlaintext1
> = z.object({
  format: PostV2CommentsFormat1$outboundSchema,
  content: z.string(),
  author: z.lazy(() => Author1$outboundSchema),
  createdAt: z.string().optional(),
  threadId: z.string(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
    threadId: "thread_id",
  });
});

export function postV2CommentsDataPlaintext1ToJSON(
  postV2CommentsDataPlaintext1: PostV2CommentsDataPlaintext1,
): string {
  return JSON.stringify(
    PostV2CommentsDataPlaintext1$outboundSchema.parse(
      postV2CommentsDataPlaintext1,
    ),
  );
}

/** @internal */
export type PostV2CommentsDataUnion$Outbound =
  | PostV2CommentsDataPlaintext1$Outbound
  | PostV2CommentsDataPlaintext2$Outbound
  | PostV2CommentsDataPlaintext3$Outbound;

/** @internal */
export const PostV2CommentsDataUnion$outboundSchema: z.ZodType<
  PostV2CommentsDataUnion$Outbound,
  PostV2CommentsDataUnion
> = z.union([
  z.lazy(() => PostV2CommentsDataPlaintext1$outboundSchema),
  z.lazy(() => PostV2CommentsDataPlaintext2$outboundSchema),
  z.lazy(() => PostV2CommentsDataPlaintext3$outboundSchema),
]);

export function postV2CommentsDataUnionToJSON(
  postV2CommentsDataUnion: PostV2CommentsDataUnion,
): string {
  return JSON.stringify(
    PostV2CommentsDataUnion$outboundSchema.parse(postV2CommentsDataUnion),
  );
}

/** @internal */
export type PostV2CommentsRequest$Outbound = {
  data:
    | PostV2CommentsDataPlaintext1$Outbound
    | PostV2CommentsDataPlaintext2$Outbound
    | PostV2CommentsDataPlaintext3$Outbound;
};

/** @internal */
export const PostV2CommentsRequest$outboundSchema: z.ZodType<
  PostV2CommentsRequest$Outbound,
  PostV2CommentsRequest
> = z.object({
  data: z.union([
    z.lazy(() => PostV2CommentsDataPlaintext1$outboundSchema),
    z.lazy(() => PostV2CommentsDataPlaintext2$outboundSchema),
    z.lazy(() => PostV2CommentsDataPlaintext3$outboundSchema),
  ]),
});

export function postV2CommentsRequestToJSON(
  postV2CommentsRequest: PostV2CommentsRequest,
): string {
  return JSON.stringify(
    PostV2CommentsRequest$outboundSchema.parse(postV2CommentsRequest),
  );
}

/** @internal */
export const PostV2CommentsResponse$inboundSchema: z.ZodType<
  PostV2CommentsResponse,
  unknown
> = z.object({
  data: Comment$inboundSchema,
});

export function postV2CommentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2CommentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2CommentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2CommentsResponse' from JSON`,
  );
}
