/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The direction to sort the results by.
 */
export const PostV2ObjectsObjectRecordsQueryDirection2 = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The direction to sort the results by.
 */
export type PostV2ObjectsObjectRecordsQueryDirection2 = ClosedEnum<
  typeof PostV2ObjectsObjectRecordsQueryDirection2
>;

/**
 * Sort by path
 */
export type PostV2ObjectsObjectRecordsQuerySort2 = {
  /**
   * The direction to sort the results by.
   */
  direction: PostV2ObjectsObjectRecordsQueryDirection2;
  /**
   * You may use the `path` property to traverse record reference attributes and parent records on list entries. `path` accepts an array of tuples where the first element of each tuple is the slug or ID of a list/object, and the second element is the slug or ID of an attribute on that list/object. The first element of the first tuple must correspond to the list or object that you are querying. For example, if you wanted to sort by the name of the parent record (a company) on a list with the slug "sales", you would pass the value `[['sales', 'parent_record'], ['companies', 'name']]`.
   */
  path: Array<Array<string>>;
  /**
   * Which field on the value to sort by e.g. "last_name" on a name value.
   */
  field?: string | undefined;
};

/**
 * The direction to sort the results by.
 */
export const PostV2ObjectsObjectRecordsQueryDirection1 = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The direction to sort the results by.
 */
export type PostV2ObjectsObjectRecordsQueryDirection1 = ClosedEnum<
  typeof PostV2ObjectsObjectRecordsQueryDirection1
>;

/**
 * Sort by attribute
 */
export type PostV2ObjectsObjectRecordsQuerySort1 = {
  /**
   * The direction to sort the results by.
   */
  direction: PostV2ObjectsObjectRecordsQueryDirection1;
  /**
   * A slug or ID to identify the attribute to sort by.
   */
  attribute: string;
  /**
   * Which field on the value to sort by e.g. "last_name" on a name value.
   */
  field?: string | undefined;
};

export type PostV2ObjectsObjectRecordsQuerySortUnion =
  | PostV2ObjectsObjectRecordsQuerySort1
  | PostV2ObjectsObjectRecordsQuerySort2;

export type PostV2ObjectsObjectRecordsQueryRequestBody = {
  /**
   * An object used to filter results to a subset of results. See the [full guide to filtering and sorting here](/docs/filtering-and-sorting).
   */
  filter?: { [k: string]: any } | undefined;
  /**
   * An object used to sort results. See the [full guide to filtering and sorting here](/docs/filtering-and-sorting).
   */
  sorts?:
    | Array<
      | PostV2ObjectsObjectRecordsQuerySort1
      | PostV2ObjectsObjectRecordsQuerySort2
    >
    | undefined;
  /**
   * The maximum number of results to return. Defaults to 500. See the [full guide to pagination here](/docs/pagination).
   */
  limit?: number | undefined;
  /**
   * The number of results to skip over before returning. Defaults to 0. See the [full guide to pagination here](/docs/pagination).
   */
  offset?: number | undefined;
};

export type PostV2ObjectsObjectRecordsQueryRequest = {
  object: string;
  requestBody: PostV2ObjectsObjectRecordsQueryRequestBody;
};

export type PostV2ObjectsObjectRecordsQueryId = {
  /**
   * A UUID identifying the workspace this record belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the object this record belongs to.
   */
  objectId: string;
  /**
   * A UUID identifying this record.
   */
  recordId: string;
};

export type PostV2ObjectsObjectRecordsQueryData = {
  id: PostV2ObjectsObjectRecordsQueryId;
  /**
   * When this record was created.
   */
  createdAt: string;
  /**
   * A record type with an attribute `api_slug` as the key, and an array of value objects as the values.
   */
  values: { [k: string]: any };
};

/**
 * Success
 */
export type PostV2ObjectsObjectRecordsQueryResponse = {
  data: Array<PostV2ObjectsObjectRecordsQueryData>;
};

/** @internal */
export const PostV2ObjectsObjectRecordsQueryDirection2$outboundSchema:
  z.ZodEnum<typeof PostV2ObjectsObjectRecordsQueryDirection2> = z
    .nativeEnum(PostV2ObjectsObjectRecordsQueryDirection2);

/** @internal */
export type PostV2ObjectsObjectRecordsQuerySort2$Outbound = {
  direction: string;
  path: Array<Array<string>>;
  field?: string | undefined;
};

/** @internal */
export const PostV2ObjectsObjectRecordsQuerySort2$outboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsQuerySort2$Outbound,
  PostV2ObjectsObjectRecordsQuerySort2
> = z.object({
  direction: PostV2ObjectsObjectRecordsQueryDirection2$outboundSchema,
  path: z.array(z.array(z.string())),
  field: z.string().optional(),
});

export function postV2ObjectsObjectRecordsQuerySort2ToJSON(
  postV2ObjectsObjectRecordsQuerySort2: PostV2ObjectsObjectRecordsQuerySort2,
): string {
  return JSON.stringify(
    PostV2ObjectsObjectRecordsQuerySort2$outboundSchema.parse(
      postV2ObjectsObjectRecordsQuerySort2,
    ),
  );
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryDirection1$outboundSchema:
  z.ZodEnum<typeof PostV2ObjectsObjectRecordsQueryDirection1> = z
    .nativeEnum(PostV2ObjectsObjectRecordsQueryDirection1);

/** @internal */
export type PostV2ObjectsObjectRecordsQuerySort1$Outbound = {
  direction: string;
  attribute: string;
  field?: string | undefined;
};

/** @internal */
export const PostV2ObjectsObjectRecordsQuerySort1$outboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsQuerySort1$Outbound,
  PostV2ObjectsObjectRecordsQuerySort1
> = z.object({
  direction: PostV2ObjectsObjectRecordsQueryDirection1$outboundSchema,
  attribute: z.string(),
  field: z.string().optional(),
});

export function postV2ObjectsObjectRecordsQuerySort1ToJSON(
  postV2ObjectsObjectRecordsQuerySort1: PostV2ObjectsObjectRecordsQuerySort1,
): string {
  return JSON.stringify(
    PostV2ObjectsObjectRecordsQuerySort1$outboundSchema.parse(
      postV2ObjectsObjectRecordsQuerySort1,
    ),
  );
}

/** @internal */
export type PostV2ObjectsObjectRecordsQuerySortUnion$Outbound =
  | PostV2ObjectsObjectRecordsQuerySort1$Outbound
  | PostV2ObjectsObjectRecordsQuerySort2$Outbound;

/** @internal */
export const PostV2ObjectsObjectRecordsQuerySortUnion$outboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsQuerySortUnion$Outbound,
  PostV2ObjectsObjectRecordsQuerySortUnion
> = z.union([
  z.lazy(() => PostV2ObjectsObjectRecordsQuerySort1$outboundSchema),
  z.lazy(() => PostV2ObjectsObjectRecordsQuerySort2$outboundSchema),
]);

export function postV2ObjectsObjectRecordsQuerySortUnionToJSON(
  postV2ObjectsObjectRecordsQuerySortUnion:
    PostV2ObjectsObjectRecordsQuerySortUnion,
): string {
  return JSON.stringify(
    PostV2ObjectsObjectRecordsQuerySortUnion$outboundSchema.parse(
      postV2ObjectsObjectRecordsQuerySortUnion,
    ),
  );
}

/** @internal */
export type PostV2ObjectsObjectRecordsQueryRequestBody$Outbound = {
  filter?: { [k: string]: any } | undefined;
  sorts?:
    | Array<
      | PostV2ObjectsObjectRecordsQuerySort1$Outbound
      | PostV2ObjectsObjectRecordsQuerySort2$Outbound
    >
    | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

/** @internal */
export const PostV2ObjectsObjectRecordsQueryRequestBody$outboundSchema:
  z.ZodType<
    PostV2ObjectsObjectRecordsQueryRequestBody$Outbound,
    PostV2ObjectsObjectRecordsQueryRequestBody
  > = z.object({
    filter: z.record(z.string(), z.any()).optional(),
    sorts: z.array(
      z.union([
        z.lazy(() => PostV2ObjectsObjectRecordsQuerySort1$outboundSchema),
        z.lazy(() => PostV2ObjectsObjectRecordsQuerySort2$outboundSchema),
      ]),
    ).optional(),
    limit: z.number().optional(),
    offset: z.number().optional(),
  });

export function postV2ObjectsObjectRecordsQueryRequestBodyToJSON(
  postV2ObjectsObjectRecordsQueryRequestBody:
    PostV2ObjectsObjectRecordsQueryRequestBody,
): string {
  return JSON.stringify(
    PostV2ObjectsObjectRecordsQueryRequestBody$outboundSchema.parse(
      postV2ObjectsObjectRecordsQueryRequestBody,
    ),
  );
}

/** @internal */
export type PostV2ObjectsObjectRecordsQueryRequest$Outbound = {
  object: string;
  RequestBody: PostV2ObjectsObjectRecordsQueryRequestBody$Outbound;
};

/** @internal */
export const PostV2ObjectsObjectRecordsQueryRequest$outboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsQueryRequest$Outbound,
  PostV2ObjectsObjectRecordsQueryRequest
> = z.object({
  object: z.string(),
  requestBody: z.lazy(() =>
    PostV2ObjectsObjectRecordsQueryRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function postV2ObjectsObjectRecordsQueryRequestToJSON(
  postV2ObjectsObjectRecordsQueryRequest:
    PostV2ObjectsObjectRecordsQueryRequest,
): string {
  return JSON.stringify(
    PostV2ObjectsObjectRecordsQueryRequest$outboundSchema.parse(
      postV2ObjectsObjectRecordsQueryRequest,
    ),
  );
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryId$inboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsQueryId,
  unknown
> = z.object({
  workspace_id: z.string(),
  object_id: z.string(),
  record_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "object_id": "objectId",
    "record_id": "recordId",
  });
});

export function postV2ObjectsObjectRecordsQueryIdFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ObjectsObjectRecordsQueryId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2ObjectsObjectRecordsQueryId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ObjectsObjectRecordsQueryId' from JSON`,
  );
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryData$inboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsQueryData,
  unknown
> = z.object({
  id: z.lazy(() => PostV2ObjectsObjectRecordsQueryId$inboundSchema),
  created_at: z.string(),
  values: z.record(z.string(), z.any()),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});

export function postV2ObjectsObjectRecordsQueryDataFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ObjectsObjectRecordsQueryData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV2ObjectsObjectRecordsQueryData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ObjectsObjectRecordsQueryData' from JSON`,
  );
}

/** @internal */
export const PostV2ObjectsObjectRecordsQueryResponse$inboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsQueryResponse,
  unknown
> = z.object({
  data: z.array(
    z.lazy(() => PostV2ObjectsObjectRecordsQueryData$inboundSchema),
  ),
});

export function postV2ObjectsObjectRecordsQueryResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV2ObjectsObjectRecordsQueryResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV2ObjectsObjectRecordsQueryResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV2ObjectsObjectRecordsQueryResponse' from JSON`,
  );
}
