/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Attribute, Attribute$inboundSchema } from "../components/attribute.js";
import {
  InputValueUnion,
  InputValueUnion$Outbound,
  InputValueUnion$outboundSchema,
} from "../components/inputvalueunion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Whether the attribute is to be created on an object or a list.
 */
export const PostV2TargetIdentifierAttributesTarget = {
  Objects: "objects",
  Lists: "lists",
} as const;
/**
 * Whether the attribute is to be created on an object or a list.
 */
export type PostV2TargetIdentifierAttributesTarget = ClosedEnum<
  typeof PostV2TargetIdentifierAttributesTarget
>;

/**
 * The type of the attribute. This value affects the possible `config` values. Attributes of type "status" are not supported on objects.
 */
export const PostV2TargetIdentifierAttributesTypeEnum = {
  Text: "text",
  Number: "number",
  Checkbox: "checkbox",
  Currency: "currency",
  Date: "date",
  Timestamp: "timestamp",
  Rating: "rating",
  Status: "status",
  Select: "select",
  RecordReference: "record-reference",
  ActorReference: "actor-reference",
  Location: "location",
  Domain: "domain",
  EmailAddress: "email-address",
  PhoneNumber: "phone-number",
} as const;
/**
 * The type of the attribute. This value affects the possible `config` values. Attributes of type "status" are not supported on objects.
 */
export type PostV2TargetIdentifierAttributesTypeEnum = ClosedEnum<
  typeof PostV2TargetIdentifierAttributesTypeEnum
>;

export type PostV2TargetIdentifierAttributesDefaultValueStatic = {
  type: "static";
  template: Array<InputValueUnion>;
};

/**
 * For actor reference attributes, you may pass a dynamic value of `"current-user"`. When creating new records or entries, this will cause the actor reference value to be populated with either the workspace member or API token that created the record/entry.
 */
export const PostV2TargetIdentifierAttributesTemplate = {
  CurrentUser: "current-user",
} as const;
/**
 * For actor reference attributes, you may pass a dynamic value of `"current-user"`. When creating new records or entries, this will cause the actor reference value to be populated with either the workspace member or API token that created the record/entry.
 */
export type PostV2TargetIdentifierAttributesTemplate = ClosedEnum<
  typeof PostV2TargetIdentifierAttributesTemplate
>;

export type PostV2TargetIdentifierAttributesDefaultValueDynamic = {
  type: "dynamic";
  template?: any | undefined;
};

/**
 * The default value for this attribute. Static values are used to directly populate values using their contents. Dynamic values are used to lookup data at the point of creation. For example, you could use a dynamic value to insert a value for the currently logged in user. Which default values are available is dependent on the type of the attribute. Default values are not currently supported on people or company objects.
 */
export type PostV2TargetIdentifierAttributesDefaultValueUnion =
  | PostV2TargetIdentifierAttributesDefaultValueDynamic
  | PostV2TargetIdentifierAttributesDefaultValueStatic;

/**
 * The ISO4217 code representing the currency that values for this attribute should be stored in.
 */
export const PostV2TargetIdentifierAttributesDefaultCurrencyCode = {
  Aud: "AUD",
  Brl: "BRL",
  Bel: "BEL",
  Cad: "CAD",
  Cny: "CNY",
  Cop: "COP",
  Czk: "CZK",
  Dkk: "DKK",
  Eur: "EUR",
  Hkd: "HKD",
  Isk: "ISK",
  Inr: "INR",
  Ils: "ILS",
  Jpy: "JPY",
  Krw: "KRW",
  Myr: "MYR",
  Mxn: "MXN",
  Ntd: "NTD",
  Nzd: "NZD",
  Ngn: "NGN",
  Nok: "NOK",
  Xpf: "XPF",
  Pen: "PEN",
  Php: "PHP",
  Pln: "PLN",
  Gbp: "GBP",
  Sar: "SAR",
  Sgd: "SGD",
  Zar: "ZAR",
  Sek: "SEK",
  Chf: "CHF",
  Aed: "AED",
  Usd: "USD",
} as const;
/**
 * The ISO4217 code representing the currency that values for this attribute should be stored in.
 */
export type PostV2TargetIdentifierAttributesDefaultCurrencyCode = ClosedEnum<
  typeof PostV2TargetIdentifierAttributesDefaultCurrencyCode
>;

/**
 * How the currency should be displayed across the app. "code" will display the ISO currency code e.g. "USD", "name" will display the localized currency name e.g. "British pound", "narrowSymbol" will display "$1" instead of "US$1" and "symbol" will display a localized currency symbol such as "$".
 */
export const PostV2TargetIdentifierAttributesDisplayType = {
  Code: "code",
  Name: "name",
  NarrowSymbol: "narrowSymbol",
  Symbol: "symbol",
} as const;
/**
 * How the currency should be displayed across the app. "code" will display the ISO currency code e.g. "USD", "name" will display the localized currency name e.g. "British pound", "narrowSymbol" will display "$1" instead of "US$1" and "symbol" will display a localized currency symbol such as "$".
 */
export type PostV2TargetIdentifierAttributesDisplayType = ClosedEnum<
  typeof PostV2TargetIdentifierAttributesDisplayType
>;

/**
 * Configuration available for attributes of type "currency".
 */
export type PostV2TargetIdentifierAttributesCurrency = {
  /**
   * The ISO4217 code representing the currency that values for this attribute should be stored in.
   */
  defaultCurrencyCode: PostV2TargetIdentifierAttributesDefaultCurrencyCode;
  /**
   * How the currency should be displayed across the app. "code" will display the ISO currency code e.g. "USD", "name" will display the localized currency name e.g. "British pound", "narrowSymbol" will display "$1" instead of "US$1" and "symbol" will display a localized currency symbol such as "$".
   */
  displayType: PostV2TargetIdentifierAttributesDisplayType;
};

/**
 * Configuration available for attributes of type "record-reference".
 */
export type PostV2TargetIdentifierAttributesRecordReference = {
  /**
   * A list of slugs or UUIDs to indicate which objects records are allowed to belong to. Leave empty to to allow records from all object types.
   */
  allowedObjects: Array<string>;
};

export type PostV2TargetIdentifierAttributesConfig = {
  /**
   * Configuration available for attributes of type "currency".
   */
  currency?: PostV2TargetIdentifierAttributesCurrency | undefined;
  /**
   * Configuration available for attributes of type "record-reference".
   */
  recordReference?: PostV2TargetIdentifierAttributesRecordReference | undefined;
};

export type PostV2TargetIdentifierAttributesData = {
  /**
   * The name of the attribute. The title will be visible across Attio's UI.
   */
  title: string;
  /**
   * A text description for the attribute.
   */
  description: string | null;
  /**
   * A unique, human-readable slug to access the attribute through URLs and API calls. Formatted in snake case.
   */
  apiSlug: string;
  /**
   * The type of the attribute. This value affects the possible `config` values. Attributes of type "status" are not supported on objects.
   */
  type: PostV2TargetIdentifierAttributesTypeEnum;
  /**
   * When `is_required` is `true`, new records/entries must have a value for this attribute. If `false`, values may be `null`. This value does not affect existing data and you do not need to backfill `null` values if changing `is_required` from `false` to `true`.
   */
  isRequired: boolean;
  /**
   * Whether or not new values for this attribute must be unique. Uniqueness restrictions are only applied to new data and do not apply retroactively to previously created data.
   */
  isUnique: boolean;
  /**
   * Whether or not this attribute can have multiple values. Multiselect is only available on some value types.
   */
  isMultiselect: boolean;
  /**
   * The default value for this attribute. Static values are used to directly populate values using their contents. Dynamic values are used to lookup data at the point of creation. For example, you could use a dynamic value to insert a value for the currently logged in user. Which default values are available is dependent on the type of the attribute. Default values are not currently supported on people or company objects.
   */
  defaultValue?:
    | PostV2TargetIdentifierAttributesDefaultValueDynamic
    | PostV2TargetIdentifierAttributesDefaultValueStatic
    | null
    | undefined;
  config: PostV2TargetIdentifierAttributesConfig;
};

export type PostV2TargetIdentifierAttributesRequestBody = {
  data: PostV2TargetIdentifierAttributesData;
};

export type PostV2TargetIdentifierAttributesRequest = {
  /**
   * Whether the attribute is to be created on an object or a list.
   */
  target: PostV2TargetIdentifierAttributesTarget;
  identifier: string;
  requestBody: PostV2TargetIdentifierAttributesRequestBody;
};

/**
 * Success
 */
export type PostV2TargetIdentifierAttributesResponse = {
  data: Attribute;
};

/** @internal */
export const PostV2TargetIdentifierAttributesTarget$outboundSchema:
  z.ZodEnum<typeof PostV2TargetIdentifierAttributesTarget> = z.nativeEnum(
    PostV2TargetIdentifierAttributesTarget,
  );

/** @internal */
export const PostV2TargetIdentifierAttributesTypeEnum$outboundSchema:
  z.ZodEnum<typeof PostV2TargetIdentifierAttributesTypeEnum> = z
    .nativeEnum(PostV2TargetIdentifierAttributesTypeEnum);

/** @internal */
export type PostV2TargetIdentifierAttributesDefaultValueStatic$Outbound = {
  type: "static";
  template: Array<InputValueUnion$Outbound>;
};

/** @internal */
export const PostV2TargetIdentifierAttributesDefaultValueStatic$outboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesDefaultValueStatic$Outbound,
    PostV2TargetIdentifierAttributesDefaultValueStatic
  > = z.object({
    type: z.literal("static"),
    template: z.array(InputValueUnion$outboundSchema),
  });

export function postV2TargetIdentifierAttributesDefaultValueStaticToJSON(
  postV2TargetIdentifierAttributesDefaultValueStatic:
    PostV2TargetIdentifierAttributesDefaultValueStatic,
): string {
  return JSON.stringify(
    PostV2TargetIdentifierAttributesDefaultValueStatic$outboundSchema.parse(
      postV2TargetIdentifierAttributesDefaultValueStatic,
    ),
  );
}

/** @internal */
export const PostV2TargetIdentifierAttributesTemplate$outboundSchema:
  z.ZodEnum<typeof PostV2TargetIdentifierAttributesTemplate> = z
    .nativeEnum(PostV2TargetIdentifierAttributesTemplate);

/** @internal */
export type PostV2TargetIdentifierAttributesDefaultValueDynamic$Outbound = {
  type: "dynamic";
  template?: any | undefined;
};

/** @internal */
export const PostV2TargetIdentifierAttributesDefaultValueDynamic$outboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesDefaultValueDynamic$Outbound,
    PostV2TargetIdentifierAttributesDefaultValueDynamic
  > = z.object({
    type: z.literal("dynamic"),
    template: z.any().optional(),
  });

export function postV2TargetIdentifierAttributesDefaultValueDynamicToJSON(
  postV2TargetIdentifierAttributesDefaultValueDynamic:
    PostV2TargetIdentifierAttributesDefaultValueDynamic,
): string {
  return JSON.stringify(
    PostV2TargetIdentifierAttributesDefaultValueDynamic$outboundSchema.parse(
      postV2TargetIdentifierAttributesDefaultValueDynamic,
    ),
  );
}

/** @internal */
export type PostV2TargetIdentifierAttributesDefaultValueUnion$Outbound =
  | PostV2TargetIdentifierAttributesDefaultValueDynamic$Outbound
  | PostV2TargetIdentifierAttributesDefaultValueStatic$Outbound;

/** @internal */
export const PostV2TargetIdentifierAttributesDefaultValueUnion$outboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesDefaultValueUnion$Outbound,
    PostV2TargetIdentifierAttributesDefaultValueUnion
  > = z.union([
    z.lazy(() =>
      PostV2TargetIdentifierAttributesDefaultValueDynamic$outboundSchema
    ),
    z.lazy(() =>
      PostV2TargetIdentifierAttributesDefaultValueStatic$outboundSchema
    ),
  ]);

export function postV2TargetIdentifierAttributesDefaultValueUnionToJSON(
  postV2TargetIdentifierAttributesDefaultValueUnion:
    PostV2TargetIdentifierAttributesDefaultValueUnion,
): string {
  return JSON.stringify(
    PostV2TargetIdentifierAttributesDefaultValueUnion$outboundSchema.parse(
      postV2TargetIdentifierAttributesDefaultValueUnion,
    ),
  );
}

/** @internal */
export const PostV2TargetIdentifierAttributesDefaultCurrencyCode$outboundSchema:
  z.ZodEnum<typeof PostV2TargetIdentifierAttributesDefaultCurrencyCode> =
    z.nativeEnum(PostV2TargetIdentifierAttributesDefaultCurrencyCode);

/** @internal */
export const PostV2TargetIdentifierAttributesDisplayType$outboundSchema:
  z.ZodEnum<typeof PostV2TargetIdentifierAttributesDisplayType> = z
    .nativeEnum(PostV2TargetIdentifierAttributesDisplayType);

/** @internal */
export type PostV2TargetIdentifierAttributesCurrency$Outbound = {
  default_currency_code: string;
  display_type: string;
};

/** @internal */
export const PostV2TargetIdentifierAttributesCurrency$outboundSchema: z.ZodType<
  PostV2TargetIdentifierAttributesCurrency$Outbound,
  PostV2TargetIdentifierAttributesCurrency
> = z.object({
  defaultCurrencyCode:
    PostV2TargetIdentifierAttributesDefaultCurrencyCode$outboundSchema,
  displayType: PostV2TargetIdentifierAttributesDisplayType$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    defaultCurrencyCode: "default_currency_code",
    displayType: "display_type",
  });
});

export function postV2TargetIdentifierAttributesCurrencyToJSON(
  postV2TargetIdentifierAttributesCurrency:
    PostV2TargetIdentifierAttributesCurrency,
): string {
  return JSON.stringify(
    PostV2TargetIdentifierAttributesCurrency$outboundSchema.parse(
      postV2TargetIdentifierAttributesCurrency,
    ),
  );
}

/** @internal */
export type PostV2TargetIdentifierAttributesRecordReference$Outbound = {
  allowed_objects: Array<string>;
};

/** @internal */
export const PostV2TargetIdentifierAttributesRecordReference$outboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesRecordReference$Outbound,
    PostV2TargetIdentifierAttributesRecordReference
  > = z.object({
    allowedObjects: z.array(z.string()),
  }).transform((v) => {
    return remap$(v, {
      allowedObjects: "allowed_objects",
    });
  });

export function postV2TargetIdentifierAttributesRecordReferenceToJSON(
  postV2TargetIdentifierAttributesRecordReference:
    PostV2TargetIdentifierAttributesRecordReference,
): string {
  return JSON.stringify(
    PostV2TargetIdentifierAttributesRecordReference$outboundSchema.parse(
      postV2TargetIdentifierAttributesRecordReference,
    ),
  );
}

/** @internal */
export type PostV2TargetIdentifierAttributesConfig$Outbound = {
  currency?: PostV2TargetIdentifierAttributesCurrency$Outbound | undefined;
  record_reference?:
    | PostV2TargetIdentifierAttributesRecordReference$Outbound
    | undefined;
};

/** @internal */
export const PostV2TargetIdentifierAttributesConfig$outboundSchema: z.ZodType<
  PostV2TargetIdentifierAttributesConfig$Outbound,
  PostV2TargetIdentifierAttributesConfig
> = z.object({
  currency: z.lazy(() =>
    PostV2TargetIdentifierAttributesCurrency$outboundSchema
  ).optional(),
  recordReference: z.lazy(() =>
    PostV2TargetIdentifierAttributesRecordReference$outboundSchema
  ).optional(),
}).transform((v) => {
  return remap$(v, {
    recordReference: "record_reference",
  });
});

export function postV2TargetIdentifierAttributesConfigToJSON(
  postV2TargetIdentifierAttributesConfig:
    PostV2TargetIdentifierAttributesConfig,
): string {
  return JSON.stringify(
    PostV2TargetIdentifierAttributesConfig$outboundSchema.parse(
      postV2TargetIdentifierAttributesConfig,
    ),
  );
}

/** @internal */
export type PostV2TargetIdentifierAttributesData$Outbound = {
  title: string;
  description: string | null;
  api_slug: string;
  type: string;
  is_required: boolean;
  is_unique: boolean;
  is_multiselect: boolean;
  default_value?:
    | PostV2TargetIdentifierAttributesDefaultValueDynamic$Outbound
    | PostV2TargetIdentifierAttributesDefaultValueStatic$Outbound
    | null
    | undefined;
  config: PostV2TargetIdentifierAttributesConfig$Outbound;
};

/** @internal */
export const PostV2TargetIdentifierAttributesData$outboundSchema: z.ZodType<
  PostV2TargetIdentifierAttributesData$Outbound,
  PostV2TargetIdentifierAttributesData
> = z.object({
  title: z.string(),
  description: z.nullable(z.string()),
  apiSlug: z.string(),
  type: PostV2TargetIdentifierAttributesTypeEnum$outboundSchema,
  isRequired: z.boolean(),
  isUnique: z.boolean(),
  isMultiselect: z.boolean(),
  defaultValue: z.nullable(
    z.union([
      z.lazy(() =>
        PostV2TargetIdentifierAttributesDefaultValueDynamic$outboundSchema
      ),
      z.lazy(() =>
        PostV2TargetIdentifierAttributesDefaultValueStatic$outboundSchema
      ),
    ]),
  ).optional(),
  config: z.lazy(() => PostV2TargetIdentifierAttributesConfig$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    apiSlug: "api_slug",
    isRequired: "is_required",
    isUnique: "is_unique",
    isMultiselect: "is_multiselect",
    defaultValue: "default_value",
  });
});

export function postV2TargetIdentifierAttributesDataToJSON(
  postV2TargetIdentifierAttributesData: PostV2TargetIdentifierAttributesData,
): string {
  return JSON.stringify(
    PostV2TargetIdentifierAttributesData$outboundSchema.parse(
      postV2TargetIdentifierAttributesData,
    ),
  );
}

/** @internal */
export type PostV2TargetIdentifierAttributesRequestBody$Outbound = {
  data: PostV2TargetIdentifierAttributesData$Outbound;
};

/** @internal */
export const PostV2TargetIdentifierAttributesRequestBody$outboundSchema:
  z.ZodType<
    PostV2TargetIdentifierAttributesRequestBody$Outbound,
    PostV2TargetIdentifierAttributesRequestBody
  > = z.object({
    data: z.lazy(() => PostV2TargetIdentifierAttributesData$outboundSchema),
  });

export function postV2TargetIdentifierAttributesRequestBodyToJSON(
  postV2TargetIdentifierAttributesRequestBody:
    PostV2TargetIdentifierAttributesRequestBody,
): string {
  return JSON.stringify(
    PostV2TargetIdentifierAttributesRequestBody$outboundSchema.parse(
      postV2TargetIdentifierAttributesRequestBody,
    ),
  );
}

/** @internal */
export type PostV2TargetIdentifierAttributesRequest$Outbound = {
  target: string;
  identifier: string;
  RequestBody: PostV2TargetIdentifierAttributesRequestBody$Outbound;
};

/** @internal */
export const PostV2TargetIdentifierAttributesRequest$outboundSchema: z.ZodType<
  PostV2TargetIdentifierAttributesRequest$Outbound,
  PostV2TargetIdentifierAttributesRequest
> = z.object({
  target: PostV2TargetIdentifierAttributesTarget$outboundSchema,
  identifier: z.string(),
  requestBody: z.lazy(() =>
    PostV2TargetIdentifierAttributesRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function postV2TargetIdentifierAttributesRequestToJSON(
  postV2TargetIdentifierAttributesRequest:
    PostV2TargetIdentifierAttributesRequest,
): string {
  return JSON.stringify(
    PostV2TargetIdentifierAttributesRequest$outboundSchema.parse(
      postV2TargetIdentifierAttributesRequest,
    ),
  );
}

/** @internal */
export const PostV2TargetIdentifierAttributesResponse$inboundSchema: z.ZodType<
  PostV2TargetIdentifierAttributesResponse,
  unknown
> = z.object({
  data: Attribute$inboundSchema,
});

export function postV2TargetIdentifierAttributesResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PostV2TargetIdentifierAttributesResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PostV2TargetIdentifierAttributesResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PostV2TargetIdentifierAttributesResponse' from JSON`,
  );
}
