/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV2ListsListEntriesDataRequest = {
  /**
   * A UUID identifying the record you want to add to the list. The record will become the 'parent' of the created list entry.
   */
  parentRecordId: string;
  /**
   * A UUID or slug identifying the object that the added parent record belongs to.
   */
  parentObject: string;
  /**
   * An object with an attribute `api_slug` or `attribute_id` as the key, and a single value (for single-select attributes), or an array of values (for single or multi-select attributes) as the values. For complete documentation on values for all attribute types, please see our [attribute type docs](/docs/attribute-types).
   */
  entryValues: { [k: string]: any };
};

export type PostV2ListsListEntriesRequestBody = {
  data: PostV2ListsListEntriesDataRequest;
};

export type PostV2ListsListEntriesRequest = {
  list: string;
  requestBody: PostV2ListsListEntriesRequestBody;
};

export type PostV2ListsListEntriesId = {
  /**
   * A UUID identifying the workspace this entry belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the list this entry is in.
   */
  listId: string;
  /**
   * A UUID identifying this entry.
   */
  entryId: string;
};

/**
 * A list of attribute values for the list entry (not attribute values for its parent record).
 */
export type PostV2ListsListEntriesEntryValues = {};

export type PostV2ListsListEntriesDataResponse = {
  id: PostV2ListsListEntriesId;
  /**
   * A UUID identifying the record that is parent of the list entry.
   */
  parentRecordId: string;
  /**
   * A UUID or slug identifying the object that the parent record belongs to.
   */
  parentObject: string;
  /**
   * When this entry was created.
   */
  createdAt: string;
  /**
   * A list of attribute values for the list entry (not attribute values for its parent record).
   */
  entryValues: PostV2ListsListEntriesEntryValues;
};

/**
 * Success
 */
export type PostV2ListsListEntriesResponse = {
  data: PostV2ListsListEntriesDataResponse;
};

/** @internal */
export type PostV2ListsListEntriesDataRequest$Outbound = {
  parent_record_id: string;
  parent_object: string;
  entry_values: { [k: string]: any };
};

/** @internal */
export const PostV2ListsListEntriesDataRequest$outboundSchema: z.ZodType<
  PostV2ListsListEntriesDataRequest$Outbound,
  PostV2ListsListEntriesDataRequest
> = z.object({
  parentRecordId: z.string(),
  parentObject: z.string(),
  entryValues: z.record(z.string(), z.any()),
}).transform((v) => {
  return remap$(v, {
    parentRecordId: "parent_record_id",
    parentObject: "parent_object",
    entryValues: "entry_values",
  });
});

export function postV2ListsListEntriesDataRequestToJSON(
  postV2ListsListEntriesDataRequest: PostV2ListsListEntriesDataRequest,
): string {
  return JSON.stringify(
    PostV2ListsListEntriesDataRequest$outboundSchema.parse(
      postV2ListsListEntriesDataRequest,
    ),
  );
}

/** @internal */
export type PostV2ListsListEntriesRequestBody$Outbound = {
  data: PostV2ListsListEntriesDataRequest$Outbound;
};

/** @internal */
export const PostV2ListsListEntriesRequestBody$outboundSchema: z.ZodType<
  PostV2ListsListEntriesRequestBody$Outbound,
  PostV2ListsListEntriesRequestBody
> = z.object({
  data: z.lazy(() => PostV2ListsListEntriesDataRequest$outboundSchema),
});

export function postV2ListsListEntriesRequestBodyToJSON(
  postV2ListsListEntriesRequestBody: PostV2ListsListEntriesRequestBody,
): string {
  return JSON.stringify(
    PostV2ListsListEntriesRequestBody$outboundSchema.parse(
      postV2ListsListEntriesRequestBody,
    ),
  );
}

/** @internal */
export type PostV2ListsListEntriesRequest$Outbound = {
  list: string;
  RequestBody: PostV2ListsListEntriesRequestBody$Outbound;
};

/** @internal */
export const PostV2ListsListEntriesRequest$outboundSchema: z.ZodType<
  PostV2ListsListEntriesRequest$Outbound,
  PostV2ListsListEntriesRequest
> = z.object({
  list: z.string(),
  requestBody: z.lazy(() => PostV2ListsListEntriesRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function postV2ListsListEntriesRequestToJSON(
  postV2ListsListEntriesRequest: PostV2ListsListEntriesRequest,
): string {
  return JSON.stringify(
    PostV2ListsListEntriesRequest$outboundSchema.parse(
      postV2ListsListEntriesRequest,
    ),
  );
}

/** @internal */
export const PostV2ListsListEntriesId$inboundSchema: z.ZodType<
  PostV2ListsListEntriesId,
  unknown
> = z.object({
  workspace_id: z.string(),
  list_id: z.string(),
  entry_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "list_id": "listId",
    "entry_id": "entryId",
  });
});

export function postV2ListsListEntriesIdFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ListsListEntriesId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2ListsListEntriesId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ListsListEntriesId' from JSON`,
  );
}

/** @internal */
export const PostV2ListsListEntriesEntryValues$inboundSchema: z.ZodType<
  PostV2ListsListEntriesEntryValues,
  unknown
> = z.object({});

export function postV2ListsListEntriesEntryValuesFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ListsListEntriesEntryValues, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2ListsListEntriesEntryValues$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ListsListEntriesEntryValues' from JSON`,
  );
}

/** @internal */
export const PostV2ListsListEntriesDataResponse$inboundSchema: z.ZodType<
  PostV2ListsListEntriesDataResponse,
  unknown
> = z.object({
  id: z.lazy(() => PostV2ListsListEntriesId$inboundSchema),
  parent_record_id: z.string(),
  parent_object: z.string(),
  created_at: z.string(),
  entry_values: z.lazy(() => PostV2ListsListEntriesEntryValues$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "parent_record_id": "parentRecordId",
    "parent_object": "parentObject",
    "created_at": "createdAt",
    "entry_values": "entryValues",
  });
});

export function postV2ListsListEntriesDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ListsListEntriesDataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV2ListsListEntriesDataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ListsListEntriesDataResponse' from JSON`,
  );
}

/** @internal */
export const PostV2ListsListEntriesResponse$inboundSchema: z.ZodType<
  PostV2ListsListEntriesResponse,
  unknown
> = z.object({
  data: z.lazy(() => PostV2ListsListEntriesDataResponse$inboundSchema),
});

export function postV2ListsListEntriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ListsListEntriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2ListsListEntriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ListsListEntriesResponse' from JSON`,
  );
}
