/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV2ObjectsObjectRecordsDataRequest = {
  /**
   * An object with an attribute `api_slug` or `attribute_id` as the key, and a single value (for single-select attributes), or an array of values (for single or multi-select attributes) as the values. For complete documentation on values for all attribute types, please see our [attribute type docs](/docs/attribute-types).
   */
  values: { [k: string]: any };
};

export type PostV2ObjectsObjectRecordsRequestBody = {
  data: PostV2ObjectsObjectRecordsDataRequest;
};

export type PostV2ObjectsObjectRecordsRequest = {
  object: string;
  requestBody: PostV2ObjectsObjectRecordsRequestBody;
};

export type PostV2ObjectsObjectRecordsId = {
  /**
   * A UUID identifying the workspace this record belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the object this record belongs to.
   */
  objectId: string;
  /**
   * A UUID identifying this record.
   */
  recordId: string;
};

export type PostV2ObjectsObjectRecordsDataResponse = {
  id: PostV2ObjectsObjectRecordsId;
  /**
   * When this record was created.
   */
  createdAt: string;
  /**
   * A record type with an attribute `api_slug` as the key, and an array of value objects as the values.
   */
  values: { [k: string]: any };
};

/**
 * Success
 */
export type PostV2ObjectsObjectRecordsResponse = {
  data: PostV2ObjectsObjectRecordsDataResponse;
};

/** @internal */
export type PostV2ObjectsObjectRecordsDataRequest$Outbound = {
  values: { [k: string]: any };
};

/** @internal */
export const PostV2ObjectsObjectRecordsDataRequest$outboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsDataRequest$Outbound,
  PostV2ObjectsObjectRecordsDataRequest
> = z.object({
  values: z.record(z.string(), z.any()),
});

export function postV2ObjectsObjectRecordsDataRequestToJSON(
  postV2ObjectsObjectRecordsDataRequest: PostV2ObjectsObjectRecordsDataRequest,
): string {
  return JSON.stringify(
    PostV2ObjectsObjectRecordsDataRequest$outboundSchema.parse(
      postV2ObjectsObjectRecordsDataRequest,
    ),
  );
}

/** @internal */
export type PostV2ObjectsObjectRecordsRequestBody$Outbound = {
  data: PostV2ObjectsObjectRecordsDataRequest$Outbound;
};

/** @internal */
export const PostV2ObjectsObjectRecordsRequestBody$outboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsRequestBody$Outbound,
  PostV2ObjectsObjectRecordsRequestBody
> = z.object({
  data: z.lazy(() => PostV2ObjectsObjectRecordsDataRequest$outboundSchema),
});

export function postV2ObjectsObjectRecordsRequestBodyToJSON(
  postV2ObjectsObjectRecordsRequestBody: PostV2ObjectsObjectRecordsRequestBody,
): string {
  return JSON.stringify(
    PostV2ObjectsObjectRecordsRequestBody$outboundSchema.parse(
      postV2ObjectsObjectRecordsRequestBody,
    ),
  );
}

/** @internal */
export type PostV2ObjectsObjectRecordsRequest$Outbound = {
  object: string;
  RequestBody: PostV2ObjectsObjectRecordsRequestBody$Outbound;
};

/** @internal */
export const PostV2ObjectsObjectRecordsRequest$outboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsRequest$Outbound,
  PostV2ObjectsObjectRecordsRequest
> = z.object({
  object: z.string(),
  requestBody: z.lazy(() =>
    PostV2ObjectsObjectRecordsRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function postV2ObjectsObjectRecordsRequestToJSON(
  postV2ObjectsObjectRecordsRequest: PostV2ObjectsObjectRecordsRequest,
): string {
  return JSON.stringify(
    PostV2ObjectsObjectRecordsRequest$outboundSchema.parse(
      postV2ObjectsObjectRecordsRequest,
    ),
  );
}

/** @internal */
export const PostV2ObjectsObjectRecordsId$inboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsId,
  unknown
> = z.object({
  workspace_id: z.string(),
  object_id: z.string(),
  record_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "object_id": "objectId",
    "record_id": "recordId",
  });
});

export function postV2ObjectsObjectRecordsIdFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ObjectsObjectRecordsId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2ObjectsObjectRecordsId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ObjectsObjectRecordsId' from JSON`,
  );
}

/** @internal */
export const PostV2ObjectsObjectRecordsDataResponse$inboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsDataResponse,
  unknown
> = z.object({
  id: z.lazy(() => PostV2ObjectsObjectRecordsId$inboundSchema),
  created_at: z.string(),
  values: z.record(z.string(), z.any()),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});

export function postV2ObjectsObjectRecordsDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ObjectsObjectRecordsDataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV2ObjectsObjectRecordsDataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ObjectsObjectRecordsDataResponse' from JSON`,
  );
}

/** @internal */
export const PostV2ObjectsObjectRecordsResponse$inboundSchema: z.ZodType<
  PostV2ObjectsObjectRecordsResponse,
  unknown
> = z.object({
  data: z.lazy(() => PostV2ObjectsObjectRecordsDataResponse$inboundSchema),
});

export function postV2ObjectsObjectRecordsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ObjectsObjectRecordsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostV2ObjectsObjectRecordsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ObjectsObjectRecordsResponse' from JSON`,
  );
}
