/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { ObjectT, ObjectT$inboundSchema } from "../components/object.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostV2ObjectsData = {
  /**
   * A unique, human-readable slug to access the object through URLs and API calls. Should be formatted in snake case.
   */
  apiSlug: string;
  /**
   * The singular form of the object's name.
   */
  singularNoun: string;
  /**
   * The plural form of the object's name.
   */
  pluralNoun: string;
};

export type PostV2ObjectsRequest = {
  data: PostV2ObjectsData;
};

/**
 * Success
 */
export type PostV2ObjectsResponse = {
  data: ObjectT;
};

/** @internal */
export type PostV2ObjectsData$Outbound = {
  api_slug: string;
  singular_noun: string;
  plural_noun: string;
};

/** @internal */
export const PostV2ObjectsData$outboundSchema: z.ZodType<
  PostV2ObjectsData$Outbound,
  PostV2ObjectsData
> = z.object({
  apiSlug: z.string(),
  singularNoun: z.string(),
  pluralNoun: z.string(),
}).transform((v) => {
  return remap$(v, {
    apiSlug: "api_slug",
    singularNoun: "singular_noun",
    pluralNoun: "plural_noun",
  });
});

export function postV2ObjectsDataToJSON(
  postV2ObjectsData: PostV2ObjectsData,
): string {
  return JSON.stringify(
    PostV2ObjectsData$outboundSchema.parse(postV2ObjectsData),
  );
}

/** @internal */
export type PostV2ObjectsRequest$Outbound = {
  data: PostV2ObjectsData$Outbound;
};

/** @internal */
export const PostV2ObjectsRequest$outboundSchema: z.ZodType<
  PostV2ObjectsRequest$Outbound,
  PostV2ObjectsRequest
> = z.object({
  data: z.lazy(() => PostV2ObjectsData$outboundSchema),
});

export function postV2ObjectsRequestToJSON(
  postV2ObjectsRequest: PostV2ObjectsRequest,
): string {
  return JSON.stringify(
    PostV2ObjectsRequest$outboundSchema.parse(postV2ObjectsRequest),
  );
}

/** @internal */
export const PostV2ObjectsResponse$inboundSchema: z.ZodType<
  PostV2ObjectsResponse,
  unknown
> = z.object({
  data: ObjectT$inboundSchema,
});

export function postV2ObjectsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2ObjectsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2ObjectsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2ObjectsResponse' from JSON`,
  );
}
