/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { Note, Note$inboundSchema } from "../components/note.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The format of the note content to be created. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. The `markdown` format supports rich text formatting, and links.
 */
export const PostV2NotesFormat = {
  Plaintext: "plaintext",
  Markdown: "markdown",
} as const;
/**
 * The format of the note content to be created. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. The `markdown` format supports rich text formatting, and links.
 */
export type PostV2NotesFormat = ClosedEnum<typeof PostV2NotesFormat>;

export type PostV2NotesData = {
  /**
   * The ID or slug of the parent object the note belongs to.
   */
  parentObject: string;
  /**
   * The ID of the parent record the note belongs to.
   */
  parentRecordId: string;
  /**
   * The note title. The title is plaintext only and has no formatting.
   */
  title: string;
  /**
   * The format of the note content to be created. The `plaintext` format uses the line feed character `\n` to create new lines within the note content. The `markdown` format supports rich text formatting, and links.
   */
  format: PostV2NotesFormat;
  /**
   * The representation of the note content in the specified format.
   */
  content: string;
  /**
   * `created_at` will default to the current time. However, if you wish to backdate a note for migration or other purposes, you can override with a custom `created_at` value. Note that dates before 1970 or in the future are not allowed.
   */
  createdAt?: string | undefined;
};

export type PostV2NotesRequest = {
  data: PostV2NotesData;
};

/**
 * Success
 */
export type PostV2NotesResponse = {
  data: Note;
};

/** @internal */
export const PostV2NotesFormat$outboundSchema: z.ZodEnum<
  typeof PostV2NotesFormat
> = z.nativeEnum(PostV2NotesFormat);

/** @internal */
export type PostV2NotesData$Outbound = {
  parent_object: string;
  parent_record_id: string;
  title: string;
  format: string;
  content: string;
  created_at?: string | undefined;
};

/** @internal */
export const PostV2NotesData$outboundSchema: z.ZodType<
  PostV2NotesData$Outbound,
  PostV2NotesData
> = z.object({
  parentObject: z.string(),
  parentRecordId: z.string(),
  title: z.string(),
  format: PostV2NotesFormat$outboundSchema,
  content: z.string(),
  createdAt: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    parentObject: "parent_object",
    parentRecordId: "parent_record_id",
    createdAt: "created_at",
  });
});

export function postV2NotesDataToJSON(
  postV2NotesData: PostV2NotesData,
): string {
  return JSON.stringify(PostV2NotesData$outboundSchema.parse(postV2NotesData));
}

/** @internal */
export type PostV2NotesRequest$Outbound = {
  data: PostV2NotesData$Outbound;
};

/** @internal */
export const PostV2NotesRequest$outboundSchema: z.ZodType<
  PostV2NotesRequest$Outbound,
  PostV2NotesRequest
> = z.object({
  data: z.lazy(() => PostV2NotesData$outboundSchema),
});

export function postV2NotesRequestToJSON(
  postV2NotesRequest: PostV2NotesRequest,
): string {
  return JSON.stringify(
    PostV2NotesRequest$outboundSchema.parse(postV2NotesRequest),
  );
}

/** @internal */
export const PostV2NotesResponse$inboundSchema: z.ZodType<
  PostV2NotesResponse,
  unknown
> = z.object({
  data: Note$inboundSchema,
});

export function postV2NotesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostV2NotesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostV2NotesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostV2NotesResponse' from JSON`,
  );
}
