/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PutV2ObjectsObjectRecordsDataRequest = {
  /**
   * An object with an attribute `api_slug` or `attribute_id` as the key, and a single value (for single-select attributes), or an array of values (for single or multi-select attributes) as the values. For complete documentation on values for all attribute types, please see our [attribute type docs](/docs/attribute-types).
   */
  values: { [k: string]: any };
};

export type PutV2ObjectsObjectRecordsRequestBody = {
  data: PutV2ObjectsObjectRecordsDataRequest;
};

export type PutV2ObjectsObjectRecordsRequest = {
  object: string;
  matchingAttribute: string;
  requestBody: PutV2ObjectsObjectRecordsRequestBody;
};

export type PutV2ObjectsObjectRecordsId = {
  /**
   * A UUID identifying the workspace this record belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the object this record belongs to.
   */
  objectId: string;
  /**
   * A UUID identifying this record.
   */
  recordId: string;
};

export type PutV2ObjectsObjectRecordsDataResponse = {
  id: PutV2ObjectsObjectRecordsId;
  /**
   * When this record was created.
   */
  createdAt: string;
  /**
   * A record type with an attribute `api_slug` as the key, and an array of value objects as the values.
   */
  values: { [k: string]: any };
};

/**
 * Success
 */
export type PutV2ObjectsObjectRecordsResponse = {
  data: PutV2ObjectsObjectRecordsDataResponse;
};

/** @internal */
export type PutV2ObjectsObjectRecordsDataRequest$Outbound = {
  values: { [k: string]: any };
};

/** @internal */
export const PutV2ObjectsObjectRecordsDataRequest$outboundSchema: z.ZodType<
  PutV2ObjectsObjectRecordsDataRequest$Outbound,
  PutV2ObjectsObjectRecordsDataRequest
> = z.object({
  values: z.record(z.string(), z.any()),
});

export function putV2ObjectsObjectRecordsDataRequestToJSON(
  putV2ObjectsObjectRecordsDataRequest: PutV2ObjectsObjectRecordsDataRequest,
): string {
  return JSON.stringify(
    PutV2ObjectsObjectRecordsDataRequest$outboundSchema.parse(
      putV2ObjectsObjectRecordsDataRequest,
    ),
  );
}

/** @internal */
export type PutV2ObjectsObjectRecordsRequestBody$Outbound = {
  data: PutV2ObjectsObjectRecordsDataRequest$Outbound;
};

/** @internal */
export const PutV2ObjectsObjectRecordsRequestBody$outboundSchema: z.ZodType<
  PutV2ObjectsObjectRecordsRequestBody$Outbound,
  PutV2ObjectsObjectRecordsRequestBody
> = z.object({
  data: z.lazy(() => PutV2ObjectsObjectRecordsDataRequest$outboundSchema),
});

export function putV2ObjectsObjectRecordsRequestBodyToJSON(
  putV2ObjectsObjectRecordsRequestBody: PutV2ObjectsObjectRecordsRequestBody,
): string {
  return JSON.stringify(
    PutV2ObjectsObjectRecordsRequestBody$outboundSchema.parse(
      putV2ObjectsObjectRecordsRequestBody,
    ),
  );
}

/** @internal */
export type PutV2ObjectsObjectRecordsRequest$Outbound = {
  object: string;
  matching_attribute: string;
  RequestBody: PutV2ObjectsObjectRecordsRequestBody$Outbound;
};

/** @internal */
export const PutV2ObjectsObjectRecordsRequest$outboundSchema: z.ZodType<
  PutV2ObjectsObjectRecordsRequest$Outbound,
  PutV2ObjectsObjectRecordsRequest
> = z.object({
  object: z.string(),
  matchingAttribute: z.string(),
  requestBody: z.lazy(() =>
    PutV2ObjectsObjectRecordsRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    matchingAttribute: "matching_attribute",
    requestBody: "RequestBody",
  });
});

export function putV2ObjectsObjectRecordsRequestToJSON(
  putV2ObjectsObjectRecordsRequest: PutV2ObjectsObjectRecordsRequest,
): string {
  return JSON.stringify(
    PutV2ObjectsObjectRecordsRequest$outboundSchema.parse(
      putV2ObjectsObjectRecordsRequest,
    ),
  );
}

/** @internal */
export const PutV2ObjectsObjectRecordsId$inboundSchema: z.ZodType<
  PutV2ObjectsObjectRecordsId,
  unknown
> = z.object({
  workspace_id: z.string(),
  object_id: z.string(),
  record_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "object_id": "objectId",
    "record_id": "recordId",
  });
});

export function putV2ObjectsObjectRecordsIdFromJSON(
  jsonString: string,
): SafeParseResult<PutV2ObjectsObjectRecordsId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV2ObjectsObjectRecordsId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV2ObjectsObjectRecordsId' from JSON`,
  );
}

/** @internal */
export const PutV2ObjectsObjectRecordsDataResponse$inboundSchema: z.ZodType<
  PutV2ObjectsObjectRecordsDataResponse,
  unknown
> = z.object({
  id: z.lazy(() => PutV2ObjectsObjectRecordsId$inboundSchema),
  created_at: z.string(),
  values: z.record(z.string(), z.any()),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});

export function putV2ObjectsObjectRecordsDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<PutV2ObjectsObjectRecordsDataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PutV2ObjectsObjectRecordsDataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV2ObjectsObjectRecordsDataResponse' from JSON`,
  );
}

/** @internal */
export const PutV2ObjectsObjectRecordsResponse$inboundSchema: z.ZodType<
  PutV2ObjectsObjectRecordsResponse,
  unknown
> = z.object({
  data: z.lazy(() => PutV2ObjectsObjectRecordsDataResponse$inboundSchema),
});

export function putV2ObjectsObjectRecordsResponseFromJSON(
  jsonString: string,
): SafeParseResult<PutV2ObjectsObjectRecordsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV2ObjectsObjectRecordsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV2ObjectsObjectRecordsResponse' from JSON`,
  );
}
