/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PutV2ListsListEntriesDataRequest = {
  /**
   * A UUID identifying the record you want to add to the list. The record will become the 'parent' of the created list entry.
   */
  parentRecordId: string;
  /**
   * A UUID or slug identifying the object that the added parent record belongs to.
   */
  parentObject: string;
  /**
   * An object with an attribute `api_slug` or `attribute_id` as the key, and a single value (for single-select attributes), or an array of values (for single or multi-select attributes) as the values. For complete documentation on values for all attribute types, please see our [attribute type docs](/docs/attribute-types).
   */
  entryValues: { [k: string]: any };
};

export type PutV2ListsListEntriesRequestBody = {
  data: PutV2ListsListEntriesDataRequest;
};

export type PutV2ListsListEntriesRequest = {
  list: string;
  requestBody: PutV2ListsListEntriesRequestBody;
};

export type PutV2ListsListEntriesId = {
  /**
   * A UUID identifying the workspace this entry belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the list this entry is in.
   */
  listId: string;
  /**
   * A UUID identifying this entry.
   */
  entryId: string;
};

/**
 * A list of attribute values for the list entry (not attribute values for its parent record).
 */
export type PutV2ListsListEntriesEntryValues = {};

export type PutV2ListsListEntriesDataResponse = {
  id: PutV2ListsListEntriesId;
  /**
   * A UUID identifying the record that is parent of the list entry.
   */
  parentRecordId: string;
  /**
   * A UUID or slug identifying the object that the parent record belongs to.
   */
  parentObject: string;
  /**
   * When this entry was created.
   */
  createdAt: string;
  /**
   * A list of attribute values for the list entry (not attribute values for its parent record).
   */
  entryValues: PutV2ListsListEntriesEntryValues;
};

/**
 * Success
 */
export type PutV2ListsListEntriesResponse = {
  data: PutV2ListsListEntriesDataResponse;
};

/** @internal */
export type PutV2ListsListEntriesDataRequest$Outbound = {
  parent_record_id: string;
  parent_object: string;
  entry_values: { [k: string]: any };
};

/** @internal */
export const PutV2ListsListEntriesDataRequest$outboundSchema: z.ZodType<
  PutV2ListsListEntriesDataRequest$Outbound,
  PutV2ListsListEntriesDataRequest
> = z.object({
  parentRecordId: z.string(),
  parentObject: z.string(),
  entryValues: z.record(z.string(), z.any()),
}).transform((v) => {
  return remap$(v, {
    parentRecordId: "parent_record_id",
    parentObject: "parent_object",
    entryValues: "entry_values",
  });
});

export function putV2ListsListEntriesDataRequestToJSON(
  putV2ListsListEntriesDataRequest: PutV2ListsListEntriesDataRequest,
): string {
  return JSON.stringify(
    PutV2ListsListEntriesDataRequest$outboundSchema.parse(
      putV2ListsListEntriesDataRequest,
    ),
  );
}

/** @internal */
export type PutV2ListsListEntriesRequestBody$Outbound = {
  data: PutV2ListsListEntriesDataRequest$Outbound;
};

/** @internal */
export const PutV2ListsListEntriesRequestBody$outboundSchema: z.ZodType<
  PutV2ListsListEntriesRequestBody$Outbound,
  PutV2ListsListEntriesRequestBody
> = z.object({
  data: z.lazy(() => PutV2ListsListEntriesDataRequest$outboundSchema),
});

export function putV2ListsListEntriesRequestBodyToJSON(
  putV2ListsListEntriesRequestBody: PutV2ListsListEntriesRequestBody,
): string {
  return JSON.stringify(
    PutV2ListsListEntriesRequestBody$outboundSchema.parse(
      putV2ListsListEntriesRequestBody,
    ),
  );
}

/** @internal */
export type PutV2ListsListEntriesRequest$Outbound = {
  list: string;
  RequestBody: PutV2ListsListEntriesRequestBody$Outbound;
};

/** @internal */
export const PutV2ListsListEntriesRequest$outboundSchema: z.ZodType<
  PutV2ListsListEntriesRequest$Outbound,
  PutV2ListsListEntriesRequest
> = z.object({
  list: z.string(),
  requestBody: z.lazy(() => PutV2ListsListEntriesRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function putV2ListsListEntriesRequestToJSON(
  putV2ListsListEntriesRequest: PutV2ListsListEntriesRequest,
): string {
  return JSON.stringify(
    PutV2ListsListEntriesRequest$outboundSchema.parse(
      putV2ListsListEntriesRequest,
    ),
  );
}

/** @internal */
export const PutV2ListsListEntriesId$inboundSchema: z.ZodType<
  PutV2ListsListEntriesId,
  unknown
> = z.object({
  workspace_id: z.string(),
  list_id: z.string(),
  entry_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "list_id": "listId",
    "entry_id": "entryId",
  });
});

export function putV2ListsListEntriesIdFromJSON(
  jsonString: string,
): SafeParseResult<PutV2ListsListEntriesId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV2ListsListEntriesId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV2ListsListEntriesId' from JSON`,
  );
}

/** @internal */
export const PutV2ListsListEntriesEntryValues$inboundSchema: z.ZodType<
  PutV2ListsListEntriesEntryValues,
  unknown
> = z.object({});

export function putV2ListsListEntriesEntryValuesFromJSON(
  jsonString: string,
): SafeParseResult<PutV2ListsListEntriesEntryValues, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV2ListsListEntriesEntryValues$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV2ListsListEntriesEntryValues' from JSON`,
  );
}

/** @internal */
export const PutV2ListsListEntriesDataResponse$inboundSchema: z.ZodType<
  PutV2ListsListEntriesDataResponse,
  unknown
> = z.object({
  id: z.lazy(() => PutV2ListsListEntriesId$inboundSchema),
  parent_record_id: z.string(),
  parent_object: z.string(),
  created_at: z.string(),
  entry_values: z.lazy(() => PutV2ListsListEntriesEntryValues$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "parent_record_id": "parentRecordId",
    "parent_object": "parentObject",
    "created_at": "createdAt",
    "entry_values": "entryValues",
  });
});

export function putV2ListsListEntriesDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<PutV2ListsListEntriesDataResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV2ListsListEntriesDataResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV2ListsListEntriesDataResponse' from JSON`,
  );
}

/** @internal */
export const PutV2ListsListEntriesResponse$inboundSchema: z.ZodType<
  PutV2ListsListEntriesResponse,
  unknown
> = z.object({
  data: z.lazy(() => PutV2ListsListEntriesDataResponse$inboundSchema),
});

export function putV2ListsListEntriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<PutV2ListsListEntriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PutV2ListsListEntriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV2ListsListEntriesResponse' from JSON`,
  );
}
