/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PutV2ObjectsObjectRecordsRecordIdDataRequest = {
  /**
   * An object with an attribute `api_slug` or `attribute_id` as the key, and a single value (for single-select attributes), or an array of values (for single or multi-select attributes) as the values. For complete documentation on values for all attribute types, please see our [attribute type docs](/docs/attribute-types).
   */
  values: { [k: string]: any };
};

export type PutV2ObjectsObjectRecordsRecordIdRequestBody = {
  data: PutV2ObjectsObjectRecordsRecordIdDataRequest;
};

export type PutV2ObjectsObjectRecordsRecordIdRequest = {
  object: string;
  recordId: string;
  requestBody: PutV2ObjectsObjectRecordsRecordIdRequestBody;
};

export type PutV2ObjectsObjectRecordsRecordIdId = {
  /**
   * A UUID identifying the workspace this record belongs to.
   */
  workspaceId: string;
  /**
   * A UUID identifying the object this record belongs to.
   */
  objectId: string;
  /**
   * A UUID identifying this record.
   */
  recordId: string;
};

export type PutV2ObjectsObjectRecordsRecordIdDataResponse = {
  id: PutV2ObjectsObjectRecordsRecordIdId;
  /**
   * When this record was created.
   */
  createdAt: string;
  /**
   * A record type with an attribute `api_slug` as the key, and an array of value objects as the values.
   */
  values: { [k: string]: any };
};

/**
 * Success
 */
export type PutV2ObjectsObjectRecordsRecordIdResponse = {
  data: PutV2ObjectsObjectRecordsRecordIdDataResponse;
};

/** @internal */
export type PutV2ObjectsObjectRecordsRecordIdDataRequest$Outbound = {
  values: { [k: string]: any };
};

/** @internal */
export const PutV2ObjectsObjectRecordsRecordIdDataRequest$outboundSchema:
  z.ZodType<
    PutV2ObjectsObjectRecordsRecordIdDataRequest$Outbound,
    PutV2ObjectsObjectRecordsRecordIdDataRequest
  > = z.object({
    values: z.record(z.string(), z.any()),
  });

export function putV2ObjectsObjectRecordsRecordIdDataRequestToJSON(
  putV2ObjectsObjectRecordsRecordIdDataRequest:
    PutV2ObjectsObjectRecordsRecordIdDataRequest,
): string {
  return JSON.stringify(
    PutV2ObjectsObjectRecordsRecordIdDataRequest$outboundSchema.parse(
      putV2ObjectsObjectRecordsRecordIdDataRequest,
    ),
  );
}

/** @internal */
export type PutV2ObjectsObjectRecordsRecordIdRequestBody$Outbound = {
  data: PutV2ObjectsObjectRecordsRecordIdDataRequest$Outbound;
};

/** @internal */
export const PutV2ObjectsObjectRecordsRecordIdRequestBody$outboundSchema:
  z.ZodType<
    PutV2ObjectsObjectRecordsRecordIdRequestBody$Outbound,
    PutV2ObjectsObjectRecordsRecordIdRequestBody
  > = z.object({
    data: z.lazy(() =>
      PutV2ObjectsObjectRecordsRecordIdDataRequest$outboundSchema
    ),
  });

export function putV2ObjectsObjectRecordsRecordIdRequestBodyToJSON(
  putV2ObjectsObjectRecordsRecordIdRequestBody:
    PutV2ObjectsObjectRecordsRecordIdRequestBody,
): string {
  return JSON.stringify(
    PutV2ObjectsObjectRecordsRecordIdRequestBody$outboundSchema.parse(
      putV2ObjectsObjectRecordsRecordIdRequestBody,
    ),
  );
}

/** @internal */
export type PutV2ObjectsObjectRecordsRecordIdRequest$Outbound = {
  object: string;
  record_id: string;
  RequestBody: PutV2ObjectsObjectRecordsRecordIdRequestBody$Outbound;
};

/** @internal */
export const PutV2ObjectsObjectRecordsRecordIdRequest$outboundSchema: z.ZodType<
  PutV2ObjectsObjectRecordsRecordIdRequest$Outbound,
  PutV2ObjectsObjectRecordsRecordIdRequest
> = z.object({
  object: z.string(),
  recordId: z.string(),
  requestBody: z.lazy(() =>
    PutV2ObjectsObjectRecordsRecordIdRequestBody$outboundSchema
  ),
}).transform((v) => {
  return remap$(v, {
    recordId: "record_id",
    requestBody: "RequestBody",
  });
});

export function putV2ObjectsObjectRecordsRecordIdRequestToJSON(
  putV2ObjectsObjectRecordsRecordIdRequest:
    PutV2ObjectsObjectRecordsRecordIdRequest,
): string {
  return JSON.stringify(
    PutV2ObjectsObjectRecordsRecordIdRequest$outboundSchema.parse(
      putV2ObjectsObjectRecordsRecordIdRequest,
    ),
  );
}

/** @internal */
export const PutV2ObjectsObjectRecordsRecordIdId$inboundSchema: z.ZodType<
  PutV2ObjectsObjectRecordsRecordIdId,
  unknown
> = z.object({
  workspace_id: z.string(),
  object_id: z.string(),
  record_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "object_id": "objectId",
    "record_id": "recordId",
  });
});

export function putV2ObjectsObjectRecordsRecordIdIdFromJSON(
  jsonString: string,
): SafeParseResult<PutV2ObjectsObjectRecordsRecordIdId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PutV2ObjectsObjectRecordsRecordIdId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PutV2ObjectsObjectRecordsRecordIdId' from JSON`,
  );
}

/** @internal */
export const PutV2ObjectsObjectRecordsRecordIdDataResponse$inboundSchema:
  z.ZodType<
    PutV2ObjectsObjectRecordsRecordIdDataResponse,
    unknown
  > = z.object({
    id: z.lazy(() => PutV2ObjectsObjectRecordsRecordIdId$inboundSchema),
    created_at: z.string(),
    values: z.record(z.string(), z.any()),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  });

export function putV2ObjectsObjectRecordsRecordIdDataResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PutV2ObjectsObjectRecordsRecordIdDataResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutV2ObjectsObjectRecordsRecordIdDataResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PutV2ObjectsObjectRecordsRecordIdDataResponse' from JSON`,
  );
}

/** @internal */
export const PutV2ObjectsObjectRecordsRecordIdResponse$inboundSchema: z.ZodType<
  PutV2ObjectsObjectRecordsRecordIdResponse,
  unknown
> = z.object({
  data: z.lazy(() =>
    PutV2ObjectsObjectRecordsRecordIdDataResponse$inboundSchema
  ),
});

export function putV2ObjectsObjectRecordsRecordIdResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  PutV2ObjectsObjectRecordsRecordIdResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      PutV2ObjectsObjectRecordsRecordIdResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'PutV2ObjectsObjectRecordsRecordIdResponse' from JSON`,
  );
}
