/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CommentId = {
  /**
   * The ID of the workspace the comment belongs to.
   */
  workspaceId: string;
  /**
   * The ID of the comment.
   */
  commentId: string;
};

/**
 * The entry the comment belongs to, `null` for comments on records.
 */
export type Entry = {
  /**
   * The ID of the entry the comment belongs to.
   */
  entryId: string;
  /**
   * The ID of the list the entry belongs to.
   */
  listId: string;
};

/**
 * The record the comment belongs to.
 */
export type RecordT = {
  /**
   * The ID of the record the comment belongs to.
   */
  recordId: string;
  /**
   * The ID of the object the record belongs to.
   */
  objectId: string;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const ResolvedByType = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type ResolvedByType = ClosedEnum<typeof ResolvedByType>;

/**
 * The actor that resolved this comment.
 */
export type ResolvedBy = {
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: ResolvedByType | null | undefined;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const AuthorType = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type AuthorType = ClosedEnum<typeof AuthorType>;

/**
 * Who wrote this comment. Note that the API provides the ability for API tokens to write comments on behalf of other actors.
 */
export type Author = {
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: AuthorType | null | undefined;
};

export type Comment = {
  id: CommentId;
  /**
   * The ID of the thread the comment belongs to.
   */
  threadId: string;
  /**
   * A plaintext representation of the content of the comment. References to workspace members are cast into email addresses, all other stylistic elements are removed.
   */
  contentPlaintext: string;
  /**
   * The entry the comment belongs to, `null` for comments on records.
   */
  entry: Entry | null;
  /**
   * The record the comment belongs to.
   */
  record: RecordT;
  /**
   * Whether the comment is resolved.
   */
  resolvedAt: string | null;
  /**
   * The actor that resolved this comment.
   */
  resolvedBy: ResolvedBy;
  /**
   * When the note was created.
   */
  createdAt: string;
  /**
   * Who wrote this comment. Note that the API provides the ability for API tokens to write comments on behalf of other actors.
   */
  author: Author;
};

/** @internal */
export const CommentId$inboundSchema: z.ZodType<
  CommentId,
  unknown
> = z.object({
  workspace_id: z.string(),
  comment_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "comment_id": "commentId",
  });
});

export function commentIdFromJSON(
  jsonString: string,
): SafeParseResult<CommentId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CommentId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CommentId' from JSON`,
  );
}

/** @internal */
export const Entry$inboundSchema: z.ZodType<Entry, unknown> = z
  .object({
    entry_id: z.string(),
    list_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "entry_id": "entryId",
      "list_id": "listId",
    });
  });

export function entryFromJSON(
  jsonString: string,
): SafeParseResult<Entry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Entry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Entry' from JSON`,
  );
}

/** @internal */
export const RecordT$inboundSchema: z.ZodType<RecordT, unknown> =
  z.object({
    record_id: z.string(),
    object_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "record_id": "recordId",
      "object_id": "objectId",
    });
  });

export function recordFromJSON(
  jsonString: string,
): SafeParseResult<RecordT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RecordT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RecordT' from JSON`,
  );
}

/** @internal */
export const ResolvedByType$inboundSchema: z.ZodEnum<
  typeof ResolvedByType
> = z.nativeEnum(ResolvedByType);

/** @internal */
export const ResolvedBy$inboundSchema: z.ZodType<
  ResolvedBy,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  type: z.nullable(ResolvedByType$inboundSchema).optional(),
});

export function resolvedByFromJSON(
  jsonString: string,
): SafeParseResult<ResolvedBy, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResolvedBy$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResolvedBy' from JSON`,
  );
}

/** @internal */
export const AuthorType$inboundSchema: z.ZodEnum<typeof AuthorType> = z
  .nativeEnum(AuthorType);

/** @internal */
export const Author$inboundSchema: z.ZodType<Author, unknown> = z
  .object({
    id: z.nullable(z.string()).optional(),
    type: z.nullable(AuthorType$inboundSchema).optional(),
  });

export function authorFromJSON(
  jsonString: string,
): SafeParseResult<Author, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Author$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Author' from JSON`,
  );
}

/** @internal */
export const Comment$inboundSchema: z.ZodType<Comment, unknown> =
  z.object({
    id: z.lazy(() => CommentId$inboundSchema),
    thread_id: z.string(),
    content_plaintext: z.string(),
    entry: z.nullable(z.lazy(() => Entry$inboundSchema)),
    record: z.lazy(() => RecordT$inboundSchema),
    resolved_at: z.nullable(z.string()),
    resolved_by: z.lazy(() => ResolvedBy$inboundSchema),
    created_at: z.string(),
    author: z.lazy(() => Author$inboundSchema),
  }).transform((v) => {
    return remap$(v, {
      "thread_id": "threadId",
      "content_plaintext": "contentPlaintext",
      "resolved_at": "resolvedAt",
      "resolved_by": "resolvedBy",
      "created_at": "createdAt",
    });
  });

export function commentFromJSON(
  jsonString: string,
): SafeParseResult<Comment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Comment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Comment' from JSON`,
  );
}
