/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListId = {
  /**
   * A UUID to identify the workspace this list belongs to.
   */
  workspaceId: string;
  /**
   * A UUID to identify this list.
   */
  listId: string;
};

/**
 * The level of access granted to all members of the workspace for this list. `null` values represent a private list that only grants access to specific workspace members via the `workspace_member_access` property.
 */
export const WorkspaceAccess = {
  FullAccess: "full-access",
  ReadAndWrite: "read-and-write",
  ReadOnly: "read-only",
} as const;
/**
 * The level of access granted to all members of the workspace for this list. `null` values represent a private list that only grants access to specific workspace members via the `workspace_member_access` property.
 */
export type WorkspaceAccess = ClosedEnum<typeof WorkspaceAccess>;

/**
 * The level of access to the list.
 */
export const Level = {
  FullAccess: "full-access",
  ReadAndWrite: "read-and-write",
  ReadOnly: "read-only",
} as const;
/**
 * The level of access to the list.
 */
export type Level = ClosedEnum<typeof Level>;

export type WorkspaceMemberAccess = {
  /**
   * A UUID to identify the workspace member to grant access to.
   */
  workspaceMemberId: string;
  /**
   * The level of access to the list.
   */
  level: Level;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const ListType = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type ListType = ClosedEnum<typeof ListType>;

/**
 * The actor which created this list.
 */
export type ListCreatedByActor = {
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: ListType | null | undefined;
};

export type List = {
  id: ListId;
  /**
   * A human-readable slug for use in URLs and responses.
   */
  apiSlug: string;
  /**
   * The name of the list, as viewed in the UI.
   */
  name: string;
  /**
   * A UUID or slug to identify the allowed object type for records added to this list. All new Lists are expected to have exactly one parent object. However, some legacy lists may have multiple allowed parents so the return type of this field is an array.
   */
  parentObject: Array<string>;
  /**
   * The level of access granted to all members of the workspace for this list. `null` values represent a private list that only grants access to specific workspace members via the `workspace_member_access` property.
   */
  workspaceAccess: WorkspaceAccess | null;
  /**
   * The level of access granted to specific workspace members for this list. An empty array represents a list that has granted access to no workspace members.
   */
  workspaceMemberAccess: Array<WorkspaceMemberAccess>;
  /**
   * The actor which created this list.
   */
  createdByActor: ListCreatedByActor;
  /**
   * When the list was created.
   */
  createdAt: string;
};

/** @internal */
export const ListId$inboundSchema: z.ZodType<ListId, unknown> = z
  .object({
    workspace_id: z.string(),
    list_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "workspace_id": "workspaceId",
      "list_id": "listId",
    });
  });

export function listIdFromJSON(
  jsonString: string,
): SafeParseResult<ListId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListId' from JSON`,
  );
}

/** @internal */
export const WorkspaceAccess$inboundSchema: z.ZodEnum<
  typeof WorkspaceAccess
> = z.nativeEnum(WorkspaceAccess);

/** @internal */
export const Level$inboundSchema: z.ZodEnum<typeof Level> = z.nativeEnum(
  Level,
);

/** @internal */
export const WorkspaceMemberAccess$inboundSchema: z.ZodType<
  WorkspaceMemberAccess,
  unknown
> = z.object({
  workspace_member_id: z.string(),
  level: Level$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "workspace_member_id": "workspaceMemberId",
  });
});

export function workspaceMemberAccessFromJSON(
  jsonString: string,
): SafeParseResult<WorkspaceMemberAccess, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspaceMemberAccess$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspaceMemberAccess' from JSON`,
  );
}

/** @internal */
export const ListType$inboundSchema: z.ZodEnum<typeof ListType> = z
  .nativeEnum(ListType);

/** @internal */
export const ListCreatedByActor$inboundSchema: z.ZodType<
  ListCreatedByActor,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  type: z.nullable(ListType$inboundSchema).optional(),
});

export function listCreatedByActorFromJSON(
  jsonString: string,
): SafeParseResult<ListCreatedByActor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCreatedByActor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCreatedByActor' from JSON`,
  );
}

/** @internal */
export const List$inboundSchema: z.ZodType<List, unknown> = z
  .object({
    id: z.lazy(() => ListId$inboundSchema),
    api_slug: z.string(),
    name: z.string(),
    parent_object: z.array(z.string()),
    workspace_access: z.nullable(WorkspaceAccess$inboundSchema),
    workspace_member_access: z.array(
      z.lazy(() => WorkspaceMemberAccess$inboundSchema),
    ),
    created_by_actor: z.lazy(() => ListCreatedByActor$inboundSchema),
    created_at: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "api_slug": "apiSlug",
      "parent_object": "parentObject",
      "workspace_access": "workspaceAccess",
      "workspace_member_access": "workspaceMemberAccess",
      "created_by_actor": "createdByActor",
      "created_at": "createdAt",
    });
  });

export function listFromJSON(
  jsonString: string,
): SafeParseResult<List, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => List$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'List' from JSON`,
  );
}
