/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NoteId = {
  /**
   * The ID of the workspace the note belongs to.
   */
  workspaceId: string;
  /**
   * The ID of the note.
   */
  noteId: string;
};

/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export const NoteType = {
  ApiToken: "api-token",
  WorkspaceMember: "workspace-member",
  System: "system",
  App: "app",
} as const;
/**
 * The type of actor. [Read more information on actor types here](/docs/actors).
 */
export type NoteType = ClosedEnum<typeof NoteType>;

/**
 * The actor that created this note.
 */
export type NoteCreatedByActor = {
  /**
   * An ID to identify the actor.
   */
  id?: string | null | undefined;
  /**
   * The type of actor. [Read more information on actor types here](/docs/actors).
   */
  type?: NoteType | null | undefined;
};

export type Note = {
  id: NoteId;
  /**
   * The slug or ID of the parent object the note belongs to.
   */
  parentObject: string;
  /**
   * The ID of the parent record the note belongs to.
   */
  parentRecordId: string;
  /**
   * The note title. The title is plaintext only and has no formatting.
   */
  title: string;
  /**
   * The plaintext representation of the note content. The line feed character `\n` represents new lines within the note content.
   */
  contentPlaintext: string;
  /**
   * The markdown representation of the note content with formatting applied based on block types and styles.
   */
  contentMarkdown: string;
  /**
   * The actor that created this note.
   */
  createdByActor: NoteCreatedByActor;
  /**
   * When the note was created.
   */
  createdAt: string;
};

/** @internal */
export const NoteId$inboundSchema: z.ZodType<NoteId, unknown> = z
  .object({
    workspace_id: z.string(),
    note_id: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "workspace_id": "workspaceId",
      "note_id": "noteId",
    });
  });

export function noteIdFromJSON(
  jsonString: string,
): SafeParseResult<NoteId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NoteId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NoteId' from JSON`,
  );
}

/** @internal */
export const NoteType$inboundSchema: z.ZodEnum<typeof NoteType> = z
  .nativeEnum(NoteType);

/** @internal */
export const NoteCreatedByActor$inboundSchema: z.ZodType<
  NoteCreatedByActor,
  unknown
> = z.object({
  id: z.nullable(z.string()).optional(),
  type: z.nullable(NoteType$inboundSchema).optional(),
});

export function noteCreatedByActorFromJSON(
  jsonString: string,
): SafeParseResult<NoteCreatedByActor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NoteCreatedByActor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NoteCreatedByActor' from JSON`,
  );
}

/** @internal */
export const Note$inboundSchema: z.ZodType<Note, unknown> = z
  .object({
    id: z.lazy(() => NoteId$inboundSchema),
    parent_object: z.string(),
    parent_record_id: z.string(),
    title: z.string(),
    content_plaintext: z.string(),
    content_markdown: z.string(),
    created_by_actor: z.lazy(() => NoteCreatedByActor$inboundSchema),
    created_at: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "parent_object": "parentObject",
      "parent_record_id": "parentRecordId",
      "content_plaintext": "contentPlaintext",
      "content_markdown": "contentMarkdown",
      "created_by_actor": "createdByActor",
      "created_at": "createdAt",
    });
  });

export function noteFromJSON(
  jsonString: string,
): SafeParseResult<Note, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Note$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Note' from JSON`,
  );
}
