/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SelectOptionId = {
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  /**
   * The ID of the object
   */
  objectId: string;
  /**
   * The ID of the attribute
   */
  attributeId: string;
  /**
   * The ID of the select option
   */
  optionId: string;
};

export type SelectOption = {
  id: SelectOptionId;
  /**
   * The title of the select option
   */
  title: string;
  /**
   * Whether or not to archive the select option. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving.
   */
  isArchived: boolean;
};

/** @internal */
export const SelectOptionId$inboundSchema: z.ZodType<
  SelectOptionId,
  unknown
> = z.object({
  workspace_id: z.string(),
  object_id: z.string(),
  attribute_id: z.string(),
  option_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "object_id": "objectId",
    "attribute_id": "attributeId",
    "option_id": "optionId",
  });
});

export function selectOptionIdFromJSON(
  jsonString: string,
): SafeParseResult<SelectOptionId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelectOptionId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelectOptionId' from JSON`,
  );
}

/** @internal */
export const SelectOption$inboundSchema: z.ZodType<
  SelectOption,
  unknown
> = z.object({
  id: z.lazy(() => SelectOptionId$inboundSchema),
  title: z.string(),
  is_archived: z.boolean(),
}).transform((v) => {
  return remap$(v, {
    "is_archived": "isArchived",
  });
});

export function selectOptionFromJSON(
  jsonString: string,
): SafeParseResult<SelectOption, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SelectOption$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SelectOption' from JSON`,
  );
}
