/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StatusId = {
  /**
   * The ID of the workspace
   */
  workspaceId: string;
  /**
   * The ID of the object
   */
  objectId: string;
  /**
   * The ID of the attribute
   */
  attributeId: string;
  /**
   * The ID of the status
   */
  statusId: string;
};

export type Status = {
  id: StatusId;
  /**
   * The title of the status
   */
  title: string;
  /**
   * Whether or not to archive the status. See our [archiving guide](/docs/archiving-vs-deleting) for more information on archiving.
   */
  isArchived: boolean;
  /**
   * Whether arriving at this status triggers a celebration effect in the UI
   */
  celebrationEnabled: boolean;
  /**
   * Target time for a record to spend in given status expressed as a ISO-8601 duration string
   */
  targetTimeInStatus: string | null;
};

/** @internal */
export const StatusId$inboundSchema: z.ZodType<
  StatusId,
  unknown
> = z.object({
  workspace_id: z.string(),
  object_id: z.string(),
  attribute_id: z.string(),
  status_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "object_id": "objectId",
    "attribute_id": "attributeId",
    "status_id": "statusId",
  });
});

export function statusIdFromJSON(
  jsonString: string,
): SafeParseResult<StatusId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StatusId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StatusId' from JSON`,
  );
}

/** @internal */
export const Status$inboundSchema: z.ZodType<Status, unknown> = z
  .object({
    id: z.lazy(() => StatusId$inboundSchema),
    title: z.string(),
    is_archived: z.boolean(),
    celebration_enabled: z.boolean(),
    target_time_in_status: z.nullable(z.string()),
  }).transform((v) => {
    return remap$(v, {
      "is_archived": "isArchived",
      "celebration_enabled": "celebrationEnabled",
      "target_time_in_status": "targetTimeInStatus",
    });
  });

export function statusFromJSON(
  jsonString: string,
): SafeParseResult<Status, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Status$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Status' from JSON`,
  );
}
