/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Comment, Comment$inboundSchema } from "./comment.js";

export type ThreadId = {
  /**
   * The ID of the workspace the thread belongs to.
   */
  workspaceId: string;
  /**
   * The ID of the thread.
   */
  threadId: string;
};

export type Thread = {
  id: ThreadId;
  /**
   * An array of comments in the thread, sorted by `created_at`.
   */
  comments: Array<Comment>;
  /**
   * When the thread was created.
   */
  createdAt: string;
};

/** @internal */
export const ThreadId$inboundSchema: z.ZodType<
  ThreadId,
  unknown
> = z.object({
  workspace_id: z.string(),
  thread_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "workspace_id": "workspaceId",
    "thread_id": "threadId",
  });
});

export function threadIdFromJSON(
  jsonString: string,
): SafeParseResult<ThreadId, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ThreadId$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ThreadId' from JSON`,
  );
}

/** @internal */
export const Thread$inboundSchema: z.ZodType<Thread, unknown> = z
  .object({
    id: z.lazy(() => ThreadId$inboundSchema),
    comments: z.array(Comment$inboundSchema),
    created_at: z.string(),
  }).transform((v) => {
    return remap$(v, {
      "created_at": "createdAt",
    });
  });

export function threadFromJSON(
  jsonString: string,
): SafeParseResult<Thread, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Thread$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Thread' from JSON`,
  );
}
